### ISSUE TITLE
GD5b65 : account login & password are not remembered after closing GD

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#1007]
## Describe the bug

All is in the title : I've noticed few days ago that my profile was not anymore connected.. When i connect it again, everything is ok.. But if i'm exiting Gdevelop and restarting it : "disconnected" => i have to connect to it each time i launch GD. 

GD5Beta65, Windows 10.

@Bouh have the same issue it seems when we checked together.

**Comment by Silver-Streak** [comment]
I'm going through older issues and saw this one, and wanted to bring attention to it if it is still ongoing.

I am not seeing this behavior in the current versions. Are you still experiencing it?

I'll close out this issue once I get confirmation that you're no longer experiencing it, or if 30 days have passed since this post.

**Comment by KinkGD** [comment]
Hello,

You're right, tested right now, i cannot reproduce the issue with lastest version ! Ty
