### ISSUE TITLE
Piskel editor is unsuable, the window is totally black.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1045]
## Describe the bug
Piskel editor is unsuable, the window is totally black.

## To Reproduce
1. Try to draw with piskel editor

[Reported by many user on forum.](https://forum.gdevelop-app.com/t/piskel-editor-bug/18585)

## Other details
Only B67
W10

**Comment by blurymind** [comment]
I will investigate this issue. Sounds like a problem with the path

**Comment by 4ian** [comment]
Thanks for the report @Bouh. @blurymind let me know if you find anything. I wonder what could have caused the issue.
I'll submit an update once it's fixed :)

**Comment by 4ian** [comment]
It's working in development, might be related to an issue while deploying. Now that I think about it, I have used a different folder than usual for working on GD (as I was working on re-integrating GDevelop.js), and maybe I had an older version of Piskel that was not updated since the time.

I'll make sure I clean the third party editor folders on my computer before re-deploying a new version :)

**Comment by 4ian** [comment]
Not sure this is the cause, but in an ideal world, the import-zipped-editor.js could have a protection against such outdated editors, by computing the checksum of a file for example. Not a high priority though, should not happen again, but would still bring more confidence when deploying.

**Comment by 4ian** [comment]
I've added checksum verification in b764fbbde73f29fd39d157ce32848d69add7545c. In all cases this will be helpful to ensure that the downloaded zip file is the proper one :) Will help preventing any error in future deployments.

Still have a new version to deploy to fix this!

**Comment by blurymind** [comment]
Thank you for fixing the issue so quickly @4ian :)
