### ISSUE TITLE
Create Object event in custom event behavior does not work.

### ISSUE THREAD

**Issue by ddabrahim** [4ian/GDevelop#1061]
## Describe the bug
I am developing a custom event behavior where I need to have at least 2 instances of the object the behavior is attached to. So, what I'm trying to do is inside a doStepPreEvents function I simply check if the number of 'Object' object in the scene is < 2 then create an 'Object' object but it doesn't work, another instance of the object the behavior is attached to is never created. Not sure if it a bug, but this is what I'm trying to do and it doesn't work but the behavior I'm making is useless without this functionality because there always need to be at least 2 instances, so I would like to add this safety check for convenient.

## To Reproduce
1. Create a new extension/Behavior/doStepPreEvents function
2. Inside the function, add the event to create an 'Object' object at position X and Y
3. Run the preview and see a new instance of the object the behavior is attached to is never get created.

**OS:**
Pop!_OS 18.04

**Version:**
beta 69

Thanks.

**Comment by Bouh** [comment]
If it can help me too, I use the "Create an object" action in a behavior on a custom method and my object looks good.
Maybe the problem is on doStepPreEvents?
Here my project file (Don't look too much. It's a mess. Look just the behavior ^^) 
[input - Copie.zip](https://github.com/4ian/GDevelop/files/3219548/input.-.Copie.zip)

**Comment by 4ian** [comment]
So I've not tested particularly "create object" action in behaviors, but it should work. But the condition checking the number of objects is not doing what you think. What you need to understand is this:

* In a behavior, you have a "list" of objects that is called Object (which is the first parameter of all behaviour functions) and this represents the single object the behavior is currently acting on.
* This is because behaviors methods (doStepPreEvents for example) are run separately for all objects (this is by design).

*So that means that you will always get a count of 1 for the number of picked objects for **Object**.*
Think of Object as **this** or **self** in object oriented programming languages.

Potential solution for you: you can create a helper function (not a function attached to a behavior). At this moment you will be able to get all the objects on the scene.

Also:

I'm not sure if it's a proper solution in your case, but note that for custom functions, it's always possible to add a **new parameter** that will require other objects. If you add a parameter of type Behavior after a parameter Objects, then this means that the objects will be having these behaviors (so when using the action in the events sheet, you will be asked for an object with this behavior attached).

This can help to create actions that manipulate different objects with different behaviors (or different objects with the same behavior) 

Also I was planning to check and remove some actions or conditions that does not make sense in the context of a behavior, but I think there is actually very little to none.

**Comment by ddabrahim** [comment]
I would prefer to keep the behavior self containing and not depending on outside functions and parameters to pass objects to the function from outside the behavior. This is something that I personally find really dirty and prefer to avoid doing it in OOP.
Would not be possible then to add a reference to the object and not the instance?

So essentially 'Object' could have been called "Self" or "This" that reference the instance and "Object" could have referenced the actual object the instance is created from.
So the condition "The number of This object.." makes no sense indeed because always return 1 and would be also easier to recognize why but "The number of Object object.." could make sense in my case because it is referencing the object and the condition could return all instances in the scene of the object.

Of course I have no idea how GD works internally so it may be not that simple to implement in GD.

Note:
I have tried and the create object event does not work for me not even without a condition inside the doStepPreEvent function.

Thanks anyway :)

**Comment by 4ian** [comment]
So I've checked and indeed creation of the "Object" itself is not working. This sounds like a bug - though I'm not sure what this implies.

As for Self/This/Object => there can't be a difference, they all are the same thing. In a programming language, you can't use `this`/`self` to magically be able to count all the instances of the class. You have to get an array containing all of the instances... which is what you can be doing by passing an object parameter.

I understand this would have been useful to be able to count the instances that are from the same objects, but using the "Object" for doing this is only going to move us toward strange exceptions.

**Comment by ddabrahim** [comment]
**As for Self/This/Object => there can't be a difference, they all are the same thing. In a programming language, you can't use this/self to magically be able to count all the instances of the class.**

Probably I misunderstand what you tried to explain then because I though the problem is that 'Object' points to the instance the behavior is attached to and because each behavior event is executed individually for each instance, it is always return a list of 1 object when used in the condition to count the number of object. So I thought if we would have a second object 'Object2' that would point not to the instance but to the object the instances created from, the class higher in the scope then it could return a list of instances inherit from the class when used in the condition to count number of object but this is the point when I have no idea how GD works so probably I make no sense here :P  

Thanks for looking in to it anyway, I'll try other options then :)
