### ISSUE TITLE
doStepPostEvents and mouse over are not compatible?

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1064]
I wanted to create a button behavior.
The button creation is working well, but the mouseover and clicks don't work as expected, it's work only on the lastest button added on scene...
I tested looping for all the objects and making a group of objects but I didn't succeed, I must have missed something or it's a bug.
Here the project file :
[input - Copie.zip](https://github.com/4ian/GDevelop/files/3224399/input.-.Copie.zip)

**Comment by 4ian** [comment]
It does work ;) You'll see it's funny:

When you put the mouse over the first object:

* Behavior on object 1 is ran. Mouse is over -> background is set to green
* Behavior on object 2 is ran. Mouse is NOT over -> background is set to red

so it seems like that the behavior did not run, while it actually did.
Remember that behavior functions and lifecycle methods are running *for each* and every *single object* having the behavior, *one at a time*.

So I can safely say that it's not a bug :) If you to avoid this kind of mistake later, prefer changing something like position/size/color of the Object instead of relying on a "global" thing like the background color ;)

**Comment by Bouh** [comment]
I see thank you, i understand what happend now !
This work : 
![image](https://user-images.githubusercontent.com/1670670/58441756-d7a00c80-80e4-11e9-8c59-0ec1368e2b5c.png)

**Comment by 4ian** [comment]
Yep, perfect 👍
