### ISSUE TITLE
Tweening sequences break when triggered on objects of the same type

### ISSUE THREAD

**Issue by CustomLenny** [4ian/GDevelop#1098]
## Describe the bug
When triggering a Tween sequence on one object, then triggering it on the next it doesn't work, then also no longer works on the first object either.
Basically the trigger once thinks it's been triggered once and will never trigger again after switching to another object (as far as I can tell).

## To Reproduce
Included basic game zip, follow instructions in game for small example
[IssueTween.zip](https://github.com/4ian/GDevelop/files/3277417/IssueTween.zip)

## Other details
GD b73

**Comment by Wend1go** [comment]
This is actually by design. A tween that finishes can't be removed automatically. You need to remove the finished tween manually before you start the next one like so:
![grafik](https://user-images.githubusercontent.com/7413059/59372063-f0482d80-8d46-11e9-9309-7226d84fef24.png)
I'm not happy with this either, since it is not very intuitive but I don't know how to do it better.

Another thing:
If you want the platforms to return to their original Y position after finishing the tween animation you should consider adding a fixed coordinate value for the animation instead of `Platform.Y() - 8`. If you bump into the plattform again before it has moved down again completely, it will stop and start the animation anew from the position it currently is. Better save the original Y position into an object variable when the scene starts and use 
something like `Platform.Variable(OriginalY) - 8` for the animations destination.

**Comment by CustomLenny** [comment]
Ah! Thankyou. I must've missed that step in the tutorial I watched, either that or they didn't include it themselves.

_On a side note_: Is there a way to have the platform save its original Y value as a variable on start so that all boxes follow that, or do I have to enter it into ever box I drag onto the scene?
