### ISSUE TITLE
Idea: Bundle a user friendly generic json editor

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#1145]
The idea came to me while embedding yarn editor. Yarn uses json files- but does it for a very specific yarn format that is dialogue trees in yarn style data structure.

What if we also have a generic json editor to open and edit any json file - inspect it for proplems and so on. That would enable people to create/edit their own json files in any data structure they like to declare for their own usecase - straight inside gdevelop. In a user friendly way.

A cool option I found is this editor
https://github.com/josdejong/jsoneditor
![68747470733a2f2f7261772e6769746875622e636f6d2f6a6f7364656a6f6e672f6a736f6e656469746f722f6d61737465722f6d6973632f6a736f6e656469746f722e706e67](https://user-images.githubusercontent.com/6495061/60741710-687acb00-9f62-11e9-9642-3f14939e5b5e.png)

I can even embed it in the same PR as yarn

What do you think :) is this a feature creep or something you would find useful?

**Comment by blurymind** [comment]
I  guess we kind of have something similar with the structured variable editor. Not sure if we can have that much use of it, since gdevelopjs has no conditions/actions/expressions to deal with arrays (to my knowledge)

**Comment by Bouh** [comment]
If it is just adding a JSON editor for a feature so a minority of users use it, knowing that the code required to have the editor must be a little big.
I don't think it's worth it. Because :
I think it's not useful, because it's almost secondary, (I mean in relation to sprites and Pixel Editor)
Code added is big. Then there are external software to do it, and a notepad is enough for text (Json).

In my mind I think that if something is already feasible with a software made for it and/or that it is simple. Then there is no need to integrate it into another software (Here GD).

Pixel is good because it is a main feature of any game to have sprites.
For Jfxr it's perfect because a sound tool is complicated for a novice. 
But a text editor is easy :)

**Comment by blurymind** [comment]
Other story-centric engines have made their own editors for this - in a similar way. What makes Yarn a good fit for GD is really its open source nature and the fact it's battle-tested on a number of successful games (not just NITW).

I personally like it because it is easy to maintain. It's source code is very simple

**Comment by Bouh** [comment]
> My only interest in this was in its ability to debug JSON files and correct mistakes

The debugger inside GD5 can display values, maybe the json structure is display? And we can edit value in this debugger :)

**Comment by blurymind** [comment]
ah yes, thats true. I will close  this now

**Comment by 4ian** [comment]
An "external editor" could be done at some point, but we could actually reuse the existing json editor used in the debugger :) I was also thinking of using it for the "preview" of the json resources
