### ISSUE TITLE
Filesystem example

### ISSUE THREAD

**Issue by piyushpalawat99** [4ian/GDevelop#1155]
Hi!

I'd like to submit a new example to be added to GDevelop.
Here is the link to download it: 
[filesystem.zip](https://github.com/4ian/GDevelop/files/3410718/filesystem.zip)

It is a simple example demonstrating the use of filesystem. It can also serve as a one-level file explorer example for GDevelop. Any suggestions to simplify the example or to make any other changes are welcome.

I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by 4ian** [comment]
Thanks for this! A few comments:

* The first scene is called NewScene, can you give it a proper name like the others?
* When a directory is created, it's not clear that it's done. Would be better to add a confirmation message telling that it's successfully done. The user should always know what happen without guessing.
* "Left click" to validate looks rather unusual and strange. Better make a "Create" button or something like this - or at least use the Enter key.
* Could we do without timers/double click in the first scene? This make events looks complicated for nothing - it's an example so let's focus on the interesting part: the Filesystem extension :)

**Comment by piyushpalawat99** [comment]
Thanks for the feedback.

> The first scene is called NewScene, can you give it a proper name like the others?
- Sure, I'll change the name of the first scene.
> When a directory is created, it's not clear that it's done. Would be better to add a confirmation message telling that it's successfully done.
- I'll modify the text of the text object that displays the message to create a directory.
> "Left click" to validate looks rather unusual and strange. Better make a "Create" button or something like this
- I'll work on the "Create" button.
> or at least use the Enter key.

The reason I couldn't add an action to check the enter key was when it checked the "Enter" key press condition, the key press is already added to the directory name, i.e. the directory name ended with an empty new line in the end which would result in an error in the action.
> Could we do without timers/double click in the first scene? This make events looks complicated for nothing - it's an example so let's focus on the interesting part: the Filesystem extension :)
- Would it be fine if a single click is used rather than a double click to open the directory and remove the "SelectDesktop" and "SelectDocuments" objects?

**Comment by piyushpalawat99** [comment]
I have updated the example. These are the changes.
- Now we have to click (just once) on a directory to open it.
- To create a new directory, a "Create Directory" button has been added.
- After the creation of a new directory, a new message is displayed indicating that the directory has been created.

Here is the updated file:
[filesystem.zip](https://github.com/4ian/GDevelop/files/3417011/filesystem.zip)

**Comment by 4ian** [comment]
Sorry for getting back to you late. I've checked your new zip file but there is still the need to double click on a folder. Have you uploaded the proper zip? :) Or am I missing something?

**Comment by piyushpalawat99** [comment]
Hey @4ian no worries.
Yes, I uploaded the wrong zip 🤦‍♂. I apologise for the inconvenience caused.
Here's the one I wanted to upload: 
[filesystem.zip](https://github.com/4ian/GDevelop/files/3439559/filesystem.zip).

**Comment by 4ian** [comment]
Cool :) Almost there, could you take a look at:
* Naming the variable that is storing the potential error "Error". A variable named "Variable" will be very confusing for beginners :)
* Check if you can fix the text going out of the screen:
  <img width="699" alt="Screenshot 2019-07-28 22 18 13" src="https://user-images.githubusercontent.com/1280130/62013060-b95a9980-b185-11e9-8f56-0417752bdf2e.png">
* Also you can remove "Start" and fix the typo "clilck": "Type the name of the new directory and click "Create Directory" button once you're done."
* nitpicking: I would prefer to have an event like this:  
```
Condition: The text of scene variable Name is = ""
Action: Set the scene variable Name to "NewDir"
```

rather than duplicating the event to create the directory - it's messy and error prone in case you want to add some logic because you have to duplicate the logic (for example, if you update the name of the Error variable, it's easy to forget to change it in the other action).
An event like I shown will make more sense. 
I think you can also remove the "Object dir is visible".

I know it's a lot of things but it's super important to have very simple examples and crystal clear, concise events - otherwise new users will start making messy events :)

Almost there! ;)

**Comment by piyushpalawat99** [comment]
I have done the changes :)
For a quick look, here is a screenshot of what the desktop events look like: 
![filesystem](https://user-images.githubusercontent.com/31609516/62014538-e62ba280-b1bf-11e9-94fd-28c8d19045cd.png)
The trigger once conditions may seem to be overused, but the events were not giving the desired results without them. Any other feedbacks are welcome.
Here is the zip file: 
[filesystem.zip](https://github.com/4ian/GDevelop/files/3439679/filesystem.zip)

**Comment by Wend1go** [comment]
You can get rid of the "Trigger once" conditions by checking for "key/touch is released" instead of pressed.
The first event in the screenshot is currently triggered 60 times per second while the "n" key is held down which creates lots of objects on top of each other.
Could you also move the event with "At the beginning of the scene" to the top of the event sheet?
Since it is holding initialization logic, moving it to the top of the event sheet would give a better overview about the order in which events are executed.

**Comment by piyushpalawat99** [comment]
@Wend1go Thanks for the feedback :)
Here's the changed event sheet:

![filesystem](https://user-images.githubusercontent.com/31609516/62031910-09794080-b206-11e9-8181-a96debd7bc37.png)

And you can 
[check out the entire project here.](https://github.com/4ian/GDevelop/files/3440932/filesystem.zip)

**Comment by 4ian** [comment]
Added for next version :) Thanks!

I still think this example got a bit over complicated for just demonstrating the creation of directories. Let's strive for simplicity in the future and keep only one scene, with maybe something to select between document/desktop. I've also moved the action that was repeated ("Your new directory has been created") and I've replaced the condition testing the text of NewFileDesktop by a condition testing the new of "Dir" object. Testing the text is fragile because if I update the text object then the condition is not working anymore ;)

Thanks for your time on this!
