### ISSUE TITLE
Editor hangs when selecting an object

### ISSUE THREAD

**Issue by eon-s** [4ian/GDevelop#1157]
Using Ubuntu 19.04 and GDevelop 5 beta 65 and 75

Sometimes, when selecting an object, the editor hangs for a very long time before showing the properties and the message panel at the bottom.

The JS console shows this, but nothing more that can give a hint of what produces the hang:

```
[Violation] 'click' handler took 50414ms
55.bf6fc99b.chunk.js:1 [Violation] 'pointerdown' handler took 100665ms
raven.js:1137 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Another thing I have noticed is that the editor takes a long time to initialize (the first screen) before this happens, not sure if related.

I do not know how to reproduce consistently, running from the terminal, the application do not throw any message.

**Comment by 4ian** [comment]
Is this reproducible with a particular game, or happening randomly at first sight?

**Comment by eon-s** [comment]
This can happen with any project, seems random.
After awhile of not using the editor the problem disappears or reappears, but cannot see anything in the JS console different from a regular usage.

**Comment by 4ian** [comment]
Can you open a task manager and see if there is a huge CPU usage at this time and/or RAM usage.

**Comment by eon-s** [comment]
No high CPU usage or noticeable memory leaks. 
I wonder if dbus is being funny, I have noticed a couple of system messages about dbus and gdevelop, I will check that the next time the problem appears (I'm not getting that behavior now that I'm looking for it...).

**Comment by eon-s** [comment]
Finally could reproduce it with beta 79 and the profiler enabled, the problem starts with pointer down event, here is the profiler file saved with the dev tools (it is big because it has several minutes of nothing).

[Profile-20190806T004156.zip](https://github.com/4ian/GDevelop/files/3470270/Profile-20190806T004156.zip)

Also it seems to happen with any element of the editor, not only objects but things like "close tab" buttons too.

**Comment by 4ian** [comment]
Really interesting, thanks for capturing this profile trace.
I can't see where the issue lies in GDevelop, because the profile indicates that the time is spent in a function "ipcRenderer.sendSync" but there is no call to sendSync in GDevelop :/ 

I wonder if it's a Chromium/Electron related issue, and that updating Electron would fix the issue.
I see for example in v4 release notes (https://electronjs.org/releases/stable?version=4&page=5) that "Public IPC channel (ipcRenderer / ipcMain) is no longer used to implement Electron internals (remote module for example). #13940"
(Added a card here as it has to be done anyway at some point: https://trello.com/c/yp3IczuR/343-update-electron-to-v4-or-more)

**Comment by Silver-Streak** [comment]
@eon-s I am going through older issues to bring attention to them or close them out.

GDevelop (and Electron) has been updated quite a few time since this occurred. Are you still experiencing this?

I'll close this issue out upon receiving confirmation that this is resolved, or if 30 days have passed from this post.

**Comment by eon-s** [comment]
It seems to be fixed now, no idea when or what fixed this, so closing.
