### ISSUE TITLE
Implement Phaser framework

### ISSUE THREAD

**Issue by DaniellMesquita** [4ian/GDevelop#1170]
https://github.com/photonstorm/phaser

(I'm not maintainer or member of it. Its because Phaser is open-source and the leading framework for games, which would make GDevelop modular and more focused on its own)

**Comment by 4ian** [comment]
GDevelop is already based on Pixi.js: https://github.com/pixijs/pixi.js

Phaser itself is a very good game engine, but re-implementing all the runtime using Phaser instead of Pixi.js is a very long task that probably won't be bringing tons of differences because Pixi.js is also very complete and very performant.
Moving to Phaser could happen in the future, but it should be motivated by a main, documented win on some part (measured performance with benchmarks, new features not in Pixi.js) to justify the time investment on doing this rather than working on other features :) 
Also, note that the game engine is already able to support multiple renderers. Notably, there is an experimental Cocos-2D JS renderer, so anyone that think that Phaser will do a better job than Pixi.js can try to make a Pull Request integrating Phaser - I'll be interested to look at this and help if this brings lots of advantages :)

I'm closing this issue as issues are mostly for bugs rather than feature requests - feel free to continue the discussion.
