### ISSUE TITLE
A bug in event editor trying to edit the symbols in comparing events!

### ISSUE THREAD

**Issue by PrashantGyawali** [4ian/GDevelop#1175]
(Solved)

**Comment by piyushpalawat99** [comment]
Looks like you haven't clicked on "≥ (greater than or equal to)". Clicking on it brings down the drop-down. And if you have clicked on it and still getting the same result, the bug seems to solved in beta76. Attaching a screenshot confirming the same.

![Annotation 2019-07-31 155846](https://user-images.githubusercontent.com/31609516/62205159-73334f00-b3ac-11e9-9513-ff4582aca5be.png)

Though I'm not really sure why there's a horizontal scroll and why can't the dropdown's width be increased a bit so that there's no need for horizontal scrolling.

**Comment by piyushpalawat99** [comment]
@PrashantGyawali You need to close the issue so that it does not show up in the already existing issues ;)

**Comment by 4ian** [comment]
Don't erase your message or title, this can be useful for other users when they are searching for issue. Instead, close the issue
