### ISSUE TITLE
Bug in windows exported game

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1191]
## Describe the bug
When we export game for windows (Zip file and auto-installer file) the game cannot be launched because we have one error about node.dll (screenshoot below)

Export doesn't work on b79, but working on b77.
I can't test on b78 (Limited to 2 export/day)

I'am wondering if this fail come from my PR #1179 :/ 

## To Reproduce
1. Open platformer example
2. Export with Windows Zip file and/or auto-installer file (i can't test other export)
3.a Install game with auto-installer file, game crash and show 
![installateur_windows](https://user-images.githubusercontent.com/1670670/63092048-ad7e1e00-bf60-11e9-9fbc-67d9c7f5ef35.png)
3.b Launch game from zip file, nothing is launched, no errors, nothing. 

The logs from exports showing nothing: 
> Build succeeded, no log provided.

[Other user have same issue on W10](https://forum.gdevelop-app.com/t/build-pipeline-bug/20131/2)

**Comment by 4ian** [comment]
Thanks for reporting this, not sure what is happening. Can you double check that things are working with beta 77 and 78?

> I can't test on b78 (Limited to 2 export/day)

I set up a pro subscription on your account so you can test

**Comment by 4ian** [comment]
Would be cool if you could also test with/without icon to see if there is a difference

**Comment by Bouh** [comment]
I don't understand i nothing changed (only reinstall B79) on my test workflow and it's working now...

```
2019-08-15 21:51:50
B79 
without icones
export Win10 msi + Zip
Result : Working
----------
2019-08-15 21:46:22
B79 
With icones
export Win10 msi + Zip
Result : Working
----------
2019-08-15 13:12:06
B77
without icones
export Win10 msi + Zip
Result : Working
----------
2019-08-15 12:57:32
B79
without icones 
export Win10 msi + Zip
Result : FAIL
```

**Comment by 4ian** [comment]
So while writing the previous messages, I also restarted the workers building the games. Seems that one was kind of stuck and I guess bugged. 

That's why I wanted to still double check if it has something to see with the version number, but I was thinking that it was unrelated.

In the future, I want to move these workers to "on demand workers", meaning that when you run an export, the worker would be created on the fly and destroyed just after the game is built (contrary to the current workers, which are servers waiting for things to compile and only destroyed in case of issues).
These on demand workers should reduce the issues a lot, because for every export it would start from a clean state.

**Comment by OniGiri-TT** [comment]
Sorry for the late reply:
I've checked B78 and it throws the error after the first install. But after reinstalling B78 the build pipeline works fine and the builds are running.

**Comment by 4ian** [comment]
I'll consider this was a transient issue due to the infrastructure, so closing this :)
