### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [4ian/GDevelop#1211]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by 4ian** [comment]
This is an interesting project - any help to work on this is welcome. I took a look at this years ago but it was not very mature at this time. Might be easier to integrate now with the CMake example? 
This would still need investigation on what is the size of such a library integrated to games (because you're embedding the whole LLVM/clang compiler I guess) surely a few megabytes, and what is the expected speed gain - typically events are not slow by themselves, it's the condition/action that are slow (for example, if you check collisions between tons of objects).

I'll close this as this is a feature request/idea and I keep only bug reports here. Discussion can still continue! :)

**Comment by blockspacer** [comment]
@4ian  
> This would still need investigation on what is the size of such a library integrated to games 

End user usually can`t modify scripts. Some apps may benefit from script-to-native 'conversion'.
Develop much faster with Cling help (dev/debug build), release same code compiled without Cling at all (release build).

Also: you can embed Cling for some platforms even in release build, if you want.

**Comment by 4ian** [comment]
I see - I was thinking you were suggesting this to be used as an alternative to JS code event - so end user would be able to write scripts in C++. If you only think about the editor, then I'm not sure how we would use cling because the C++ is compiled to webassembly using Emscripten (so that the whole editor can even run in a web browser).

Or did I miss what would be the usage of cling in your mind? More details would be useful :) I see the way it works but not where it would be useful in GD precisely.
