### ISSUE TITLE
Big perfomance difference between Linux preview and exported.

### ISSUE THREAD

**Issue by MilkWebhook** [4ian/GDevelop#1222]
## Describe the bug:
I preview, and it goes very stable. But then, i export to Linux to try and it is unplayable.

## To Reproduce
1. Use a computer with Linux.
2. Make a game in which you can see your player move arround.
3. Preview. Smooth, true?
4. Export to Linux (.appimage)
5. Right click .appimage / can be executed as a program. (else, it doesn't work.)
6. See the speed difference.

* Please include a link to a game if possible:
https://gamejolt.com/games/p1xg4m3_the_game/432114

## Other details
* Firefox (Browser that I use)
Laptop Name: HP 255 G4
1.4Ghz Dual Core w/ AMD Radeon R2 Graphics
5GB RAM (All the ram was assigned)

* Desktop app.
* (Left blank, no more context.)

**Comment by 4ian** [comment]
Most probably because GDevelop is running with Electron 3 but the exported games with Electron 2 - so a older version of Chromium internally. And I guess this version is becoming too old or may not be running with WebGL on your system for whatever reason due to graphics driver. 
I'll upgrade games to use Electron 3 in the next version - which hopefully will fix the issues.

**Comment by MilkWebhook** [comment]
Okay, thanks.
