### ISSUE TITLE
Add a boolean variable type for object, scene and global scopes

### ISSUE THREAD

**Issue by williamd1k0** [4ian/GDevelop#1229]
## Description
Hi, I'm a game developer, but I'm actually a Godot user. Yesterday, I tried GDevelop to help a friend who was using it on a gamedev course (GDevelop was needed for a specific task).
When using GDevelop to help my friend, we realize that the engine does not have a boolean type for variables.
That's a bit weird, even though you can work around this using numbers, it is not an user-friendly solution.
Note: I know that Construct 3 has a boolean type and "actions" to set and toggle.

## Solution suggested
- Add the boolean type for object, scene and global scopes.
- Add a "*{variable}* is enabled/on" condition.
- Add set and toggle actions.

**Comment by 4ian** [comment]
This is indeed missing :) And using numbers (0/1) to simulate boolean is sub-optimal (even if it works for now). Note that for now, behavior properties can still be set as booleans, offering action to toggle them and condition to test them.

I've added a card for this on the roadmap: https://trello.com/c/Q0sA9LzS/361-support-booleans-for-variables

As done for feature requests, I'll close the issue but the discussion can continue here. 

Something that might be needed too for this:
- Update the variable editors in the IDE to support setting True or False as the initial value of a variable (which would be a boolean). Right now, it's either a string, or a number if the string can be converted to a number. A bit of rework would be needed to avoid this auto inference of the type I think - or at least show this in the IDE.
- We could go further and add support for boolean expressions, so you could do things like `not(VariableBoolean(MyOtherBooleanVariable))` (exact syntax to be discussed, might be better to use !, && and || operators like in C style languages) - instead of having just the choice between Yes and No for boolean parameters like it's the case now.
