### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by luizbills** [4ian/GDevelop#1288]
GDevelop could have a marketplace for free and paid game assets and editor extensions. Part of the sales would go to development. And I believe this would attract other artists and developers to our community and even help in promoting the game editor.

**Comment by luizbills** [comment]
Instead of charging a commission on sales, it could charge a monthly fee to sell premium items.

**Comment by 4ian** [comment]
Please rather use the forum for ideas/feature requests :) 
In theory yes that would be great to have a store/marketplace. In practice, making something that is really good is hard because you have to come up with: 
- The store interface/website,
- The upload/download/hosting
- The account management (we have accounts in GDevelop so we could reuse them)
- The payment (kind of feasible with Stripe marketplace) 
- The legal things
- The moderation of content (do you moderate after upload, before making things available online, etc...) - which takes time in addition to the maintenance of the game engine and the software itself.
- The integration with the engine.

So while I would be all for it if we had the resources, for now we would a pragmatic solution or an integration with something already existing maybe?

**Comment by blurymind** [comment]
I quite like how itch.io does it :) you can put out stuff for free and people donate if they want to. You can also made it paid with minimal donation.

Why not integrate itch.io itself inside the newIde. Then it could handle accounts,payments, etc.
Itch has an open source app btw
https://github.com/itchio/itch

I wonder  if they have some sort of an api that can be used to use their services in more integrated ways

**Comment by luizbills** [comment]
> Why not integrate itch.io itself inside the newIde.
The marketplace could help increase your revenue and help the project grow faster.

> Then it could handle accounts, payments, etc.
Yes, but it wouldn't help the project much. And if someone wanted to sell an extension, the buyer would have to download and import manually. 

Without an official marketplace, developers won't feel too confident about making paid extensions or paid tutorials.

**Comment by blurymind** [comment]
itch is a legit place to sell content to develop games. It is already full of both 2d game assets, other tools and code for different game engines.

If you actually look at the content, and the level of quality of content - you will see that it is probably our best option

**Comment by luizbills** [comment]
Alright. You convinced me
