### ISSUE TITLE
Unable to quit GDevelop or open anything from toolbar if a project isn't open

### ISSUE THREAD

**Issue by Baylissimo** [4ian/GDevelop#1294]
After opening GDevelop and before opening or starting a new project any attempt to open the toolbar, like for example to close GDevelop from file, it just says Gdevelop still loading.

## To Reproduce
1. Go to 'toolbar' after opening GDevelop
2. All options say Gdevelop is still loading.

<img width="309" alt="Screen Shot 2019-11-18 at 11 00 55 am" src="https://user-images.githubusercontent.com/15341856/69016587-a6e5c380-09f3-11ea-91da-38c0a9270a33.png">

## Other details
* Using MacOS Catalina 10.15.1
* GDevelop beta 82

To access toolbar of course I can open or start a project then quit.

**Comment by Phenomena3** [comment]
Happening Windows 8.1 laptop and some other machines too, I think.

**Comment by 4ian** [comment]
If you create/open a project, the menu is properly appearing then?

**Comment by Baylissimo** [comment]
Yes. When creating/opening a project then the menu appears properly. And continues to appear properly after the opened project is closed and no other projects are open.

**Comment by Bouh** [comment]
This is only on b82&b81.
Same for few others bug, B82 are pretty bugged in UI.

https://forum.gdevelop-app.com/t/menus-are-loaded-infinitely/21256
https://forum.gdevelop-app.com/t/expression-search-issue/21260
https://forum.gdevelop-app.com/t/user-interface-regression/21351

**Comment by 4ian** [comment]
I referenced these in https://github.com/4ian/GDevelop/issues/1295

**Comment by Bouh** [comment]
insert [at line 131-132](https://github.com/4ian/GDevelop/blob/3bd9432b5e5140f73c29f2cd83f68d1bcb56b785/newIDE/app/src/MainFrame/ElectronMainMenu.js#L132)  
      `this._buildAndSendMenuTemplate();`
or 
`this.forceUpdate()`

**Comment by 4ian** [comment]
I'm surprised because that should in theory already work, because there is `componentDidUpdate` there:

https://github.com/4ian/GDevelop/blob/3bd9432b5e5140f73c29f2cd83f68d1bcb56b785/newIDE/app/src/MainFrame/ElectronMainMenu.js#L134-L139

that should be called after each rendering of the component (which is the case when the app is rendered on start). I thought that `this.props.i18n.language` is never undefined, so when `componentDidUpdate` is called for the first time, `this._language` which is undefined should NOT be equal, so `this._buildAndSendMenuTemplate();` should be called.

I can't reproduce this issue on my macbook nor on a Windows computer but this being said, we can be on the safe side and assume that after the component is mounted, `componentDidUpdate` will not consider that the language has changed. And so we should call `this._buildAndSendMenuTemplate();` to trigger the menu update.

(`this._buildAndSendMenuTemplate();` is preferable to `this.forceUpdate` because forceUpdate is a generic way to say "Hey React please re-render this component on screen" which can encompass different things. While calling `this._buildAndSendMenuTemplate();` is very specific: "the menu is probably not up to date so please do it now").

@Bouh do you want to make a PR to add this as you've found the solution? :)

**Comment by Bouh** [comment]
If we can add React debugger with pixiJs debugger in next build this is welcome.
I've tryed to remove the condition in `componentDidUpdate` and just keep `this._buildAndSendMenuTemplate();` but isn't working, so `componentDidUpdate` are never called.

**Comment by 4ian** [comment]
Right, well better call `this._buildAndSendMenuTemplate` at the end of componentDidMount so that we're sure it's called at least once. `componentDidUpdate` should only be used for when the language is changed.
