### ISSUE TITLE
The point of an object is updated too late.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1300]
A forum user reported that the update of the point is late.
I'm picking up his post: 

## Describe the bug
This bug is an isolated version of https://forum.gdevelop-app.com/t/action-ordering-issues/21620

[Project showing the bug](https://drive.google.com/open?id=1hNlvzME3Nu8mTz90n8E7mWY0btpaEGk8)

## To Reproduce
(Arrow keys to shoot (no diagonals))
1. Press a direction
2. Press another direction
3. The first bullet of the new direction is spawned at the old direction animation's tip point but moves in the new direction

## Other details
GDevelop 5 Beta 83
macOS Mojave

**Comment by KinkGD** [comment]
hum, could it be linked to https://github.com/4ian/GDevelop/issues/879 ? One thing is sure, points of the sprites have issues... 

I always have to spawn an object, then at frame+1 select the correct animation, then at frame +2 select the PointX:PointY to attach something on a sprite (with position or physic).

**Comment by 4ian** [comment]
That seem indeed very related to #879. 
To fix that and #879 I think we have to fix the sprites so that when the animation is changed we set a "_spriteDirty" flag to true. Then, when the object is updated by the game engine (`gdjs.SpriteRuntimeObject.prototype.update`), we update the animation and set "_spriteDirty" to false. 
If before that, something else need to get information from the sprite (basically, the points and maybe width/height too), we check if _spriteDirty is true and if yes we update the animation before proceeding.

Originally, the fact that the animation is not immediately changed is to avoid extra work if events are changing the animation multiple times (from animation 1 to 2, then in the next event from 2 back to 1). But this might be creating more problems than anything else.

**Comment by 4ian** [comment]
> I always have to spawn an object, then at frame+1 select the correct animation

Isn't changing the animation immediately after creating the object working? So you would "just" have to wait frame+1 to select the pointX;pointY to attach something to your sprite.

**Comment by KinkGD** [comment]
> 
> 
> > I always have to spawn an object, then at frame+1 select the correct animation
> 
> Isn't changing the animation immediately after creating the object working? So you would "just" have to wait frame+1 to select the pointX;pointY to attach something to your sprite.

Not always ! I can use frame +1 to select the "good" points, only if it's at least the second instance of the object to be spawned **after** scene creation (or if multiples instances are created at the beginning of the scene).. 
And sorry, i'm not sure to explain it clearly because i use a workaround for longtime now (january!), but by creating objects on the beginning of the scene + changing their animation in the same event + then attach physical revolute wheel at the right PointX;PointY, i have to wait the frame +2 to get the good sprite point positions. 

Details :
1) On beginning of the scene the object is created with animation 0, and in the same event, i ask for animation change
2) At frame +1, the correct animation number (for example 2), changed "at the beginning of the scene" is finally applied... But points of the sprite aren't usable yet, if i try to create the revolute wheel at this point, it's points from animation #0 that will be used...
3) So it's why i create my physical revolute wheel at frame +2...

Let me know if you want precisions.

**Comment by 4ian** [comment]
That's very clear :) The test games attached here and yours are very very helpful. Should have a fix for this!

**Comment by KinkGD** [comment]
:)

Le jeu. 28 nov. 2019 22:34, Florian Rival <notifications@github.com> a
écrit :
