### ISSUE TITLE
Strange output in eventsheet

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1326]
## Describe the bug
It's as if a variable has two different possible outputs.

A user brought up what he thinks is a bug.
I've cleaned up the file as much as possible.
I'm pretty sure there's something wrong. But I couldn't tell where it came from.

![errors_on_files](https://user-images.githubusercontent.com/1670670/71271098-75924780-2353-11ea-958c-2f7625c5e0c8.png)

## To Reproduce
See files.
[Projects_to_verify.zip](https://github.com/4ian/GDevelop/files/3989335/Projects_to_verify.zip)

## Other details
GD5 B82, and dev with last commits at this day

**Comment by 4ian** [comment]
In the first events (bugged.json), the action changes the variable of "check". The "if one of these conditions is true" is doing the "union" of picked objects. If you click on "a", then:
* No cursor on "check" => the list of picked "check" is empty (condition is false)
* Cursor is on "a" => the list of picked "a" contains one "a" (condition is true).

This means that the "or" condition is true, and then list of picked objects that I mention are carried over to the next condition, next to the action.
In the action, if you clicked on "a", the list of picked "check" is empty => no variable is updated.

**Comment by Bouh** [comment]
In this type of case we don't need to have a selection.
Doesn't the selection that is made at the end of the OR block seem more logical if it doesn't exclude the objects?

You will surely have a good counter-example, so why not have a boolean to filter the selection, or not have it on the "OR".

I understand that the engine works this way but here it's a bit strange, well in 11 years I see it for the first time it's not a big problem but it's confusing.

**Comment by 4ian** [comment]
> You will surely have a good counter-example

I do 😄For example, let's say you want to do something as soon as one kind of object or another is verifying a condition:

Conditions: 
* OR:
  * X position of ObjectA < 100
  * X position of ObjectB < 100
Actions:
* Delete ObjectA
* Delete ObjectB

The example is a bit contrived, because actually a group containing ObjectA and ObjectB would be better... but still here you can see that I intended to delete the objects A or B when they go at a certain position (X position less than 100).
If we do not exclude objects - in other words, if we don't pick all objects in the OR - then if an object A goes below 100px on the X axis then it's deleted and... **all** objects B are also deleted! Much more surprising no?

> I understand that the engine works this way but here it's a bit strange, well in 11 years I see it for the first time it's not a big problem but it's confusing.

Yep maybe we could add in the description that "All conditions inside the OR are executed. Objects picked in these conditions are then carried to the next conditions or actions. If none of the conditions inside the OR are true, then the whole condition is considered false."

**Comment by Wend1go** [comment]
@4ian I find your example a little confusing to be honest. If I made a logic block like that, I'd expect that both ObjectA AND ObjectB get deleted when either object is below 100.
If I wanted it to only affect one type of object, I'd add a custom function and check for ObjectA in one condition and for ObjectB in another.
When I started using GD, I was confused about the way the engine filters for objects. And because of that filtering the logic I wrote often didn't do what I expected.

**Comment by 4ian** [comment]
Maybe the example is not the best I could find, but I still think the implementation is currently making sense because you can "fix" the example that Bouh gave by adding a "Pick all objects check" before the action and you're good.
Same for my example, if you really want to delete all objects A and B, you add a "Pick all objects A", "Pick all objects B" and all objects get destroyed. If you want to only get then the objects that satisfied the OR conditions... you do not add a "Pick all objects" and it works.

I think most of the confusion comes from an expectation of "OR" (and [same for the discussion for "Else"](https://forum.gdevelop-app.com/t/if-else-event-we-have-a-solution/21168/15)) to act like a strictly boolean operator - but we're dealing with list of objects.
We can maybe rename it or enhance the description. Pretty sure this is more a problem of documentation than anything else:

Let me try to formulate this as: 
1. *"If you talk to GDevelop about an object in the conditions, only the objects that matched the condition will be picked in the actions"*. (In my example, you "talked" about Object A and Object B to GDevelop. So GDevelop will only deleted the ones that fulfilled the conditions).
2. *If you talked to GDevelop about an object, but want to act on all objects* (strange but can happen rarely), use "Pick all objects".
3. That's it (hopefully :))

Or if you have an alternative implementation I'm happy to also consider it, but this requires a careful and complete explanations of all possible use cases (without objects, with objects).

**Comment by 4ian** [comment]
Note that we can consider adding a "OR, but that forget objects that have been picked" - but if we prove that the current model of "OR" (that keep objects picked) + "Pick all" is not equivalent.

**Comment by Wend1go** [comment]
```

    OR:
        X position of ObjectA < 100
        X position of ObjectB < 100

Actions:

    Delete ObjectA
    Delete ObjectB
```
It might be just me, since I have a VB.Net background. But when I see the logic blocks, my brain immediately converts them to the following code:
```
If (ObjectA.Position.X < 100 Or ObjectB.Position.X < 100) Then
    ObjectA.Dispose()
    ObjectB.Dispose()
End If
```
Where a condition corresponds to an "If" clause and the actions to methods inside that if clause.
So to me it seems illogical that one method inside the "pseudo If clause" is not executed.
Maybe people without any knowledge of programming think different about it.
It took me some time to realise how the filtering method works.
Would be interesting to read about the issues others had when they just started using GD.

**Comment by 4ian** [comment]
This would be true if we were not dealing with list of objects. For example, if you are doing a OR with variables, it works like an usual OR condition:

```
Conditions:
 OR: 
   Scene variable A = 1
   Scene variable B = 1

Actions:
  Do something
```

is roughly equal to `if (scene variable A = 1 OR scene variable B =1) Then doSomething() End If`

But as we're dealing with objects, what conditions really are in this case is "filters".

```
Conditions:
    OR:
        X position of ObjectA < 100
        X position of ObjectB < 100

Actions:

    Delete ObjectA
    Delete ObjectB
```

is roughly:

```
const objectsA = scene.getAllObjects("A").filter(object => object.X < 100)
const objectsB = scene.getAllObjects("B").filter(object => object.X < 100)

if (objectsA not empty OR objects B not empty) {
  for each object in objectsA: delete object 
  for each object in objectsB: delete object
}
```

Again not saying that your reasoning is false 😉 - it's just that events are more than just if/else :) Because they are made to be able to handle both "usual true/false conditions" and "object lists" in a way that is (more or less) seamless. It usually works very well and is intuitive for 99% of cases. When you're using "advanced" conditions like OR though, it's usually confusing because the OR is dealing with object lists filtering. 

> As an additional note: it's a bit like when people ask to "please just add ELSE, it can't be difficult". [Turns out it is: people have two different vision of what should be the result when I take an example](https://forum.gdevelop-app.com/t/if-else-event-we-have-a-solution/21168/14). The best decision might be to never add ELSE - or to find another word rather than "ELSE". The reason is that "else" does not play naturally with filtering/mapping (`filter`, `map`) which are more functional programming concepts.

Maybe we should explain that in this page: http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/basic-game-making-concepts?
Or in another page about events?

Again I'm hoping maybe a more complete description of OR, or a slightly different naming, could help reduce the confusion?

**Comment by 4ian** [comment]
To summarize:

* If you're interested in the "else problem", read this (lengthy! 😬) post that is explaining the problem: https://forum.gdevelop-app.com/t/if-else-event-we-have-a-solution/21168/10?u=4ian
* If you have ideas about how to make OR clearer (description, wiki page, renaming, something else...), please let me know. Maybe we should rename it to "Launch these conditions, remember objects that are passing them and continue if at least one of the conditions is not false" but well that's long :D
* If you think OR should be working somehow different, let me know but please be sure to consider all the use cases possible.

**Comment by Bouh** [comment]
When I started GD I thought object. (unique)
Over time i puts several instances of the object on the scene and that's where the misunderstanding begins.
I'm sure that people who put several instances of the object still think as a single object.

Filtering is discovered when you understand that one instance of an object works, but multiple instances can work differently.

And these are two super important concepts. And I don't see it explained, or even mentioned in the software.
The wiki have a few words about instances and filtering, but very simple case.

For OR condition I think it can be given a long description. The sentences you have written are understandable.

> * _"If you talk to GDevelop about an object in the conditions, only the objects that matched the condition will be picked in the actions"_. (In my example, you "talked" about Object A and Object B to GDevelop. So GDevelop will only deleted the ones that fulfilled the conditions).
> * _If you talked to GDevelop about an object, but want to act on all objects_ (strange but can happen rarely), use "Pick all objects".

I am more and more hesitant to keep the example of Platformer for the Guideline.
Putting forward this kind of concept is important.

**Comment by Wend1go** [comment]
To be clear, I'm not saying that the filtering system we have now is bad. I just had to learn mostly via try and error until I understood how the filtering works.
A more detailed (or even a separate Wiki article) with some examples on the topic would have helped me back then.
I just don't know if I was the exception while everyone else understands the concept immediately. :grin:

**Comment by Bouh** [comment]
I close because it's not a problem coming from the engine.
The discussion can continue.
