### ISSUE TITLE
Expose more variables of PlatformerObject

### ISSUE THREAD

**Issue by Level0gamedev** [4ian/GDevelop#1357]
## Description
At this time PlatformerObject behavior is very "closed up" and separate from the rest of the engine. The changes the behavior does to an object are not accessible through Common Conditions of all Objects (e.g. Speed can't be compared). In fact, none of the current values for the object are accessible via events (only the variables for Options are). Some variables are being able to be read (onFloor, Jumping, etc.) but not changed by the user. This limits the PlatformerObject behavior considerably.
 
## Solution suggested
Allow the user to read/write following PlatformerObject variables (taken from platformerobjectruntimebehavior.js) via the editor:

- this._currentFallSpeed
- this._currentSpeed 
- this._currentJumpSpeed

- this._canGrabPlatforms
- this._canJump
- this._isOnFloor
- this._isOnLadder

## Alternatives considered
Current alternative to this problem is to either recreate a platformer engine with events OR using the Physics. 

Alternative solution is to connect the above values to events from Common Conditions of all Objects.

**Comment by 4ian** [comment]
There is indeed surely a few conditions/expression to add :)
Precisely, this is what is I think missing:

`this._currentFallSpeed` => getter method to add in JS + condition/expression
`this._currentSpeed` => getter method to add in JS + condition/expression
`this._currentJumpSpeed ` => getter method to add in JS + condition/expression
`this. _canGrabPlatforms ` => condition and action (getter in JS, and the setter `setCanGrabPlatforms` method is actually already coded)
`this._canJump ` => action already existing, getter in JS + condition to do.
`this._isOnLadder ` => getter in JS + condition.

Not all of these have actions because some are properties that describe a state, but can't be modified alone (or this would risk breaking the assumptions/internal state of the platformer) (like isOnFloor/isOnLadder).

**Comment by 4ian** [comment]
Closing as card created on Trello
