### ISSUE TITLE
Weird code in runtimeObject

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1368]
Ok, I am currently writing typescript definitions for the GDJS Engine, but there is a weird bit of code that I don't understand and makes typescript go insane. It's the len parameter in runtimescene.js in method separateObjectsWithForces (line 1289). Why is it here? it's being redeclared if undefined and then redefined again in the for loop. What is going on there?

**Comment by arthuro555** [comment]
Now I am even more confused as it says in the extension declaration that the second parameter is an object List, even if it looks like a pretty clear number in the GDJS implementation???? Anyways, this is deprecated and hidden, Is it a problem if I potentially break it by removing the weird argument from the GDJS implementation as it breaks TypeScript support?

**Comment by arthuro555** [comment]
Ohhhh or does the engine always pass the length of a list with it? still makes me confused about it's redeclaration tho.

**Comment by 4ian** [comment]
Don't panic :)

**Comment by 4ian** [comment]
1. So "len" is clearly suspicious here. Not used, overriden by something else. It seems like something that was forgotten. 
2. How can we be sure? Let's find the usage of this function
3. Search for "separateObjectsWithForces" in the whole codebase. 
![image](https://user-images.githubusercontent.com/1280130/72291886-33091580-3648-11ea-85eb-414e3cc187f2.png)

4. The only usage is in the BaseObjectExtension. Let's open it. We can see that it's linked to an action internally named "Rebondir" (so probably something that is 10 years old, because written in French :))
![image](https://user-images.githubusercontent.com/1280130/72291959-5b910f80-3648-11ea-8d9a-982e5d517121.png)

5.  That's only the binding of the action to the JS code though. Let's inspect the parameter of the action. For this, search "Rebondir" in the codebase:
![image](https://user-images.githubusercontent.com/1280130/72292007-78c5de00-3648-11ea-9c8b-9650e873ea6b.png)

  A few usages in some games (so if we want to remove it comptely, we would need to update these examples - and also make sure the very very large majority of GDevelop games are not using it, which is harder to prove). We can find the declaration of "Rebondir" in `BaseExtensionObject.cpp` in `Core`:

  ![image](https://user-images.githubusercontent.com/1280130/72292128-b0cd2100-3648-11ea-93e5-ca0941537b37.png)

  What do we see? It's an object action (so translated to an object method, make sense and we can see that the first parameter is an object, it's a convention). The second parameter (which is the first when translated to JavaScript) is an "objectList" (i.e: a hashtable of objects in JS). No third parameter (so no second parameter in JS!)

Conclusion: it's a left over that is safe to remove :) 

You can still add a comment and ping me in the source file or in your commit to say "hey i'm 99% sure this is useless". Though if you create a PR soon enough, I should be able to review it anyway.

**Comment by arthuro555** [comment]
Ok, that was one of my 2 guesses, Thanks for clearing me up! (I was really scared this was my other guess, an old required restover and it would be required to edit the cpp core to change that 😌 )

**Comment by 4ian** [comment]
Closing as "solved" :)
