### ISSUE TITLE
[Minor UX issue] Animation editor checkbox for selecting frames blends into transparent background

### ISSUE THREAD

**Issue by kryptot7** [4ian/GDevelop#1412]
## Describe the bug
In the animation editor, the checkbox for selecting frames blends into the checkerboard pattern that shows up if the frame has a transparent background.
![image](https://user-images.githubusercontent.com/30781325/73881879-2636a680-482f-11ea-8abe-c5dc53bba2e6.png)
(Checked)
![image](https://user-images.githubusercontent.com/30781325/73881895-2fc00e80-482f-11ea-9166-962958f2b8e9.png)

## To Reproduce
1. Create a Sprite object.
2. Open the animation editor.
3. Edit its animation in Piskel.
4. Save.
5. See issue.

## Other details
* Windows 10 1909 x64
* GDevelop 5 beta 88

Also, it could be made more clear what you can do with selected frames. Currently, it seems you have to right-click them to find out:
![image](https://user-images.githubusercontent.com/30781325/73882330-d86e6e00-482f-11ea-9628-25bc43e02851.png)

Perhaps a couple buttons that say "Duplicate" and "Delete" could pop up in the top-left of this area (aligned with "Edit with Piskel", etc.) to make it clear what you can do with the selection.
Of course, this is a pretty minor issue, and everything seems to work regardless. There are bigger fish to fry!

**Comment by Silver-Streak** [comment]
I'm going through older issues to bring attention to them if they can be resolved, or close out the ones that already are.

Happily, it seems this was resolved at some point since B88.

![image](https://user-images.githubusercontent.com/24237149/126906210-a05c470e-1687-4044-aee4-d0380c9c6179.png)
![image](https://user-images.githubusercontent.com/24237149/126906238-04dcd4b7-107b-44ee-b466-a9298da54ba2.png)
![image](https://user-images.githubusercontent.com/24237149/126906251-7c18e67e-8772-4e28-bb1a-33622bb3a3e9.png)

If you're still experiencing this with B113 or newer, please feel free to reopen this issue with what theme you are using and a screenshot.
