### ISSUE TITLE
Custom Fonts at large font size being rendered in IDE with Default Font Render Box/Wrong Location

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#1419]
## Describe the bug
When using Custom Fonts, if you select a large font size, the font's position and boundry box do not accurately represent the font size.

I originally discussed this on the forum, but now that I can reproduce it in other projects I thought it made sense to put it here: https://forum.gdevelop-app.com/t/text-object-boundry-box-not-matching-font-in-editor/22636/2

## To Reproduce
1. Create any new project, or load an existing one.
2. Create a Text Object.
3. Set font size to a large size, like 40.
4. Load a custom font such as Silver: https://poppyworks.itch.io/silver
5. Place it in the scene.
6. Load the preview, and the fonts will have moved. The Preview is much more accurate to the font's actual location than the IDE.
7. Another way to see this is to place a sprite object roughly the same size, and put it at the x/y coordinates of the font. You'll see in the IDE that the sprite is way higher than the font, but in the preview they're aligned.
8. You can also just remove the custom font from the objects, and you'll notice the font boundry box stays the same for the default font.
9. You can also reduce the font to a smaller size (like 30) and the boundry box will shrink to what it should be.

Screenshot from Editor: 
![image](https://user-images.githubusercontent.com/24237149/73996967-ce796780-4922-11ea-81df-38aaca0e01ef.png)

Screenshot from Game: 
![image](https://user-images.githubusercontent.com/24237149/73996975-d6390c00-4922-11ea-98a5-9916fbb37758.png)

Screenshot showing incorrect boundry box for custom font at size 40: 
![image](https://user-images.githubusercontent.com/24237149/73997280-a2121b00-4923-11ea-99b3-7202bb1b12b9.png)

Screenshot showing boundry box height on custom font matching standard font at size 40:
![image](https://user-images.githubusercontent.com/24237149/73997370-e7cee380-4923-11ea-86e3-713dad948760.png)

Screenshot showing correct boundry box for custom font at size 30.
![image](https://user-images.githubusercontent.com/24237149/73997302-ad654680-4923-11ea-82f1-e663a0fc84e1.png)

Example Project: 
[FontIssueExample.zip](https://github.com/4ian/GDevelop/files/4168774/FontIssueExample.zip)

## Other details
OS: Windows 10 Pro 10.0.18362 Build 18362
GDevelop 5 version 5.0.0-beta88. Desktop app.

Two more screenshots showing how this badly messes up layouts in the IDE:
Nothing seems aligned in IDE: 
![image](https://user-images.githubusercontent.com/24237149/73997482-3da38b80-4924-11ea-9f33-8aed6be9957e.png)

Everything aligned in preview:
![image](https://user-images.githubusercontent.com/24237149/73997510-52801f00-4924-11ea-92b9-56ea2a07d5c3.png)

**Comment by Bouh** [comment]
I was able to reproduce the bug with this font.
I looked a little bit into the code.  I can't find anything that seems unusual.
I've tested other fonts and I don't have this bug.

Could it be a parameter of the font? Maybe ask the font author if a variable font height can exist as a parameter in a font.
Or if there is question of pixel ratio or ppp resolution ?

**Comment by Silver-Streak** [comment]
Hmmm..I'm able to reproduce this with a bunch of other fonts too.

Here's another one: https://tinyworlds.itch.io/free-pixel-font-thaleah

Size 20 boundry box: 
![image](https://user-images.githubusercontent.com/24237149/74188373-e51a0a00-4c13-11ea-848a-2596cfde9eb8.png)
From the top of the T to the border of the boundry box, the boundry box is ~37% the height of the T character.

Size 40 boundry box:
![image](https://user-images.githubusercontent.com/24237149/74188396-f105cc00-4c13-11ea-9289-067b85169495.png)
From the top of the T to the border of the boundry box, the boundry box is ~92% the height of the T character.

**Comment by Silver-Streak** [comment]
As another example, both the default font and the custom font at size 40. Both boundry boxes align perfectly in size.

![image](https://user-images.githubusercontent.com/24237149/74188819-da13a980-4c14-11ea-8be1-41a593b173ba.png)

**Comment by Silver-Streak** [comment]
For other oddities, BBText objects _are not_ impacted by this.

Here is a normal text object and a BBtext object, both using the same custom font, both set to size 40. 
![image](https://user-images.githubusercontent.com/24237149/74189081-658d3a80-4c15-11ea-83bb-d92f92c9c095.png)

**Comment by Bouh** [comment]
If there is no problem on BBtext i will compare both for try catch the differences.

**Comment by Bouh** [comment]
Possible issue with the font loader ? 
This one is used : https://github.com/bramstein/fontfaceobserver

Cyan rectangle are the bounding box with created it events.
![image](https://user-images.githubusercontent.com/1670670/74195021-af4c4400-4c5a-11ea-9e0b-f5289e4a5bff.png)
Project file : [font_comparator.zip](https://github.com/4ian/GDevelop/files/4183303/font_comparator.zip)

**Comment by Bouh** [comment]
Two more case on forum, with BBtext and without.[ link 1](https://forum.gdevelop-app.com/t/bbtext-line-height/23240/7), [link 2](https://forum.gdevelop-app.com/t/bbtext-word-problem/23245)

BBtext come from [this repo?](https://github.com/tleunen/pixi-multistyle-text/issues)
If yes there is an issue on the repo maybe related to this bug.

I think lineHeight is missing or undefined in pixi 4.8.6, or the value by default should be the value living in the font file, what you think?

It's cool the issue seem global, and not just on GDevelop, in this case digging forums can help, we need research and more comments for understand.

**Comment by blurymind** [comment]
Bbtext just wraps pixi-multistyle-text which uses the standard text styling
in pixi :)

**Comment by 4ian** [comment]
So this is:
- both on BBText and the normal text object right?
- different in preview and in the scene editor?

Do we know which one, the preview or the scene editor, is right?

Looks like a potential different font loading. Pixi renders the texts on a canvas before copying it into the game canvas => if the browser loads the font differently, it will be rendered differently.

**Comment by Silver-Streak** [comment]
@4ian 
- both on BBText and the normal text object right?
  - Correct, both.
- different in preview and in the scene editor?
  - Correct, the editor displays text boundary box height ad positioning way different than the actual Y position or height.
- Do we know which one, the preview or the scene editor, is right?
 - Preview shows the objects at the correct Y position.

**Comment by Phenomena3** [comment]
I think Silver-Streak's issue is similar to mine and the other report on the forum, but I don't know that it's exactly the same. In the first screenshot below, the boundary box for left click overlapping right click can be ignored. It's expected in my case due to the longer sentences on the left and side-by-side layout. 

The main issue on my end is that multiple lines of text are overlapping within the same box. It is more noticeable in the preview and export, which looks different from both preview & scene editor depending on the browser. Here's [a direct link to my app](http://pluckygames.com/apps/mirrors/) for comparison in Chrome and Firefox:

- Click Studio
- Click the question mark icon at the bottom

It's also worth noting that all of the hints in my app are a regular text object; some of the hints have multiple lines and they are not being squished in either version on export, preview, or the scene editor. They're also all the same font, which is [Bubblegum Sans](https://fonts.google.com/specimen/Bubblegum+Sans).

## Screenshots 
### In version 89

![editor_v89](https://user-images.githubusercontent.com/45985516/76342543-27973b00-62d5-11ea-8cc9-ab8c16680599.png)

![previewsquish_v89](https://user-images.githubusercontent.com/45985516/76342565-2fef7600-62d5-11ea-99e8-566d9e229dcc.png)

### In version 88

![sceneeditor_v88](https://user-images.githubusercontent.com/45985516/76342763-7d6be300-62d5-11ea-9c54-a71535daa44d.png)

![preview_v88](https://user-images.githubusercontent.com/45985516/76342803-89f03b80-62d5-11ea-97a1-c736ec4142c1.png)

> both on BBText and the normal text object right?
It seems to be only BBText over here

> different in preview and in the scene editor?
Yes, and on HTML5 export there are differences between browsers

> Do we know which one, the preview or the scene editor, is right?
I'd think the scene editor would be right in terms of design intent and that ideally previews/exports should be as close as possible to our settings in the editor, but perhaps I'm not properly understanding this question :\

**Comment by 4ian** [comment]
Interesting, not sure if this is the same issue. Yours seems like a regression as it was working in beta 88.
While @Silver-Streak reported issue on version 88 and indicates that the preview is the right one. 

Might be worth opening a new issue with a simple game showing the text with your font and showing immediately the issue. This way we can verify that v88 worked, v89 not, and find the difference.
(If it turns out to be the same issue, we'll close one)

**Comment by Phenomena3** [comment]
I'll reopen a new issue with simple projects attached within the next few days. 
They won't be games, just text examples.

**Comment by 4ian** [comment]
Thanks! :)

**Comment by Silver-Streak** [comment]
![image](https://user-images.githubusercontent.com/24237149/216802038-2576cbeb-b447-43a0-a99d-ad8f4a104082.png)
I actually never heard that this issue was worked on, but from loading up Bouh's project it definitely seems solved to me (although bitmap texts fixed this mostly anyway)
