### ISSUE TITLE
Flappy bird 

### ISSUE THREAD

**Issue by THE-GEM-TUTORIALS** [4ian/GDevelop#1426]
Hi!

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **INSERT the link to your game here, or add it as an attachment**.
https://www.mediafire.com/file/z6omui2ce6z40ni/My_project473.zip/file

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by THE-GEM-TUTORIALS** [comment]
@4ian checkout this example i really think it would be good for gdevelop

**Comment by 4ian** [comment]
Nice! That would be a good example :) Could we do these improvements?

* Merge the first and last events (conditions are the same):
![image](https://user-images.githubusercontent.com/1280130/74475631-b2844180-4e9f-11ea-9665-b475dabbd81d.png)
* Allow to use space on desktop
* Add some sounds (when you're hitting an obstacle, when you "jump" in the air?)
* This transition is too abrupt:
  ![image](https://user-images.githubusercontent.com/1280130/74475746-e9f2ee00-4e9f-11ea-988a-9b8abf94a3d7.png)
  Instead, let's make the bird fall and then display the game over.
* The game is a bit slow compared to: https://flappybird.io/ - it must feel faster to move the bird.
* Buttons must be centered in the window:  
  ![image](https://user-images.githubusercontent.com/1280130/74475879-32121080-4ea0-11ea-9716-181fc4ffacf3.png)

It's a very good start :) Let's try to make something as fun as the original one :)

**Comment by THE-GEM-TUTORIALS** [comment]
yes i will work on that now
thanks for the improvement suggestion

**Comment by 4ian** [comment]
Thank you! 👍

**Comment by THE-GEM-TUTORIALS** [comment]
i am changing the assets used to make it more like the flappy bird game

**Comment by THE-GEM-TUTORIALS** [comment]
hello Florian i just wanted to give you an update on the flappy bird game
 flappy.png
<https://drive.google.com/file/d/1S-fP-kU9mMcleUsV0IdXJ6MirndjBcWK/view?usp=drive_web>

**Comment by 4ian** [comment]
You can't include images from emails, please use GitHub to attach your image and files :) (do it too rather than hosting things on website like mediafire that are full of ads)

**Comment by THE-GEM-TUTORIALS** [comment]
thanks for the advice well i have completed the flappy bird example and would like you to check it out and let me know your suggestions and also what should be written as the explanation for each event.
[Flappy bird.zip](https://github.com/4ian/GDevelop/files/4216009/Flappy.bird.zip)

**Comment by 4ian** [comment]
Wow this is great improvements! 🤩 Looks awesome and is really close to the original gameplay. Well done!

A few comments, but overall this looks great :)

* Prefer using `TimeDelta()` (see the end of http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/basic-game-making-concepts) for this:
  ![image](https://user-images.githubusercontent.com/1280130/74685383-50d91580-51c6-11ea-859a-f9c090dfe81d.png)
* Sine_movement is not an ideal name for this variable, prefer naming it something like "Gameplay_started"
![image](https://user-images.githubusercontent.com/1280130/74685448-841ba480-51c6-11ea-9994-fb5822af63a4.png)

* Do this only at the beginning of the scene:
![image](https://user-images.githubusercontent.com/1280130/74685547-c644e600-51c6-11ea-8e69-15e13d9ce39a.png)
* You should delete Pipe when they go out of the screen (otherwise the game will slow down)
* The game width should not be adapted when the game window is resized (check the game properties):
  ![image](https://user-images.githubusercontent.com/1280130/74685730-45d2b500-51c7-11ea-9708-37533d727a26.png)
* Let's remove the empty comments. No need to separate the events, this is taking space for nothing. Just add an explanation if an event is complicated or has some special thing you want to highlight.
* Prefer to use `LinearMovement` behavior rather than SineMovement for the game over panel/texts :)
* Speaking of the panel, it's a bit small no? 
  ![image](https://user-images.githubusercontent.com/1280130/74685870-b679d180-51c7-11ea-9e92-869cb91977e3.png)
  A bit hard to read what's written inside :) There should be something to do to make it larger, or appear larger on screen.

Apart from that, again great job. It's much better and polished 👍👍 :)

**Comment by THE-GEM-TUTORIALS** [comment]
thanks i will work on that and get back to you

**Comment by 4ian** [comment]
Great, let me know when you have an updated version and I will add it to examples :)

**Comment by THE-GEM-TUTORIALS** [comment]
hello i took some of your advice and added it to the game and it looks much better. But i left some out because they don't work the way they are suppose to after the change while for others i felt they wont be the best of events if added. I also added an event to notify the player once he or she has a new Highscore. Please let me know if it's ready or would need some more adjustment and also please go through all the comments and let me know if you think it should be edited.
[Flappybirdgame.zip](https://github.com/4ian/GDevelop/files/4226870/Flappybirdgame.zip)

**Comment by THE-GEM-TUTORIALS** [comment]
Also could i make a tweet telling everyone about this example coming to GDevelop on twitter

**Comment by 4ian** [comment]
Added for next version and to the web-app: https://editor.gdevelop-app.com/?project=example://flappy-bird :)

Thanks a lot for your work on this, the example looks really nice!
Feel free to tweet about it for sure 👍

**Comment by THE-GEM-TUTORIALS** [comment]
Thanks alot, I can't wait for the next version
