### ISSUE TITLE
Group/Comment text input is hard to exit

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1430]
When I edit the text of comments and groups, the textbox is as wide as the item itself, making it hard to exit text input.
Ideally, the textbox would be limited to the actual text, whether text input is enabled or not. 
![image](https://user-images.githubusercontent.com/25978830/74527061-100ea180-4f25-11ea-9b1b-a165215a2810.png)
Example: I left-click on a group, text input activates and I enter the text I want. Now let's say that I want to copy-paste the item: I try to disable text input by pressing return (not working), by clicking right below the text (not working), by clicking on the right side of the text (not working), further to the right (still not working), by [right-clicking](https://github.com/4ian/GDevelop/issues/1423) (not working), and only then, I either click on the left-side handle, or click on an event below/above, and it works. 
I find it quite inconvenient/unnatural.

And it's even more frustrating when you didn't mean to activate text input, i.e. I left-click on the group item to select it, and text input activates.

**Comment by geetesh-gupta** [comment]
Hi @PascalLadalle Please confirm is the issue same as shown in this [https://gofile.io/?c=0WFBPW](video) . I am facing the issue while renaming an object. Until I change the current name, the field doesn't exit as shown in the video. If the issue is same, I would like to continue on this thread, otherwise create a new issue and work on the solution to the problem if @4ian agrees.

**Comment by PascalLadalle** [comment]
Hi @geetesh-gupta 
My problem is in the Events tab, not in the Scene tab like yours. 
It's only related to the **Group** items and the **Comment** items.

**Comment by geetesh-gupta** [comment]
Okay, @PascalLadalle I will try to have a look into it.

**Comment by geetesh-gupta** [comment]
I was thinking of possible solutions to the problem. Consider the following solutions:

1. On pressing enter, endEditing. --- Works perfectly for **Group** items because they are single line fields but for **Comment** items, this cannot be used.
2. Have text field width of **95%**, to allow 5% of right side area empty so that when clicked, it will endEditing   ---- these percentages are just tentative
3. Have special button at the right hand side to confirm endEditing.

Which of the above @4ian @PascalLadalle think is most appropriate?
 
One more update, I have changed calling edit event onClick to onDoubleClick to allow editing only when a user intentionally double clicks to edit.

**Comment by PascalLadalle** [comment]
I'm not a dev, but I'll give you my opinion from a user point of view.
For number one, maybe Esc key can be used to exit input?
For number two, I think text field width should be text.Width()+10%. Don't know if that is feasible.
For number three, right-hand side is very far away on a large screen, not ideal at all.

Usually, double-click is for _opening_, so in the case of comments, triggering the editing is good, but in the case of groups, I think it would be more logical if it would expand/shrink the group (same result as clicking on the arrow on the left side). 
If it's technically possible, maybe double-clicking on the text itself would trigger editing while double-clicking on the group bar outside of the text would expand the group.
Another possibility to maintain logic while keeping a similar result would be that double-clicking group or comments _open_ the Edit menu (right-click/edit).

**Comment by 4ian** [comment]
Double clicking should in general trigger the "main" action on the item, which is often the equivalent of the right-click > edit menu item. It should not trigger a renaming I would say.

The editing of a name should be ended by either:
- pressing enter (but as you mentioned this is not possible for comments that are multiline... or we consider that you have to press Shift+Enter to either add a new line or close the edition)
- clicking anywhere outside.

A button at the right hand side could work but the idea is that the text of a comment/group should stay the same when you're editing it or not - I'm afraid a button could move things.

Another solution is as you mentioned adding some padding around the text... this being said it's not super complicated to click on another event already, right? Might be just a matter of handling it with the keyboard (enter and/or shift+enter, to decide).

**Comment by geetesh-gupta** [comment]
@4ian Please have a look at the PR and give your reviews.

**Comment by 4ian** [comment]
See if you can answer to Bouh on the PR first :) Thanks!
