### ISSUE TITLE
Error in Flip horizontally

### ISSUE THREAD

**Issue by Foolius** [4ian/GDevelop#146]
I have a german version and followed the platformer tutorial.
but at flip horizontally, the game automatically filled in "Ja" german for yes, but this does not work. it has to be "yes" in lower case. the same for "Nein", "no".
I didn't check this for other actions.

**Comment by victorlevasseur** [comment]
Yes, the software only supports "yes", "no", "oui", "non" (the french of yes and no). However, this needs to be fixed in the translation.

**Comment by 4ian** [comment]
This IDE should make sure that only yes/no can be selected and translate it accordingly to the user language (even if if internally using yes/no instead of the translation). For the condition/action window, it's easy to use. For events editor, the `yesorno` and `trueorfalse` parameters types should be translated when rendered.
