### ISSUE TITLE
Overlapping highlighted objectList item

### ISSUE THREAD

**Issue by geetesh-gupta** [4ian/GDevelop#1478]
## Describe the Bug
A UI issue, whenever a field is selected for renaming, its highlighted box overlaps with the object box below it. It can be seen in the screenshot.  
![overlapping](https://user-images.githubusercontent.com/34645022/75573038-07b87980-5a82-11ea-8356-ab54d266a1c3.png)

## Fix 
Remove top padding when highlighted. 

## To Reproduce
1. Go to 'a new project'
2. Right Click on any object name
3. Click on rename option

**Comment by jimil749** [comment]
I did see the issue, maybe we could something like: whenever user selects rename, the entire text should be selected rather than putting the cursor add the end of the word. 
Just a suggestion!  :)

**Comment by geetesh-gupta** [comment]
I think the issue is due to a styling class being added on focus. I have found out that Mui-focusVisible is added as a class when rename option is selected for an object. I have tried providing padding 0 using chrome inspector, it is working (check the screenshots).

When rename is not selected:
![without_rename_selected](https://user-images.githubusercontent.com/34645022/75579146-2cfdb580-5a8b-11ea-8b04-989d4d8a8ea2.png)

When rename is selected:
![with_rename_selected](https://user-images.githubusercontent.com/34645022/75579141-2a02c500-5a8b-11ea-8d9b-ea54cdb87801.png)

When rename is selected and padding top and bottom set to be zero:
![with_rename_selected_padding_zero](https://user-images.githubusercontent.com/34645022/75579145-2bcc8880-5a8b-11ea-94ae-d805d870532d.png)


But, I am currently unable to figure out, how to override its style. @4ian Kindly guide here.

**Comment by 4ian** [comment]
This is not critical but would be a welcome fix. I'll let you investigate in React components - this is typical search in React components and I would prefer not to have to guide people here.

**Comment by bajaj99prashant** [comment]
@4ian, I am working on this issue.

**Comment by jimil749** [comment]
There might be a roadblock here. The API for the component library (MUI Component) does not have a padding prop.
https://material-ui.com/api/text-field/ 

If you checkout the docs, the only way to overwrite is through an external css file. So, there might be a problem providing padding to the component!

**Comment by 4ian** [comment]
Are we sure padding is the solution? You can always pass it with a `style` prop.

**Comment by bajaj99prashant** [comment]
The issue is the height of the list-item in the object list is fixed to 40px when the renaming of the object takes place the border-bottom of text-field appears which changes the height of the selected list-item by 2px approx. The approach which i found to solve the issue is decreasing the height of text-field and decreasing the bottom padding in the text-filed.

**Comment by bajaj99prashant** [comment]
We can also decrease the height of the text field component while renaming the object item, the issue is maybe due to the fixed height of items in the object list.

**Comment by bajaj99prashant** [comment]
@4ian, I have fixed the overlapping of list items by adjusting the height of the MUITextField component in TextField.js.

![Screenshot from 2020-03-04 09-38-42](https://user-images.githubusercontent.com/42171435/75844666-ba7b3580-5dfc-11ea-8ab3-23b00eeb6e19.png)

**Comment by 4ian** [comment]
Well, look at the position of the text field, is looks not centered at all. Ideally it should match the position of the existing text - so that the text seamlessly change to a text field and vice versa from the user point of view.

**Comment by bajaj99prashant** [comment]
Centered the position of the text field, checked it for both web and mobile view.

Web view
![Screenshot from 2020-03-05 03-44-19](https://user-images.githubusercontent.com/42171435/75928419-5dcb5980-5e94-11ea-9593-d9d396a708dd.png)

Mobile View
![Screenshot from 2020-03-05 03-44-45](https://user-images.githubusercontent.com/42171435/75928432-63c13a80-5e94-11ea-8c86-a7129b4785d8.png)

**Comment by 4ian** [comment]
That looks better, at least on these screenshots :) 👍

**Comment by bajaj99prashant** [comment]
Is there any test, any sort of measure or improvement I need to take care of before creating a pull request as I am trying to contribute for the first time.

**Comment by 4ian** [comment]
Be sure to look at [the README](https://github.com/4ian/GDevelop/tree/master/newIDE) how to run:
- Autoformatting
- "Flow" static typing tests
- The tests for the app

Almost most importantly, do test your changes on multiple devices and screen ratios (a bit like you did), different browsers if possible. Check that it's rendering properly in the electron app (see also the README how to run it) - as it's used by the vast majority of users :) 

The idea is just to be sure that there is no obvious regression (check that you can still renaming an object ;)). If changes are just "cosmetic", risk is low, but you never know!

Do these before creating a PR. Then you can create a PR with your branch so that we can take a look at your implementation.

**Comment by bajaj99prashant** [comment]
Ran Autoformatting, Flow typing tests, and Tests for the app, checked it on Google Chrome and in Firefox for both web and mobile view, checked it on the electron app.

**Comment by 4ian** [comment]
Feel free to open a PR then! :)

**Comment by AlexandreSi** [comment]
I think this is not an issue anymore, feel free to reopen it if needed!
