### ISSUE TITLE
BBText line height

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1521]
## Describe the bug

Multiple lines of text merge together on preview when using BBText objects as shown in the attached screenshots. HTML5 exports are also affected in different browsers. 

_Please double check that the bug is not already reported in the issues list._

Was advised [here](https://github.com/4ian/GDevelop/issues/1419#issuecomment-597340328) to open a new issue.

## To Reproduce
1. Create a BBText object and choose custom font
2. Add more than one line of text
3. Preview

* Please include a link to a game if possible! 

My existing app showing the problem within two clicks is [here](https://www.pluckygames.com/apps/mirrors). 
1. Click Studio
2. Click the question mark icon to open a brief help layer

The latest updates were made with version 89 and the issue is more obvious in Firefox. 

Example projects with the same font and both text types are included below. 

* If applicable, add screenshots to help explain your problem. 

## Version 88
![gdv88textsceneeditor](https://user-images.githubusercontent.com/45985516/76484998-9669b680-63f1-11ea-8720-2977a8bc6e92.png)

![gdv88textpreview](https://user-images.githubusercontent.com/45985516/76485006-9d90c480-63f1-11ea-8acb-2ad8c6d03609.png)

## Version 89
![gdv89textsceneeditor](https://user-images.githubusercontent.com/45985516/76485015-a4b7d280-63f1-11ea-908d-d9b742b85d75.png)

![gdv89textpreview](https://user-images.githubusercontent.com/45985516/76485022-aaadb380-63f1-11ea-90b7-11139771cfee.png)

# The example projects

They are exactly same except one was saved in V88 and the other V89.
[v88text.zip](https://github.com/4ian/GDevelop/files/4322168/v88text.zip)
[v89text.zip](https://github.com/4ian/GDevelop/files/4322169/v89text.zip)

## Other details

* Include any OS/browser version/smartphone that you're using

Windows 8.1, Laptop

* Which version of GDevelop are you using? The desktop app or the web-app?

See above and desktop app.

* Add any other context about the problem here.

This doesn't appear to be a problem with the default Arial font.

**Comment by blurymind** [comment]
I think @Bouh added a better selector for the custom fonts in BBtext, but it could also be something else that caused a regression

**Comment by 4ian** [comment]
Would be a good idea to investigate changes made in the BBText object - not sure what it could be linked to.

**Comment by Bouh** [comment]
My previous PR for add font on BBtext is here https://github.com/4ian/GDevelop/pull/1394

I use only the resource loader and set the fontFamily, but instead write the name manually in BBtext propertie panel, now the resource loader provide the name.

So if we have a bug, the bug is in the resource loader.
Because font is loaded differently when we load with the resource loader?
What is used when we have no resource loader, who load the font?

**Comment by Phenomena3** [comment]
Any news on this issue?

**Comment by KinkGD** [comment]
up! Facing the issue too, beta92.

**Comment by convictedweirdo** [comment]
Unfortunately, this issue still persists in beta95. 

![image](https://user-images.githubusercontent.com/25803863/83512244-45122480-a513-11ea-8179-a41975e301fa.png)

**Comment by Bouh** [comment]
https://github.com/4ian/GDevelop/pull/1628#issuecomment-643831545

**Comment by 4ian** [comment]
Let's try to find a solution to this issue, it's a bummer and makes the BB text hard to use: https://forum.gdevelop-app.com/t/need-tester-gdevelop-5-branch-pixi-v5/24819/36

I think it's a font issue, because even the default font is not the same as the one rendered in the scene editor. Also if it's correctly rendered in the scene editor, no reason we can't fix this in the game engine :)

**Comment by convictedweirdo** [comment]
Something odd I noticed, is that the default Arial font works as intended when there is only one bbtext object in the scene. The Arial renders differently once a second bbtext object is added.

**Comment by 4ian** [comment]
Definitely something weird/wrong in the way the fonts are handled.. I wonder if the issue is that the font used by the BB Text is not properly exposed to the editor, which is not loading it at the game startup, so it's loaded "on demand" when the object is created... at which point, because the font is not loaded yet in memory, the BB text use another font to do the line height calculations.

**Comment by 4ian** [comment]
I finally found the issue :)

**Comment by 4ian** [comment]
FYI the reason behind this was the CSS "font family" name generated was having a dot (as it was named after the filename) and this was causing issue with BB Text/Pixi text rendering. This was not the case in the editor where the font family name were pre-processed to eliminate any non alphanumeric character and spaces. This is now also done in the game engine :)
