### ISSUE TITLE
Object with numeric values in start of name are unusable

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1557]
## Describe the bug
When a object contain a number at start like `1PlayerHitBox`.
This object isn't works in preview.

## To Reproduce
1. Open platformer example
2. Rename `PlayerHitBox `to `1PlayerHitBox`
3. Run the preview you can't move

And worse, i we go back to initial name `PlayerHitBox` and re run the preview, the game have still the issue.

## Other details
* beta 89

**Comment by geetesh-gupta** [comment]
One solution can be to restrict the names to start with alphabets i.e. have the object names follow the same syntactic rules as other variables names in general for any programming language. It will make the naming consistent with general guidelines. This way the problem will be solved as well as proper naming specification will be followed. What are your opinions? 🤔

**Comment by 4ian** [comment]
The rules are:
1. Only alphanumeric characters (a-z, A-Z, 0-9) and underscores
2. Do not start with a numeric character (0-9).

The second rule is because otherwise when parsing expression, we can't make the difference between a number (123) and an object name (123) (we say that the grammar is "ambiguous").

Actually, there is no technical restrictions for rule 1 apart from not to use what are considered as operator, separators or whitespace(-, +, /, *, =, {,},[,],",';,:,. etc ...) by the expression parser.

We could imagine allowing any unicode character that is not an operator, separators, whitespace or number. This would allow to enter characters used in other languages than English (accentuated characters, Chinese/Korean, cyrillic... well everything supported by Unicode :)).

For now to be simple, I decided to just accept names that are valid in JavaScript.
You can see in the IDE that we use `gd.Project.validateObjetName`. And you can see the implementation here: 

https://github.com/4ian/GDevelop/blob/3ff5dd7cd2c1f6b2bfd57b2ef79b65d1e47ab15a/Core/GDCore/Project/Project.cpp#L948-L958

Turns out that I forgot to implement the second rule :) Should be not too hard to add, a bit of C++ and GDevelop.js work (see the README in GDevelop.js)

**Comment by PawBud** [comment]
I think that this issue should be closed right @Bouh @4ian?

**Comment by Bouh** [comment]
Yes, just i've no right for close it :)
In general lastest issues fixed are pass in review and closed just before the next release and writing of patch note.
