### ISSUE TITLE
Text cursor not at the end of the value in case of num input

### ISSUE THREAD

**Issue by geetesh-gupta** [4ian/GDevelop#1559]
# Describe the bug
When a num type input is selected to change, the default cursor goes to the starting of the variable but I think it should be consistent with other type of data for example strings, where it goes to the end by default. 

# How to Reproduce
1. Open any project
2. Try to change a num value
3. See error as given below

String type input
![image](https://user-images.githubusercontent.com/34645022/77161466-bd01ae80-6acf-11ea-9f61-cff1a95b3881.png)

Num type input
![image](https://user-images.githubusercontent.com/34645022/77161422-a6f3ee00-6acf-11ea-872c-d0a47f9eeb76.png)

**Comment by 4ian** [comment]
For this kind of "bug", I would prefer an investigation about what is the right behavior and a suggestion of a solution - I'm afraid of "noise" about having too much issues with an impact that is very low. 
Basically, how many users have been affected by this? How many complained? What is the time wasted? => If it's not huge, I would prefer for you to come up with a suggestion "let's do this on [X/Y/Z components] because [reason].".

Don't get me wrong, polishing the software is *super* important. But for very specific things like this that possibly have a low impact, better open a PR directly or a very descriptive issue with the components to change :)

**Comment by geetesh-gupta** [comment]
Ok. I will remember this in future :) Continuing on this, for future, for this type of issue where it sort of includes discussion, what should be the approach. Should I directly find a workaround and create a PR or create an issue with what can be done or create a post on the forum? 

And talking about this issue, I sort of added it because I found it non-consistent in terms of normal workflow because we generally try to modify from the end. I can't say about how many people consider this as a bug. But, I think consistency should be there.

Sorry for posting this without following a proper channel. I will try to follow proper ways in future.

**Comment by PawBud** [comment]
Yup I think a direct PR is the way to go @geetesh-gupta
