### ISSUE TITLE
remove splash screen limitation

### ISSUE THREAD

**Issue by renomagame** [4ian/GDevelop#1567]
people who dont have money or credit card shouldnt have to pay to remove splash screen limitation instead you should for ask donation including subscription is the same as any other game builder so you are basically saying if this thing is free you are the product.

**Comment by 4ian** [comment]
Servers that are running to host GDevelop website, to make games for Android/Windows/macOS/Linux, etc... are not free. They are costing me money, every month, for you. 
That's a choice that I have made to incentivise people to get subscriptions to help to contribute to the payment of these servers. Without them, I'll start to lose money for you every month, and I'll stop working on GDevelop and abandon it.

Instead, I'm asking people that can contribute to the software by giving a small amount of money. The *only feature* that is blocked is the splash screen, because I consider that if you can't or don't want to give a few bucks per month, then you can a least show the splash screen of GDevelop.

Remember that me and contributors are *spending dozens of hours* per week on this project. *For free*. I could make a startup, make the software a paid software and sell it for hundreds of dollars a year :) But I decided to try to make it open-source and find an alternate way of sustaining it.

I understand that if you're young or in a bad financial situation, you may not be able to pay. Still, the only thing I'm asking you is to show a splash screen! That's not an horrible thing to do :)  

> you should for ask donation

I tried in the past. I get so little donations that I was losing money. This is unfortunately not a working business model.

> basically saying if this thing is free you are the product

This is not true at all :) We're not showing any ads in the product or on the website. We're not stealing any data. We're not selling any data from users. I'm not try to get you to pay for some service stealing your data. 

I'm happy to answer more about this but please do on the forum. Here, this is a space for technical discussion only.

I hope you understand.
