### ISSUE TITLE
Dropdown menu in the 'Change editor zoom' menu

### ISSUE THREAD

**Issue by ner-aim** [4ian/GDevelop#1580]
(I don't know if this is only for me)
The drop-down menu in the 'Change editor zoom' has zoom in and zoom out which is completely fine. Although, its unclear why 'Ctrl + -' exists as an option to zoom out when it clearly doesn't support to zoom out on pressing the shortcut. It's intuitive to use the scroll wheel if you have a mouse but I use a laptop and sometimes end up using 'Ctrl + +' and 'Ctrl + -'.  
Although if it does support to use the shortcuts, my question is why there isn't a 'Ctrl + +' text beside zoom in.

1. Go to 'GDevelop 5'
2. Click on 'Create a New Project' and click on any of your choices.
3. Open the Change editor zoom icon (shown as a magnifying glass with 1:1 text)

![Screenshot (182)](https://user-images.githubusercontent.com/40934305/77252590-ced38500-6c7a-11ea-87f0-cbedb161c9a3.png)

* Found on a Windows 10 system
* GDevelop 5 desktop app

**Comment by xAtishayx** [comment]
@4ian 
I'm not able to understand why "Ctrl++" is not displaying here
![image](https://user-images.githubusercontent.com/42544589/77325876-f4c25d80-6d3e-11ea-8d7d-b05f7d169901.png)

I have gone through the codebase (newIDE/app/src/SceneEditor/Toolbar.js) and everything looks fine to me. 
![image](https://user-images.githubusercontent.com/42544589/77326073-42d76100-6d3f-11ea-8825-3ccded4d3c75.png)
Any different directory/file should I look for the required solution ?

**Comment by 4ian** [comment]
I don't know :) Investigate how accelerator is used. Is it an Electron bug? Are we properly using the API? Is the accelerator correct?

**Comment by NilayMajorwar** [comment]
I digged into this a bit, and I think I figured out the issue.

Firstly, this menu template almost directly goes to `electron.remote.Menu.buildFromTemplate(template)`. So the accelerator isn't really registered with Electron at all - it's just displayed in the menu. This is why the shortcuts aren't working right now. But there's another issue.

Support for numpad `+` and `-` keys was added in Electron 5.0.0, so we can't add that before upgrading our Electron version. The other `+` key is up on the `=` key, and `CmdOrCtrl+Plus` is displayed in the menu as `Ctrl+Shift+=` (on Linux/Windows) by the Electron accelerator parser.

Right now, for fixing the shortcuts not working, I guess we can add the shortcut registering code in `ElectronMenuImplementation.js` ([here](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/UI/Menu/ElectronMenuImplementation.js)), or wait for Electron upgrade, as Electron 3.1.3 allows to add `registerAccelerator: true` in a menu option to automatically register it.

@4ian What should we do? I'm willing to work on this one.

**Comment by PawBud** [comment]
> Firstly, the `Ctrl++` doesn't show, because `+` is interpreted as key separator by the Electron accelerator parser, so `++` leads to an invalid accelerator.
> yea this is mentioned in https://www.electronjs.org/docs/api/accelerator

**Comment by NilayMajorwar** [comment]
Now that Electron is upgraded, I had another look at this issue. `numadd` and `numsub` based accelerators show correctly now, but the shortcuts still don't work on Linux (and maybe Windows too).

It seems like accelerators don't get registered for context menus - they only get automatically registered when `Menu.setApplicationMenu` is called. This does make a bit of sense, since for context menus, the menu template isn't built (and accelerators wouldn't have been registered) until the context menu is opened at least once. And indeed, if I call `Menu.setApplicationMenu` with the context menu template in the context menu implementation, the zoom shortcuts get registered and start working.

A possible solution is to use the `globalShortcuts` electron module to manually register context menu accelerators (I haven't tried this yet). Though, it seems really strange why these accelerators currently work on MacOS, if I'm correct that they aren't registered automatically.

**Comment by PawBud** [comment]
@NilayMajorwar yea, There are many such issues that can finally be resolved after the electron upgrade!

**Comment by 4ian** [comment]
The menu is a context menu, shown only when the button is clicked.
As such, shortcuts are not working automatically. They are NOT handled by Electron... because the menu does not even exist when hidden.

The shortcuts in the InstancesEditor are managed in `DeprecatedKeyboardShortcuts`. If they don't work on Windows/Linux, take a look at this file :)
