### ISSUE TITLE
New editor available choices

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1611]
I prefer the old editor, but the new right-click menu 😍 saves so much time that I'm stuck with the new one.
The problem is figuring out if I have to pick an object first or if my condition/action (c/a) doesn't need me to pick an object first, because objects cannot be unpicked, so I have to close the menu and reopen it to reset.
For many c/as, it's pretty obvious.
But other c/as give me a hard time. For instance, _Create an object_ is linked, but _create from a name_ is not. 
Also, I expected the Link to be.. linked, but they're not. I realized that all c/as that need two objects are not linked.* Although I understand it, I don't think it's intuitive. Two is one plus another, after all.

The most counter-intuitive IMO, which triggered this report, is the "cursor/touch is on an object" which is not object-linked.

Maybe a good solution to avoid all this trouble would be to **not** hide the _non-linked_ c/as once an object has been picked? 

*Actually, the separate action is linked, although it involves two objects.

**Comment by 4ian** [comment]
> The most counter-intuitive IMO, which triggered this report, is the "cursor/touch is on an object" which is not object-linked.

Agree! This is fixed for next version.

> Also, I expected the Link to be.. linked, but they're not

Right, I'm a bit reluctant to move them to "object" conditions/actions because I would need to do it for the whole extension, and I prefer to avoid adding special cases.
In a sense it's normal because it's acting not on every object, but acting on the selection of objects. "Object conditions" are methods that can be called on individual objects. But the  conditions and actions from extension "Linked objects" are acting on the selection of objects.

Anyway, do you have any other action/condition apart from these? The "cursor/touch on object" was a great example.

**Comment by PascalLadalle** [comment]
Ah, once more, I forget to consider the angle of instances Vs objects.
That's all I had in store, I'll update here if I spot others.

**Comment by 4ian** [comment]
Sure! I'm closing this because "Cursor/touch on object" is fixed and the Linked Objects extension will remain in Other conditions/actions - but please comment here if you find another action/condition and I'll get a notification.
