### ISSUE TITLE
Problems with BBCode size change

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1627]
The action to modify the font size does not work properly when using the + operator. It gets the BBCode object frozen.
When using several decimals, it even crashes the preview.

I'm attaching a sample project. You'll notice the tweening doesn't work either.
[bugtextscale.zip](https://github.com/4ian/GDevelop/files/4440607/bugtextscale.zip)

**Comment by 4ian** [comment]
Might be because the "getter" function is not set properly for the BBCode font size in the `JsExtension.js` file.

**Comment by arthuro555** [comment]
Did #1688 Fix that issue?

**Comment by 4ian** [comment]
I don't think so, can you try the project from PascalLadalle?

**Comment by Quarkstar** [comment]
> It gets the BBCode object frozen.

I think it's because "Invert Condition" of the condition 'The timer "test" is greater than 2 seconds' is true, so actions are executed at the beginning. :P

> When using several decimals, it even crashes the preview.

It's because of type of `fontSize`. Font size should be a number, but it's actually a string. So `+` operator does string concatenation, not addition.

**Comment by 4ian** [comment]
Good catch, thanks @Quarkstar!
