### ISSUE TITLE
Variable object no editable selectable (repeated select object)

### ISSUE THREAD

**Issue by johnbelweb** [4ian/GDevelop#1643]
![ttt](https://user-images.githubusercontent.com/7013548/79057090-df946c80-7c22-11ea-9058-24f45b36850f.jpg)
Unable to select object variable from outside

**Comment by PascalLadalle** [comment]
I don't understand, is this an actual screenshot?
It's a mix of an object variable action and a scene variable action 🤔  a mistranslation perhaps?

**Comment by 4ian** [comment]
I think it's a wrong translation indeed. Would be interesting to add some checks in GDevelop to autodetect this

**Comment by Bouh** [comment]
I've found why, it's fixed now!

![image](https://user-images.githubusercontent.com/1670670/79081951-4c426080-7d22-11ea-8900-651201abdb9f.png)

**Comment by Bouh** [comment]
Btw lot of bad translation from this user.

**Comment by 4ian** [comment]
The translation should not include escena, because it's for variables of objects (or any other variable), not for scenes!
This kind of bad translation is very damaging. I undo-ed all translations from this user because a bad translation is 10x worse than no translation.

> i've checked all string with _PARAM and remove translation when a param is missing in the translation compare to the original.

Thanks!

Closing now as this should be fixed.
