### ISSUE TITLE
Tween conditions conflicting?

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1665]
I'm having problems with tweens... tween chains more particularly. 
Not sure what's wrong, so I tried isolating the issue, and ended up with what seems like a bug.
Here are some debug text events:
![image](https://user-images.githubusercontent.com/25978830/79503496-8ae15f00-8031-11ea-90a4-9615699d43cc.png)
It should display _show showed hide hided_ three times and _transp transped_ when a cycle of three is finished.
And here is the output:
![image](https://user-images.githubusercontent.com/25978830/79503676-dac02600-8031-11ea-99bb-ef7cc1b147f3.png)

_hide_ and _transp_ never show.

Test project attached.
[bugtweenseries.zip](https://github.com/4ian/GDevelop/files/4489635/bugtweenseries.zip)

**Comment by AlexandreSi** [comment]
I'm closing this since I think there was an issue with the version of GDevelop that saved the project you joined to the issue (and I hope this wouldn't happen today):

What you sent:
<img width="320" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/55b6fbb5-85ee-4722-acc6-a6fb209d61d8">

After simply opening the condition in the instruction editor and saving the project:
<img width="320" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/d57df0b2-997e-4e0e-9bcd-20592007c33e">

(Behavior name `Tween` was missing in your project)

And here is what the debug text says (I think that's what you were expecting):
<img width="697" alt="image" src="https://github.com/4ian/GDevelop/assets/32449369/3543da0d-31e8-4b4c-b026-6c887e0720cb">
