### ISSUE TITLE
Panel sprite "9-patch" wrong angles

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1723]
## Describe the bug
The angles of the panel sprite can be wrong when the camera move.
@Quarkstar,  See how it work on PixiJS V5.

All sprites in angles are to 0;0.

![image](https://user-images.githubusercontent.com/1670670/80868489-3aa60600-8c9b-11ea-9575-a25d9349b571.png)

[Video](https://streamable.com/4hgdgk)

[Source](https://forum.gdevelop-app.com/t/panel-sprite-not-rendering-correctly-when-spawned-off-screen/24633/3)

It's possible to add a github tag  PIXI ?

## To Reproduce
[panel_sprite_angles_wrong.zip](https://github.com/4ian/GDevelop/files/4567989/panel_sprite_angles_wrong.zip)

Launch the example, wait 3sc, some panel are generated, while this time the camera move.

## Other details
* B92, pixi 4.8.6

**Comment by Quarkstar** [comment]
Pixi v5 branch is the same.
And I had met this problem before. It's random. If you delete this object, and create a new one, it works as usual.

![Screenshot from 2020-05-02 23-48-08](https://user-images.githubusercontent.com/32167255/80868851-9a1e0900-8ccf-11ea-994b-1bd4437d965b.png)

**Comment by Bouh** [comment]
Here the issue is in the preview, it's occur sometime, very weird.

[Video](https://streamable.com/4hgdgk)

**Comment by Quarkstar** [comment]
https://github.com/4ian/GDevelop/blob/f3dc69ea6860dca776d46bc37db38ddd40abc1a1/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L355

I print the width and height of `this._borderSprites[7]` here, and I find that this returns different value at different times. Sometimes it works well and returns (32, 39), sometimes it returns (10, 7), which is the value of `RightMargin` and `BottomMargin`.

**Comment by 4ian** [comment]
> But I can't find out why it was called twice.

Naively I think we should make it work even if it's called twice.

> And I find that we use texture.height for Left and this._borderSprites[5].height for Bottom Left.

Indeed very strange 🤔Good catch! 👍👍
Give it a try with texture.height (and texture.width) and let me know if it works 👍

I guess the issue with `this._borderSprites[5].height` (and the other similar stuff) is that when `updateTexture` is called twice, the size are already changed!

**Comment by Quarkstar** [comment]
> Give it a try with texture.height (and texture.width) and let me know if it works

Yes, it works. But I still have two questions.
 - Does the original code has a special purpose? It doesn't look like a mistake. I am afraid I broke something. 

- And `updateTexture` is called twice because of this `texture.on`. Does it matter?
 
https://github.com/4ian/GDevelop/blob/f3dc69ea6860dca776d46bc37db38ddd40abc1a1/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L216

I think it doesn't work as our expectations.`Updating PanelSprite instance texture`[link](https://github.com/4ian/GDevelop/blob/f3dc69ea6860dca776d46bc37db38ddd40abc1a1/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L224) is always printed twice in console.    

### Screenshots
 https://github.com/4ian/GDevelop/blob/f3dc69ea6860dca776d46bc37db38ddd40abc1a1/newIDE/app/src/ObjectsRendering/Renderers/RenderedPanelSpriteInstance.js#L216




![Peek 2020-05-03 19-06](https://user-images.githubusercontent.com/32167255/80912708-7ca17b80-8d71-11ea-90ac-b53ef2ed794d.gif)

**Comment by 4ian** [comment]
> Does the original code has a special purpose? It doesn't look like a mistake. I am afraid I broke something.

I think it's a mistake :)

**Comment by 4ian** [comment]
And thanks a lot for investigating! This will be a great thing to fix. You can also verify the logic in the game engine object renderer: https://github.com/4ian/GDevelop/blob/master/Extensions/PanelSpriteObject/panelspriteruntimeobject-pixi-renderer.js, to see if there is a fix to do there or not.

**Comment by Quarkstar** [comment]
Thank you! And I meet a little problem with electron's updating. I will open a pr as soon as everything is okay.
