### ISSUE TITLE
Why the "save alert" is alway shown even if the project saved ?

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#1754]
## Description
It's scare me everytime ! Why the "save alert" shown even if the project is saved ?
Can you fix it ? It's not very hard.
## Solution suggested
I think you just need to create a boolean variable "isProjectSaved" and when 
we click on "save" (or ctrl+s) `isProjectSaved = true` 
and when we change something in project `isProjectSaved = false` 
Finally with variable isProject save you made something like : 
`if( isProjectSaved == true ) {
//you just quit the app here
}else {
alert("WARNING : your project is not save ! [enter the rest of the sentence here]");
}`
Excuse me fr my english ; I'm french.

**Comment by 4ian** [comment]
It should not be shown in the latest versions if you've not made any changes since you saved your project. 
Whenever a change is made, an asterisk is shown after the filename in the titlebar.

There is still a confirmation when you want to quit GDevelop. But it's telling you that you have unsaved changes only if you have made changes since the last save.

> I think you just need to create a boolean variable "isProjectSaved"

That's more complicated than that ;) But basically it's already implemented.
If you have a specific situation where the asterisk is not shown or a warning is missing after doing a change, please report it with the specific steps to reproduce this :) Thanks!
