### ISSUE TITLE
Custom loading screen for our game

### ISSUE THREAD

**Issue by Oxey405** [4ian/GDevelop#1755]
## Description
Can you add a feature for made a custom loading screen ?
(With a custom loading logo and progress bar but with gdevelop logo just in a down corner)

## Solution suggested
A menu in "game settings" you add "custom loading screen"
And in this menu we can set a logo or a sprite and give to him a short animation,
with a progress bar or not and with gdevelop logo or not (like in properties menu )

**Comment by arthuro555** [comment]
Please ask such feature requests on the forum first, we already know about this missng feature and it is already on th roadmap. Thanks :)

**Comment by 4ian** [comment]
@arthuro555: In these case, add a link to the card on the roadmap and gently invite to vote on it: https://trello.com/c/VY8dyDbk/162-update-the-splashscreen-of-games-with-a-better-looking-one-or-give-customization-options

This gives an actionable answer to the request ("if you want it, you can do the small action of voting") rather than an answer that is a dead-end ("you're at the wrong place, get out").

@Oxey405 As Arthuro555 explained you can find this feature request in the roadmap, and vote/comment on it. I'm closing this issue in favor of this Trello card. Thanks! :)

**Comment by Oxey405** [comment]
You don't understood @4ian ; I want WE (as developper) can customize our loading screen as we want (like personalized logo and title with the link in a corner for non-permium version)

**Comment by 4ian** [comment]
Yes that what I mean by "give customization options" in the card title.
