### ISSUE TITLE
GDevelop (all versions) download freezes around 50%.

### ISSUE THREAD

**Issue by CamleeW** [4ian/GDevelop#1790]
Ok, so when I try to re-download GDevelop, the progress bar in the set-up wizard freezes at about fifty percent. People have told me to re-download the old version (89), but the same thing happens on all of the versions I've tried. Also its worth noting that both 93 and 89 appear in my uninstall settings, but I can't actually uninstall them because they don't exist on my machine. Is there anything else I can do other than wait for the 94 to come out?

**Comment by 4ian** [comment]
Hard to tell what could be going wrong. Can you confirm your operating system? Have you tried rebooting? This is not a download progress but an installation progress bar. I would advise to ask this question on the forum because other members will be able to help you - this seems not related to GDevelop but to Windows :) 
I'll close this issue but feel free to continue to answer here (but again, a thread on the forum would help I think).
