### ISSUE TITLE
Instance variables in properties panel , blur the focus unsave the change.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1818]
## Describe the bug
When we enter a new value or rename a instance variable in the properties panel and select another instance the text isn't saved.

## To Reproduce
1. Select an instance
2. Add a instance variable
3. Do the same on another instance.
4. Type a new value and select directly another instance and go back to the previous.
5. The text is gone.

![mmmmm](https://user-images.githubusercontent.com/1670670/84691876-2feeba00-af45-11ea-9b77-5f680b83a374.gif)

The[ onBlur props](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/VariablesList/index.js#L235-L252
) on <SortableVariableRow> doesn't work when we select another instance.

## Other details
* b96 web and pc

**Comment by Bouh** [comment]
Solution suggested remove this line:
https://github.com/4ian/GDevelop/blob/6870a53aedea9db94dcfa38cba0c4acff4bec07d/newIDE/app/src/VariablesList/VariableRow.js#L95

I want to know if this can have some repercution somewhere else.
A priori it's good even in the dialog.

**Comment by 4ian** [comment]
Would be good to check with the React profiler if this is re-rendering the whole dialog after each key press (there is an option to highlight renderings in the React profiler, useful to see this kind of stuff).

**Comment by Bouh** [comment]
Indeed the whole dialog or properties panel are re-render :/

**Comment by 4ian** [comment]
Let's make it a prop so that we use commitOnBlur for the dialog (to avoid useless re-rendering) (and we need to click on Ok to close the dialog, so no risk of losing what the user entered) and not have it for the variables in the properties panel (as it can be dismissed at anytime without warning).

Note that we can't use a "componentWillUnmount" lifecycle method to call a onChange prop, because we risk calling a prop while the component is destroyed because the variable/the list of variable is removed from memory.

**Comment by Bouh** [comment]
[Like this ?](https://github.com/Bouh/GDevelop/commit/c94382f9221928998c6150fdf56d39d99dc4bb6f)

**Comment by 4ian** [comment]
> I think i can replace commitOnBlur={true} by commitOnBlur

Yep.

Also rename `commitOnBlur` by `commitVariableValueOnBlur` but apart from this I think that it should work?

**Comment by Bouh** [comment]
This issue can be closed too.
