### ISSUE TITLE
findRStr and findStr misunderstood

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1857]
## Describe the bug
According the wiki page StrFind return the position of an string in another string, from left to right.
StrRFind should do the same job but from the right to the left, but return the same value as StrFind when the research term is once in the string.

There is a misunderstood with these expression because StrRFind return the lastest occurence of the research and start the count from the left.
People understand that the expression will return the position from the right.

[Wiki decription:](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/expressions-reference#expressions_reference)
`
StrRFind(string, string) = Search in a text from the end (return the position of the result or -1 if not found)
`

Correct case presently in gd:

```
var domain="www.test.com";
var lastdot= domain.lastIndexOf("t");  //return 7, from left to the right
```
How people think have the value:
```
var domain="www.test.com";
var lastdot= Math.abs(domain.lastIndexOf("t") - domain.length+1); //return 4, from right to left
// it's always the lastest 't' but from the end like it's explain on the wiki.
```

So what to do ?
I know if i tweak the expression findRStr, this will be broken for all previous games.
So maybe there is a simplier way to find the position from the end, or i can add a new expression for it, and we edit the description of the findRStr for explain clearly what is expected.

## Other details
b97

**Comment by 4ian** [comment]
I think we should clarify the description then! 
Also, returning something from the right can be also "risky" because some would assume it should return the number of letter sfrom the end to the beginning of the searched string, while someone could assume it should return the number of letters from the end to the end of the searched string. In other words:

```
var domain = "this is test"
domain.lastIndexOf("is") => // should return 5, 6 or 7? 
```

5 would be the *distance* between the end of the last character
6 would be the *position* of the last character of the last searched string
7 would be the *position* of the first character of the last searched string.

So I would say:
- let's clarify the description to say that "Search the last occurence in a string (return the position of the result, from the beginning of the string, or -1 if not found)".
- The name is a bit unfortunate. All the "R" functions were inspired by C++ rfind: http://www.cplusplus.com/reference/string/string/rfind/ - you can see that the description of the reutrn value is "The position of the first character of the last match.". Maybe we could hide the expression and add a new one called `StrFindLast`. It seems much clearer: "it search the string, but gives you back the **last** one".
- I would advise against making a version that returns the number of character from the end because:
  * As I wrote before, it's unclear what it should return
  * People can easily do `StrLength(thestr) - StrFindLast(thestr, searched string)` if they want to :)
  * If you think we really need it, would be great to find a programming language offering this function, so that we can validate that we have the same implementation.
