### ISSUE TITLE
Replace UID with instance check in linked objects

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1861]
We still don't have an official place/I still don't know where to propose technical changes, so I'm doing it here.

I think @4ian said multiple times he relucantly added UIDs to onjects as they are an anti pattern. What if instead of the UID we used the reference? As you can see we can check if a reference to an object == another reference to an object and it still works when making a variable with a reference to the reference: 
![image](https://user-images.githubusercontent.com/19349038/87401936-1def4e00-c5bb-11ea-877a-f4ac2ddb4039.png)
Why not use that instead of UIDs?
We could either keep the current links manager, and use a real hashtable (or a weakmap, feature of ES6, supported by IE 11, oldest supported IE version) to map a runtime object reference to an array of references to other runtime objects, or move the list of linked objects of each RuntimeObjects to the RuntimeObject class.

**Comment by 4ian** [comment]
`we can check if a reference to an object == another reference `

Yes. Though always use === in JS ;)

There is no real incentive to keep UID if we replace them in the link manager, though it's still not completely easy to remove them, because
- "move the list of linked objects of each RuntimeObjects to the RuntimeObject class" => it's actually a "hack" to add properties to RuntimeObject. This will destroy any optimization done by the JS engine. See this article: https://richardartoul.github.io/jekyll/update/2015/04/26/hidden-classes.html and notably this take away: 
![image](https://user-images.githubusercontent.com/1280130/87536200-01294800-c699-11ea-88a5-1e670803dc20.png)
- "a real hashtable (or a weakmap, feature of ES6, supported by IE 11, oldest supported IE version) to map a runtime object reference to an array of references to other runtime objects" => could be as solution, though this need to be checked against compatibility for Android 4. (I'm happy to drop compatibility with Android 4 "soon", but still if we can avoid it's better).

And finally, if we start having part of the engine rewritten in WebAssembly in the future for increased/consistent performance, we might actually find a proper usage of the UID, by allowing to pass a list of "ids" to webassembly to designate objects. 

> he relucantly added UIDs to onjects as they are an anti pattern

Yeah, let's say that I want to minimize the "exposure" that they get. Turns out that some engine based on "entity components" (called "object" and "behaviors" in GD) work with ids for their entities. But that should be an implementation detail. Maybe later ids will be integers, will be changed to be stored in a list outside of the objects, will be removed, etc... I prefer to avoid exposing too much internal stuff, especially to GDevelop users because this may be more surprising that we can think of ("oops, why the id 15 was skipped?" "Well we now only generate ids starting from 100 for various reasons" "Damn I was using it to count objects, please fix that!" ;)).

**Comment by arthuro555** [comment]
Nvm then, we don't want to get rid of UIDs, and WeakMaps have a default: While the key has a weak reference, the value doesn't and as it isn't iterable we cannot remove manually the refernence linked to still existing objects so we would have a memory leak. We would need a WeakValueMap (non existing yet) or to set a weak reference as value ([non existing yet](https://github.com/tc39/proposal-weakrefs)).
