### ISSUE TITLE
Trigger once is shared among instances

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1874]
Shouldn't a _trigger once_ inside a _for each_ work **once for each** instance?

I'm attaching a sample project to illustrate.

[FrameTrigger.zip](https://github.com/4ian/GDevelop/files/4940622/FrameTrigger.zip)

**Comment by blurymind** [comment]
I believe you need to target the instance with some other conditions to
make it happen only for the instance

**Comment by PascalLadalle** [comment]
I used an object timer in my example. And the objects are deleted every two seconds, so I think the _trigger once_ should reset.
For your convenience:
![image](https://user-images.githubusercontent.com/25978830/87836668-38624980-c891-11ea-92e3-3e1ce8d5b246.png)

**Comment by 4ian** [comment]
By design the trigger once is only at the event level, so shared by all instances (it has no notion of instances).
If you want a trigger once per instance, you'll need to use it in a behaviour (there is a fix for this coming in next version).

This being said, the trigger once is only returning false at the next frame. So here, the actions in the for each should be run for all instances of the for each (if their timer pass the condition).

Also note that as long as there is one instance (ANY instance) fulfilling the timer condition, the trigger once will stay false. It will only be valid again if there is nothing run in the for each (no instances having a timer validating the condition, or no instances at all).

To be sure though, I would recommend avoiding trigger once in a for each/repeat.

**Comment by 4ian** [comment]
Oh also I think there is some misunderstanding of Trigger Once. 

I should probably rename it to "Trigger Once IN A ROW". The events using variables are NOT equivalent. They are setting a variable that will stay there forever. Trigger once will just prevent your event to run more than one frame in a row.

**Comment by PascalLadalle** [comment]
Yes, I'm aware the workaround isn't equivalent. 👍 
The full name is _Trigger once while true_, so I guess it's fine.

Thanks for the explanation, good to know. 
This should probably go somewhere, as a hint inside GDevelop when a _trigger once_ is a subcondition of a _for each_? or somewhere in the wiki?

Indeed if I delete the bullets earlier, the subbullets spawn as expected.

**Comment by blurymind** [comment]
I think clickteam fusion has a special condition to trigger once per each
instance or something like that
