### ISSUE TITLE
npm run check-types runs globally installed tsc

### ISSUE THREAD

**Issue by HarsimranVirk** [4ian/GDevelop#1876]
In GDJS/package.json, the script `check-types` runs the globally installed typescript's compiler, not the locally installed tsc. This might be different on Mac/Linux (I'm not sure) but happens on Windows. 😅 Due to the differences in the version of local and global tsc, the errors are significantly different as well.

**Comment by 4ian** [comment]
Yeah there are a bunch of new errors when using TypeScript 3.7+ due to a few `@private` tags.
I'm surprised it's using the globally installed version though because the npm script is just running `tsc` and Node.js should run the version installed in the node_modules... maybe we must use another command line?

**Comment by HarsimranVirk** [comment]
I tried two ways of running the local tsc, one was the command `npx tsc` (I'm not really sure if it's the correct way) and the other more obvious way was to cd into node_modules/typescript/bin and run the local tsc :) 

There could be more ways as well or maybe the most correct/official way of fixing this, but we still have these two options. 😅

**Comment by 4ian** [comment]
`npx tsc` will download and execute on the fly the `tsc` package afaik, so it's definitely not what we want here.

> to cd into node_modules/typescript/bin and run the local tsc :)

That's what I would be expecting node to do when you run `npm run check-types`, because it has some logic to run first things that are in `node_modules/bin`... but maybe actually there is no `tsc` there?

If I do `cd GDJS` then `ls node_modules/.bin` I can see something called `tsc`. Can you check if it's here for you?

**Comment by HarsimranVirk** [comment]
> If I do cd GDJS then ls node_modules/.bin I can see something called tsc. Can you check if it's here for you?

I do have the `tsc` in `node_modules/.bin` (which is the correct locally installed version as well), again not sure why it doesn't run this one instead of the global tsc. I could even see issues like this being already solved in typescript's repo 🤔 I removed the globally installed typescript and everything seems to run fine.

I guess it's not GDevelop specific, maybe we could just update the readme saying you might get issues if you have globally installed typescript, and maybe add another npm run script which specifically cd in `node_modules/.bin` (or `node_modules/typescript/bin` and runs the local tsc?

**Comment by arthuro555** [comment]
For me check-types always used the local tsc on windows
