### ISSUE TITLE
karma test command doesn't work in windows

### ISSUE THREAD

**Issue by HarsimranVirk** [4ian/GDevelop#1883]
https://github.com/4ian/GDevelop/blob/661d32917002dd4f2852c67b22f62c294e99bd8d/GDJS/tests/package.json#L8-L9

These don't work on windows because `./something/app` results in `'.' is not recognized as an internal or external command,
operable program or batch file.` due to differences of backslash/frontslash. 

Maybe a more inclusive command could be `"test": "cd ./node_modules/karma/bin && karma start ../../../karma.conf.js --browsers ChromeHeadless --single-run"` (and similar for firefox) as this should work in all environments 😅

**Comment by arthuro555** [comment]
I always jusr manually run karma like this if I remember correctly: `.\node_modules\.bin\karma.cmd  start --browsers ChromeHeadless --single-run`

**Comment by HarsimranVirk** [comment]
@arthuro555 `.\something\app` works fine as cmd understands `.\` but not `./` due to differences between frontslash and backslash 😅. This is why it's better to change directory (as both windows and linux/macOS would interpret them correctly) and then run karma, and because we are in a different dir, specify the correct path to `karma.conf.js` (which is `../../../karma.conf.js` in this case).

**Comment by arthuro555** [comment]
We shouldn’t use a backslash at all, if karma is in node_modules/.bin, we should call karma directly and it should call the version installed in node_modules automatically

De : Harsimran Singh Virk<mailto:notifications@github.com>
Envoyé le :mercredi 22 juillet 2020 18:59
À : 4ian/GDevelop<mailto:GDevelop@noreply.github.com>
Cc : Arthur Pacaud<mailto:arthur.pacaud@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [4ian/GDevelop] karma test command doesn't work in windows (#1883)


@arthuro555<https://github.com/arthuro555> .\something\app works fine as cmd understands .\ but not ./ due to differences between frontslash and backslash 😅. This is why it's better to change directory (as both windows and linux/macOS would interpret them correctly) and then run karma, and because we are in a different dir, specify the correct path to karma.conf.js (which is ../../../karma.conf.js in this case).

**Comment by HarsimranVirk** [comment]
> if karma is in node_modules/.bin, we should call karma directly and it should call the version installed in node_modules automatically

Yes, this could be the most correct way I'd say then 👍
