### ISSUE TITLE
B99 Error: "Can't Properly Export the Game" - Majority of Automated and Local Export types not working

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#1958]
## Describe the bug
When attempting to export in B99, you receive an error "Can't Properly Export the Game."
If using one of the online exports, it also says to check your internet connection.
If using the local Manual export, no additional details are given outside than the above error.
Local HTML5 export works.

## To Reproduce
1. Install B99
2. Create a project with the platformer example
3. Click the Export Game button.
4. Choose Online Export (Android, Web, Windows/macOS/Linux), iOS & Android (manual), or Windows/macOS/Linux (Manual.
5. Click Package. The error will occur almost immediately.

A user on the discord reported this on Solus Linux (and reconfirmed on Arch and OpenSUSE), here's a screenshot from there:
![image](https://user-images.githubusercontent.com/24237149/91855688-1ea37880-ec2b-11ea-84e5-94fd1abd1365.png)

While I couldn't reproduce it with local export on my first attempt, it did occur on my second attempt (Windows 10 Pro 64 bit):
![image](https://user-images.githubusercontent.com/24237149/91855887-6c1fe580-ec2b-11ea-999d-f39003755231.png)
![image](https://user-images.githubusercontent.com/24237149/91855896-6fb36c80-ec2b-11ea-8c83-2a9379a7bcff.png)

## Other details
* Include any OS/browser version/smartphone that you're using.  **(Included above)**
* Which version of GDevelop are you using?  **5.0.0-B99 desktop version**
* Add any other context about the problem here.

**Comment by Silver-Streak** [comment]
Some users also reporting this on the forums:
https://forum.gdevelop-app.com/t/error-while-exporting-the-game/27269

**Comment by Bouh** [comment]
This issue is only on _Windows/MacOS/Linux_  online and _Windows/MacOS/Linux_  local exports.

Btw both the exports work fine with the current master branch and their API keys...

**Comment by 4ian** [comment]
Fixed in 23d64aa676eaf789ce31d5176b23f212f3b8031d and released an emergency bugfix release :) Thanks for reporting this!

We've been especially unlucky because it would not happen in development, because the crash in the export happened when the dummy example extensions were not loaded (these example extensions are not loaded, and because currently there is no other extensions using the "npm dependencies" feature, this resulted in a crash in the code handling them) and I only ran an Android export before pressing the button to publish the release :)

Anyway, should be good in beta 100!

**Comment by papasfilms** [comment]
Thanks
