### ISSUE TITLE
Shifty error in console

### ISSUE THREAD

**Issue by trsh** [4ian/GDevelop#1972]
## Describe the bug

![error](https://user-images.githubusercontent.com/3727523/92634297-bfa1cb80-f2dc-11ea-8217-2ffa835709ef.png)

## To Reproduce
1. Add to some object tween behavior
2. Add some tween to the object
3. Start project and open dev console

## Other details
* Windows 10 64x
* GDevelop desktop app 5.0.0-beta99

**Comment by Bouh** [comment]
Can you use the lastest beta ?[ Beta 100](https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta100)

If the issue persist, can you add details which action and give more details as you can.
Give a sample file is also a good pratice much appreciated.

I ask all of this because i use Tweens behaviors on beta 100 with colors interpolation and it work fine.

**Comment by 4ian** [comment]
That's one of the issue fixed in beta 100 :)
