### ISSUE TITLE
 Light crash the game in canvas

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1973]
## Describe the bug
When the canvas is used, instead webGL, the game have an black screen during the loading because an error is trigger in the console.

## Error
![image](https://user-images.githubusercontent.com/1670670/92634349-751c5100-f2d4-11ea-9ed3-1a24528f8c20.png)

## Possible solution
- When the context webGL is missing then disable the light.

@HarsimranVirk 

[Source #1](https://forum.gdevelop-app.com/t/gdevelop-5-beta-100-light-example-not-work-on-canvas-with-pixi-legacy-support/27293)
[#2](https://forum.gdevelop-app.com/t/light-not-working/27430) 

## Other details
* Beta 100
* On low devices without webGL

**Comment by HarsimranVirk** [comment]
@Bouh @4ian what should we do in this case? WebGL is definitely necessary (for pixi mesh), should we just check WebGL and warn if the device doesn't support it?

**Comment by 4ian** [comment]
In these conditions we should indeed disable the light, which will consist surely in return null from getRendererObject so that nothing is displayed? (not sure exactly where we should add the guards in the code as I can't read the error on the screenshot, but that's the idea).

Also log an error in the console (as a good practice, when something is not supposed to work, log it) and that should be enough.
