### ISSUE TITLE
Changing the opacity of a TiledSprite while not visible will result in invisibility

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#1980]
If you change the opacity of a TiledSprite while it is not visible then it becomes permanently invisible.
I discovered this bug when "not visible" meant the object was more than 1000 pixels off screen.
However you can contrive this defect by setting the TiledSprite to be hidden and then changing the opacity.

Very simple reproduction:
[opactiy-bug-5b100.zip](https://github.com/4ian/GDevelop/files/5213307/opactiy-bug-5b100.zip)

You can remove the single "Hide LockBlue" line below that hides the tiled sprite and the example works as intended by alternating between transparent and not on each mouse click.
![opacity_bug_logic_screenshot](https://user-images.githubusercontent.com/251967/93005790-0af4ed80-f51a-11ea-9a8c-65e69bb5ba0b.jpg)

Version: GDevelop 5.0 b100

**Comment by krunkster** [comment]
Based on my quick glance at the code this might be related to the updateOpacity() method in the pixi renderer code:
`gdjs.TiledSpriteRuntimeObjectPixiRenderer.prototype.updateOpacity = function() {
    //TODO: Workaround a not working property in PIXI.js:
    this._tiledSprite.alpha = this._tiledSprite.visible ? this._object.opacity/255 : 0;
}`

Perhaps there is also code somewhere else that looks to see if "alpha" is 0 and consider it not "visible" therefore getting the object stuck in an invisible state?

**Comment by Bouh** [comment]
Hello 
This happend on others objects or only tiledSprite?

Maybe the reason is the updateVisibility function and visible attribute are missing for tiledSprite (exist on Sprite).
Can you confirm this happen **only** on tiledSprite?

**Comment by 4ian** [comment]
Totally possible that something is mixed up and visibility is impacting opacity because of a workaround. I think the PIXI bug is fixed since a long time, so we can use the `visible` property in PIXI now and remove the hack, by always setting the `alpha` to the value set by the user :) 
Let me know @Bouh, good opportunity to remove a hack that actually make a bug

**Comment by Bouh** [comment]
Yes the ternary condition can be deleted.

`this._tiledSprite.alpha = this._tiledSprite.visible ? this._object.opacity/255 : 0;
`
to

`this._tiledSprite.alpha = this._object.opacity/255;
`

I need do the same thing on the sprite because the hack is also present, even if this one work, if i can simplify...
I'am in charge of this fix :) 

I'll do some tests !

**Comment by krunkster** [comment]
Thanks for addressing this... should I close the issue or is that done by some other process?

**Comment by Bouh** [comment]
I do.
Thank you for this very useful bug report!
