### ISSUE TITLE
Count Object Condition: Unintended behavior for created objects within sub event

### ISSUE THREAD

**Issue by TerraPrimal** [4ian/GDevelop#1981]
Greetings,

After speaking with a few gdevelop guardians in my [original thread](https://forum.gdevelop-app.com/t/actions-after-object-creation-not-functioning-as-expected/27482/7), it looks like the Count Object Condition is causing unintended behavior for object creation as a sub event, or as Gruk put it

`this condition is interfering with the instance filtering GDevelop makes to apply the actions`

Which roughly translates to _"All objects of that type are being effected rather then just the spawned object. It’s as if you’re using a For Each Object loop."_

I have created a simple project that be played [here ](https://games.gdevelop-app.com/game-830e105a-f92a-427e-8bbd-e488e3064999/index.html)or downloaded from [here ](https://multifilemirror.com/c81ffmq602s3/Bug%20-%20Number%20Of%20Units.zip.html)that has normal creation with the Q key and the bugged creation with the W key

Image of the event sheet can be viewed [here](https://i.gyazo.com/12d088f4dc190558060eaafdc2048154.png).

Running: Windows 10, GDevelop 5.0.0 - Beta 99

Thanks!

**Comment by 4ian** [comment]
I *think* this is working as intended.
* When you use a condition, here checking the number of objects, any subsequent actions, **including** in the sub events, will be affecting the objects fulfilling the conditions.
* When you use the action to create an object, the object that is created is **added** to the list of selected objects being affected by subsequent actions.
 
This means that in these events, the "object_1" that are fulfilling the condition (i.e: either none if they are more than 100 or all of them if they are less or equal to 100) are then used in all the areas that I annotated with an orange rectangle:
![image](https://user-images.githubusercontent.com/1280130/93018497-6b466680-f5d0-11ea-8b7a-0e9bb5219235.png)

When you create a new object, it's just added to the list of objects being selected, until the next sub-event.

This being said, to achieve what you want, there are three ways:
* Either we add a special condition/action "Forget any picked object XXX", to clear the list of selected objects (but this is a new feature to be added)
* or you use a temporary variable. You set it to 0 before the condition. Then you use the condition, setting the variable to 1 if the condition is fulfilled. Finally, in **another** event, you create a new object and set it up. Because there will  be no conditions, only the object_1 being created will be affected.
* or you say "I'm tired writing these actions everytime I create an object, I want this to be done automatically!". In this case, create a custom behavior, then use a behavior method that is run when the object is created: 
![image](https://user-images.githubusercontent.com/1280130/93018632-68984100-f5d1-11ea-9fd7-7d119116ec48.png)

For this last solution, you surely need to set up your behavior to be applied only on Sprite objects, so that you can use the actions specific to sprites: 
![image](https://user-images.githubusercontent.com/1280130/93018639-7bab1100-f5d1-11ea-8b38-b4cfad341076.png)

The last option is what I recommend to organize your game if it's growing. It's a bit more technical though, so maybe the variable will be a better solution.

There is a last problem: how do we avoid this confusion in the future? Maybe with an explanation when setting up the "Create an object" action?? 
Or we could modify the action so that any existing objects that have been selected by conditions are "forgotten", but this should be I think a choice from the user?

**Comment by Bouh** [comment]
> but this should be I think a choice from the user?

Yes for sure!

I like the idea to clear the selection of objects. 
It's for an user the simplier thing. Even if i understand you wish see users used the custom behaviors :)

**Comment by TerraPrimal** [comment]
Thank you for the in-depth reply and looking into this 4ian.

I should have been more clear in the original post that I had found a solution using function / extension system. However arthuro thought this may have been unintended behavior and suggested I create a report.

I agree 100% with Bouh that this should be a choice. Using this condition as normal user, it's assumed that this wouldn't function as a loop and iterate through all current objects as nothing suggests it would (on the user end).

**Comment by Silver-Streak** [comment]
Just bringing this back up. This has popped up on numerous issues recently on the discord.

The current condition does not indicate that it would select those objects, and it does not get overwritten by any child events/actions, so it leads to a lot of user confusion. 

(e.g. "Number of objectA objects < 100" as a condition, then in the events you create objectA, and try to set its animation to 2 immediately after creation, it sets *all* objectA animations to 2.)

What's more interesting this this seems to occur with the expression, as well. 

Using the "Compare two numbers" condition, with Count(objectA) < 100, it *still* treats it as if all objects were selected, which doesn't seem to be intended behavior for the compare numbers condition, unless I'm missing something. Is this expected?

I do think the condition could be updated to "Number of objects is (equation) (number), select all (yes/no)" or the expression shouldn't select the objects so the users could do it themselves that way.

Even separate from the above, a "deselect all objectname objects" condition/action would be super useful in numerous cases.

**Comment by 4ian** [comment]
Back to this, we could:
- Keep `Count` as is, as we can't modify it for backward compatibility. Notably:
  - If you use it after referring to an object (i.e: using a condition), it will count the picked objects.
  - But if you use it for the first time, it will pick all the scene objects (that's the weird side effect).
- Add a `PickedInstancesCount`, that will only count the picked instances of the specified object. 
- Add a `SceneInstancesCount`, that will only count the instances of the specified object (or group) on the scene.

**Comment by tristanbob** [comment]
> * Keep `Count` as is, as we can't modify it for backward compatibility. 
> * Add a `PickedInstancesCount`, that will only count the picked instances of the specified object. No object picking done (because, well, they are already picked!).
> * Add a `SceneInstancesCount`, that will only count the instances of the specified object (or group) on the scene. No object picking done.

@4ian thanks for coming back to this.  

I just reread this (and the linked issue by Pandako) and I think you found a very good solution!

**Comment by 4ian** [comment]
> reproduce the existing functionality of the current condition

My question would: what do you want to reproduce?

- You want to check the number of objects on the scene: use the associated condition/expression (`SceneInstancesCount`). Then use other conditions (they will apply on all objects, because objects have never been filtered)
- You want to check the number of picked objects: use the associated condition/expression (`PickedInstancesCount`). You probably already used other conditions before because otherwise it does not make sense to use PickedInstancesCount (well, it will work and return "0" - nothing was picked).
- Any other usage? 

What I mean is that there is "nothing to pick" actually. You will count only the scene instances (not changing what you pick) or picked instances (not changing them). Unless I missed something?

**Comment by Silver-Streak** [comment]
Awesome, thanks for the details.

I think your plan would cover everything I've experienced myself or tried to help with on the discord/forums.
