### ISSUE TITLE
Deprecate Inventory extension

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#1986]
I propose to deprecate the inventory extension for two reasons:

1. It is low quality. Well, at least the JS part is pretty low quality IMO.
2. It is just a structure but less powerful. Let's encourage users to use structures instead.

**Comment by 4ian** [comment]
We need more reasons to deprecate something :) It's true that this extension is fairly simple and limited, but it's also doing exactly its job. Nowadays, we would make it an extension in the extension registry I think instead of an extension bundled with GDevelop. This being said:

* Code is fairly old school style, but it's working, [it's tested](https://github.com/4ian/GDevelop/blob/master/Extensions/Inventory/tests/inventory.spec.js), it seems there were no bugs reported about it, it's not a maintenance burden at all (it's happily living since 2 years without any changes, no regressions), there are no obvious performance issues. What is missing can be done with refactorings:
  * Don't like the formatting? Neither I do, run Prettier on it and we're done.
  * Don't like the missing static typing? Neither I do, but feel free to send PR to add `// @ts-check`s
  * Don't like the old school JS? It's a matter of taste, but we can convert it to ES6 + classes, and this can be done fairly safely because we have tests.

Unless I missed something, code is what it should be: simple, boring and tested :) 

* It's true that it's less powerful than a structure, but it's because it's a higher level abstraction. It provides less, but it's easier to use. A structure is something abstract, you have to understand what a child is, how to remove a child, how to check if something is equipped using a "boolean like" variable... 
Inventory is not flexible, and not extendable. In exchange for these limitations, it is quite simple, it does a few things for you (allow to limit the number of items, allow to mark something as equipped).

Finally, remember that marking something as deprecated means that we either have to provide an alternative or a very good reason why it's not available anymore - because we have potential dozens, hundreds, thousands (?) of games and people relying on this feature. 
If a feature is really a nightmare for us, take us time, is badly coded, full of bugs, not working, making users frustrated or even turning them away from GDevelop/giving us bad feedbacks, then I'll be more than happy to just drop this and say "use something else, it's too bad". In all the other cases, deprecating something means that we have to provide an alternative. This could be an extension made using events, registered in the extension registry :) But not sure if it's worth recoding this extension for now - though again please feel free to send PR to improve it! :)
