### ISSUE TITLE
Filesystem wrong description for Filesystem::ExecutablePath()

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2012]
[Original report](https://forum.gdevelop-app.com/t/filesystem-how-do-i-bug-report-feature-request/27933/4?u=bouh)

## Context: 
- The expression `Filesystem::ExecutablePath()` return in preview the current filepath (folders+name of the executable + the extension) of the GDevelop app.

- In an exported/compiled game the expression return the filepath to the current game.

## The issue:

The name of this expression is false, **ExecutablePath** return the path and the exe.
`C:\MyGamePath\MyGame.exe`

![image](https://user-images.githubusercontent.com/1670670/95227898-f3e6aa00-07fe-11eb-87e9-42dd26506e8d.png)

I suggest to rename in **ExecutableFilePath**.
And rework the description.

The main goal behind this was to use the path to the executable, then add another expression for get only the directory without the name and the extension of the executable is needed.

Btw rename the expression can break previous games!

[Original report](https://forum.gdevelop-app.com/t/filesystem-how-do-i-bug-report-feature-request/27933/4?u=bouh)

## Other details
B100, w10

**Comment by 4ian** [comment]
By itself, ExecutablePath is a valid way to say "this is the path to the executable". A path is not necessarily a folder.
It's a bit confusing because other expression like this return a folder path.

Let's first fix the description, as it's clearly wrong! Then we can think of adding `ExecutableFolderPath` expression and/or an helper like `FolderName(...)` or `DirectoryName(...)` that could extract the folder name in a path ;)

**Comment by Silver-Streak** [comment]
I agree with @4ian . Keeping the current expression (but updating the description), and adding another expression of ExecutableFolderPath (or maybe just GamePath?) would be the best way to proceed on this.

No clue on the difficulty of either option, though.

**Comment by 4ian** [comment]
Fixed along with new expressions to manipulate paths, a fix for an expression and a new expression to get the folder (named ExecutableFolderPath) and some TypeScript improvements too (that enabled to find the bug) in 8cd1ea6b735f3b770cf991943295b4fa5bf87f72

> or maybe just GamePath?

Might be risky to use something this short because this may not apply to future platforms (resources and executable could be in a different folder, etc...). For safety, better use long, verbose names like "ExecutableFolderPath" telling exactly what it is about (we can always add simplifications later if it's proven that there is no other concepts or quirks).

**Comment by Bouh** [comment]
@4ian With this it would be fine to refresh the reference function list on the wiki ;)

**Comment by 4ian** [comment]
Right! Refreshing the reference function list should I guess be part of the tasks when releasing a new version.
