### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Noyonika23** [4ian/GDevelop#2016]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in j
    in div
    in r
    in div
    in s
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in E
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in K
    in r
    in t
    in Unknown
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in J
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in ee
    in b
```

## Other details
* IDE version: 5.0.0-beta98-b9ba8e1b7b43f7f56f2fb7696742c604e2d8507d
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.14.6,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta98 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by PawBud** [comment]
@Noyonika23, thanks a lot for reporting this, but this issue is already open [here](https://github.com/4ian/GDevelop/issues/1941), That said, Can you comment the **Other Details** section in the link i provided above(i.e. pls post your IDE, Arch, Platform Name, Sys Ver, User Agent). 
Thanks for using GDevelop :)

**Comment by Bouh** [comment]
Even if this crash is already reported by someone else the report can be different, it's fine to continue to report the crash.

The good pratice is to explain what are you doing just before the crash because the report can't said that.
This is important for reproduce and understand why the app crash.

**Comment by PawBud** [comment]
Sorry about that @Bouh
