### ISSUE TITLE
HTTP 403 - Missing resources in webapp on new examples

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2038]
## Describe the bug
Open a tween example added in b101 on the web app the sprite are not loaded, there is a HTTP 403 code on assets.
## Other details
* b101 webapp

**Comment by Bouh** [comment]
What is the process for update the assets on the webapp.
We have just to [generate the files](https://github.com/4ian/GDevelop/tree/f0392cfede2c8b68b2c9d652001d999eac819299/newIDE#webapp-version) that's all?

**Comment by 4ian** [comment]
Woops I thought the deployment of the web-app included the example resources, that's now fixed and deployed!

> We have just to generate the files that's all?

The deploy script is now launching all the "sub scripts", which includes:
- Building the app itself.
- Pushing the GDJS runtime for this version to the static resource server (resources.gdevelop-app.com).
- Uploading the example resources to the static resource server (resources.gdevelop-app.com) - that was missing.
- Pushing the files of the built app.
- Clearing the Cloudflare cache so that editor.gdevelop-app.com now serves the new version.

Lastly, people launching editor.gdevelop-app.com that already have opened the app will still get the previous version because of the running "service worker" (as it's a "PWA"). After closing the tab, the browser will replace the old service worker by the new, at which point you get the new app (we could include a notification or a button "a new version is available, click here to relaunch and update", but I never took the time to do it.)
