### ISSUE TITLE
UI Add an object in a object group

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2039]
## Describe the bug
When an object is added to an object-group, the object-name is inserted into the input field stay.
We have to delete it before, write another object for continue working.

![image](https://user-images.githubusercontent.com/1670670/96247773-dd80e100-0faa-11eb-8d2e-1f83eb0dd8b0.png)

## Other details
* Since the dawn of time.

**Comment by saideepesh000** [comment]
@Bouh, can I work on this

**Comment by Bouh** [comment]
> @Bouh, can I work on this

@saideepesh000  Yes sure, no need to ask :)

**Comment by saideepesh000** [comment]
@Bouh, Actually I am trying to solve this issue, as per my understanding should I need to make "inputValue" to null, after the event occurs, in the file 'SemiControlledAutoComplete.js'. Am I right.

[SemiControlledAutoComplete.js](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/UI/SemiControlledAutoComplete.js).

**Comment by 4ian** [comment]
SemiControlledAutoComplete is "Semi controlled", which means that it show the value passed as a prop, but while it's focused it's keeping the value entered by the user (allowing to avoid doing a full re-renderer of the whole dialog every time a character is entered, especially useful in larger dialogs and for some text field like when entering a floating point number - where the dot would be discarded if it was controlled (writing `1.` would be reset to `1` for example)).

In this case, I think you would need to use `forceInputValueTo` to reset the autocomplete to an empty string after the objet is added to the group:
https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/UI/SemiControlledAutoComplete.js#L199
https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/ResourcesList/ResourceSelector.js#L136

**Comment by saideepesh000** [comment]
@4ian, hey thanks for your reply, you mean whenever there is an object added to the group in here -> https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/ObjectGroupEditor/index.js#L37-L45
We need to call the forceinputvalue method to reset the value. am I right?

**Comment by 4ian** [comment]
Yes that what I would try! The setState is not sufficient.

**Comment by saideepesh000** [comment]
Hi @4ian, how can we use 'forceInputValueTo' in '[ObjectGroupEditor/index.js](https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/ObjectGroupEditor/index.js#L37-L45)' because it is not the parent of '[SemiControlledAutoCompleteInterface](https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/UI/SemiControlledAutoComplete.js#L188)', as per documentation '[useImperativeHandle](https://reactjs.org/docs/hooks-reference.html#useimperativehandle)' methods are use by parents to use child's functions directly. 

And can you provide me that where is the method 'forceInputValueTo' is used in the components or any other examples in the editor. Sorry for interrupting you, I'am desperate enough to understand the codebase and solve this issue.

**Comment by 4ian** [comment]
You have to add it in ObjectSelector before being able to use it then: https://github.com/4ian/GDevelop/blob/8ba11703e193001b1fdcb683128e38ecbc7f9228/newIDE/app/src/ObjectsList/ObjectSelector.js

> can you provide me that where is the method 'forceInputValueTo' is used in the components or any other examples in the editor.

See second example in https://github.com/4ian/GDevelop/issues/2039#issuecomment-712003179

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
