### ISSUE TITLE
Yarn's night mode resets back to light mode on exit.

### ISSUE THREAD

**Issue by Lochraleon** [4ian/GDevelop#2040]
If you set the Yarn interface to night mode and then exit via the APPLY button. Yarn will not retain the setting and revert back to light mode. 

## To Reproduce
1. Click on the EDIT button and then Create/Edit option on the LoadDialogueFromJsonFile action.
2. Once in Yarn you need to create or open an existing "Node". 
3. While in the Node Text Editor, click the "Night Mode' button found to the left of the Language combo box.
4. Close the Node, click APPLY.
5. Repeat step 1. 

## Other details
I am using the desktop GDevelop 5.0.0-beta101 based on GDevelop.js 4.0.98-0-release

Thanks!

**Comment by 4ian** [comment]
cc @blurymind not sure how Yarn persists its preferences?

**Comment by blurymind** [comment]
The current version uses localStorage to do it, but the one gdevelop is
using is somewhat outdated and might not be persisting it that way.

I need to do a pr to update it as the latest one has lots of bug fixes and
optimisations. It handles big files much better now. Some stuff might not
work due to the way it is bundled still
