### ISSUE TITLE
Invalid rename triggers bugs/crashes on Linux

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2068]
Two users report a similar issue:

https://forum.gdevelop-app.com/t/setting-invalid-title-for-object-causes-my-mouse-to-break/28318
and
https://forum.gdevelop-app.com/t/app-freeze-when-object-name-already-taken/28357/2

I can't confirm the bug on Windows.

**Comment by 4ian** [comment]
Probably only happening on Linux, though I did see once something similar on macOS. The dialog seems to be shown repeatedly, never stopping. I'll take a look.

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/98009201-92adf880-1df5-11eb-8287-95dcc33896c4.png)

**Comment by 4ian** [comment]
I wonder if it's related to the popup being shown by Electron (using the dialog api) in a "blur event". We could work around by adding a "setTimeout" around the call that shows the warning message. This will force the dialog to be shown on the next event loop, when the blur event is processed. Not sure if it will help with the blocked mouse click though, but I hope so.

Yet another solution would be to move away from calling these dialog Electron apis from the "renderer process" (i.e: from the React app), and instead convert them to events that can be called from the renderer process and handled by the Electron main process, so that the dialog are shown from this process - hopefully removing all issues.

But would be great to first see if delaying the display by a single tick is making things better.

**Comment by 4ian** [comment]
Tentatively fixed in ae8a26b3f95d26fcfb74317fba89c87d320985b0
