### ISSUE TITLE
windows compiling using code::blocks , loading GDCore.cbp gives wx error wx/setup.h: No such file or directory

### ISSUE THREAD

**Issue by meiry** [4ian/GDevelop#21]
i download the ExtLib's as suggested by you .  (wxwidgets.7z)
loaded the GDCore.cbp in code::blocks then -> build , 
getting this compilation error:
`||=== Build: Debug - Edittime in Game Develop Core (compiler: GNU GCC Compiler) ===|
d:\dev\cpp\GameDevelop_source\GD\ExtLibs\wxwidgets\include\wx\platform.h |fatal error: wx/setup.h: No such file or directory|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|`

there file is not there , what im missing here ? 
using windows 7 32 bit 
Thanks

**Comment by Think-Jumper** [comment]
WIN10 64bit, I built the project using  CodeLite which making by CMake, but it's something wrong:MESSAGE: Entering directory `F:\Github\4ian\GD\build'
C:\WINDOWS\system32\cmd.exe /C K:/my_dev_env/module_gcc/TDM-GCC-64/bin/mingw32-make.exe -j 16
----------Building project:[ GDevelop - Debug ]----------
current path=F:/Github/4ian/GD/Binaries/Output/Debug_Windows/CppPlatform
Copying GDC++ and extensions to F:/Github/4ian/GD/Binaries/Output/Debug_Windows/CppPlatform...
Copying GDJS and extensions runtime files (*.js) to F:/Github/4ian/GD/Binaries/Output/Debug_Windows/JsPlatform/Runtime...
[  0%] Built target sfml-main
¸´ÖÆÁË 0 ¸öÎÄ¼þ
¸´ÖÆÁË 0 ¸öÎÄ¼þ
[  1%] Built target sfml-system
-- Found Git: H:/Program Files/Git/cmd/git.exe (found version "2.16.2.windows.1")
-- VersionPriv.h already up-to-date.
¸´ÖÆÁË 0 ¸öÎÄ¼þ
¸´ÖÆÁË 0 ¸öÎÄ¼þ
Copied GDJS and extensions runtime files (*.js) to 'F:/Github/4ian/GD/Binaries/Output/Debug_Windows/JsPlatform/Runtime'.
[  1%] Built target GDVersion
[  1%] Built target GDJS_Runtime
[  2%] Built target sfml-network
[  4%] Built target sfml-audio
[  7%] Built target sfml-window
[ 10%] Built target sfml-graphics
¸´ÖÆÁË 0 ¸öÎÄ¼þ
¸´ÖÆÁË 0 ¸öÎÄ¼þ
¸´ÖÆÁË 0 ¸öÎÄ¼þ
¸´ÖÆÁË 0 ¸öÎÄ¼þ
[ 11%] Built target GDIDE_exe
destDir\MinGW32="F:/Github/4ian/GD/Binaries/Output/Debug_Windows/CppPlatform\MinGW32\"
[ 11%] Built target GDIDE_dev_exe
Precompiling headers: GDCpp/EventsPrecompiledHeader.h.pch
[ 21%] Built target GDCpp_Runtime
[ 21%] Linking CXX shared library ..\..\Binaries\Output\Debug_Windows\GDCore.dll
[ 21%] Built target DestroyOutsideBehavior_Runtime
[ 21%] Built target DraggableBehavior_Runtime
[ 22%] Built target CommonDialogs_Runtime
[ 22%] Built target AnchorBehavior_Runtime
[ 24%] Built target Inventory_Runtime
[ 25%] Built target Light_Runtime
[ 25%] Built target Function_Runtime
[ 25%] Built target Box3DObject_Runtime
[ 26%] Built target Network_Runtime
[ 26%] Built target AES_Runtime
[ 26%] Built target AdvancedXML_Runtime
[ 26%] Built target GDCpp_Runtime_exe
[ 27%] Built target LinkedObjects_Runtime
[ 28%] Built target ParticleSystem_Runtime
Done.
[ 30%] Built target PathBehavior_Runtime
[ 32%] Built target PanelSpriteObject_Runtime
[ 33%] Built target PhysicsBehavior_Runtime
[ 34%] Built target PathfindingBehavior_Runtime
[ 34%] Built target GDCpp_IDE_Headers
[ 34%] Built target PlatformBehavior_Runtime
[ 35%] Built target TextObject_Runtime
[ 35%] Built target SystemInfo_Runtime
[ 35%] Built target SoundObject_Runtime
[ 35%] Built target PrimitiveDrawing_Runtime
[ 36%] Built target TileMapObject_Runtime
[ 36%] Built target TextEntryObject_Runtime
[ 37%] Built target TimedEvent_Runtime
[ 38%] Built target TiledSpriteObject_Runtime
[ 39%] Built target TopDownMovementBehavior_Runtime
CMakeFiles\GDCore.dir/objects.a(CommentEvent.cpp.obj): In function `gd::CommentEvent::EditEvent(wxWindow*, gd::Project&, gd::Layout&, gd::MainFrameWrapper&)':
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:55: undefined reference to `wxDialog::ShowModal()'
CMakeFiles\GDCore.dir/objects.a(CommentEvent.cpp.obj): In function `gd::CommentEvent::Render(wxDC&, int, int, unsigned int, gd::EventsEditorItemsAreas&, gd::EventsEditorSelection&, gd::Platform const&)':
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:71: undefined reference to `wxHtmlDCRenderer::SetStandardFonts(int, wxString const&, wxString const&)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:74: undefined reference to `wxColourBase::GetAsString(long) const'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:74: undefined reference to `operator+(char const*, wxString const&)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:74: undefined reference to `operator+(wxString const&, char const*)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:75: undefined reference to `wxColourBase::GetAsString(long) const'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:75: undefined reference to `operator+(char const*, wxString const&)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:75: undefined reference to `operator+(wxString const&, char const*)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:81: undefined reference to `wxHtmlDCRenderer::SetSize(int, int)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:83: undefined reference to `wxHtmlDCRenderer::SetHtmlText(wxString const&, wxString const&, bool)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:84: undefined reference to `wxHtmlDCRenderer::GetTotalHeight() const'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:86: undefined reference to `wxHtmlDCRenderer::SetHtmlText(wxString const&, wxString const&, bool)'
F:/Github/4ian/GD/Core/GDCore/Events/Builtin/CommentEvent.cpp:87: undefined reference to `wxHtmlDCRenderer::GetTotalHeight() const'
.............................................(too many same thing )
and so on.

it seems error in link the wxWidgets libs, and I found the script in "Github\4ian\GD\GDCpp\scripts\CopyHeadersToGD.bat" line24, it's better do "set MINGW_DIR="C:\TDM-GCC-32" because I don't install TDM-GCC-32 in C:\ but in E:\.
