### ISSUE TITLE
8-bit Space Shooter

### ISSUE THREAD

**Issue by asozkdfj** [4ian/GDevelop#2116]
## Describe the bug
Hi
1) I found that when I simulate 8-bit Space Shooter game, spaceship should shoot only while clicking mouse but when 
I press WINDOW BUTTON on the keyboard, spaceship begin to keeping shooting without clicking. Any idea to fix this Bug??

2)Also when I test on mobile there was a screen pushing up or down. If the screen could be fixed it will be better to test game!
![1](https://user-images.githubusercontent.com/72055093/100522005-efc97e00-31ea-11eb-8702-063bcd96a256.jpg)
![2](https://user-images.githubusercontent.com/72055093/100522006-f0faab00-31ea-11eb-8826-b3a8b19738cb.jpg)
![3](https://user-images.githubusercontent.com/72055093/100522007-f0faab00-31ea-11eb-85f7-abc9032eab49.jpg)

1) I tried on web online app
2)I'm using newest version of Iphone 7 and tested on Safari

**Comment by Silver-Streak** [comment]
As this is just an example file, I'm not sure either of these are bugs, just how the example is set up. The engine contributors can confirm if I'm incorrect.

For the first item: This is how GDevelop behaves and not really a bug. If a button is pressed down and the game loses focus (such as with the window key or clicking off the window), the button will act as if it is held down. This actually _couldn't_ be modified before. However, Arthuro555's recent additions allows you to avoid this by nesting your controls in a "window focused" condition. 

For the second item: This is also not really a bug, because it's just how the window scaling/size is set in the example game properties. You can change this by going to the File Menu and then Game Settings menu in the editor, then properties. The Resolution and Rendering section has options around it.

**Comment by Bouh** [comment]
> 1. I found that when I simulate 8-bit Space Shooter game, spaceship should shoot only while clicking mouse but when
>    I press WINDOW BUTTON on the keyboard, spaceship begin to keeping shooting without clicking. Any idea to fix this Bug??

> For the first item: This is how GDevelop behaves and not really a bug. If a button is pressed down and the game loses focus (such as with the window key or clicking off the window), the button will act as if it is held down. 

There is no release of the keys when leaving the window because it was uncomfortable and was therefore[ removed a long time ago.
](https://github.com/4ian/GDevelop/issues/880)

For the second item, refer to the Silver-Streak post above.
