### ISSUE TITLE
Object-related action is not object-bound

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2118]
This action is accessible without selecting an object, yet an object is required.
![image](https://user-images.githubusercontent.com/25978830/100677084-8b352d00-336a-11eb-9dd5-063182cd6efe.png)
![image](https://user-images.githubusercontent.com/25978830/100677279-fd0d7680-336a-11eb-9d6a-583a9c8d97c7.png)

The action itself doesn't mention either that an object is required, so it took me a while to figure out why it wasn't working. (I use the right-click menu)
![image](https://user-images.githubusercontent.com/25978830/100677106-97b98580-336a-11eb-82d4-9ab7a3072dd9.png)

GD5b102

**Comment by 4ian** [comment]
Indeed this was missing and can be fairly frustrating. These actions are a bit of a special case as requiring an object while applying on everything. Not ideal but at least I've fixed the missing object in 1f0165cda74dd9e5510b42eacb4e64a0399c60b1 :) 
Thanks for reporting!

**Comment by PascalLadalle** [comment]
Shouldn't these camera actions be object-bound as well?

![image](https://user-images.githubusercontent.com/25978830/103468359-a4aa0a00-4d58-11eb-9819-2b3a488ee80a.png)

**Comment by 4ian** [comment]
Create an object => It is object bound, but shown here too for making it easier to find. It's an exception.
Create an object from its name => not object bound, because precisely the name of object to create is found according to an expression ;)
Apply movement to all objects => not object bound, because it's an engine feature to move all objects of the scene. There is no object to select.
The camera related actions => not object bound because this is an action of the camera. Sure it asks for an object as a parameter, but this is not a property of the object that is modified - it's a property of the camera (precisely: its X and Y position are modified).

**Comment by PascalLadalle** [comment]
It makes sense, indeed... 
Let's hope it's more intuitive for everyone else than it is for me. 😛
