### ISSUE TITLE
Create object stuck in search bar

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2123]
## Describe the bug
Whenever you research an action and begin the search query with the letter C, the "Create Object" action gets stuck in the list until closing the instruction selector. If you remove your query and type another one in C, it will append another unremovable entry for the "Create Object" action.

## To Reproduce
1. Go to [the online editor](https://editor.gdevelop-app.com/?project=example://flappy-bird) and open any scene.
2. Go on the scene event sheet and click on Add Action... in any event.
3. Type "c" in the search bar.
4. Type backspace to remove the "c".
5. See the bug (The entry for the action remains).
6. Execute 3-5 again to see new entries adding up.

### Video of the issue
https://streamable.com/531tqo

## Other details
* GDevelop beta 102 web-app

**Comment by 4ian** [comment]
Very interesting! Wonder what's causing this ^^ 
This is only using the old action/condition editor right?

**Comment by INNOVATIVEGAMER** [comment]
This bug is not showing in the latest editor.
Also the online editor is ok now.
@arthuro555 you can close this issue.

**Comment by Bouh** [comment]
This still happend, it is only on the old action/condition editor, see in `Project manager>Preferences>Event Sheet`
But the new action/condition editor is now by default, i think we are ready to remove the old editor. What you think about it @4ian ?

**Comment by blurymind** [comment]
I think we should remove the old one? Ehy maintain it anyways?

**Comment by arthuro555** [comment]
I would not agree. Many (if not most) of the community members prefer and still use the old one. If we were to remove it, I think we should ask the community first by making a poll on the forum to vote if we should remove it or not.

**Comment by Bouh** [comment]
A lot of research has been done to have a good average between the old and the new editor.
Like all changes nobody likes them because it changes their habits and then some time later you don't remember the old version.

Make a pool isn't enough, we need a complete feedbacks.
If people stay on the old one, why do they stay on it?
- Something is simpler with the old editor (Details?)
- I didn't understand how it works. (Didn't take the time? What was misunderstood?)

Some little problems are starting to appear with the old editor, and maintaining it while there is a more recent and functional version has no interest if not to please the nostalgic, we must progress.

**Comment by blurymind** [comment]
Is the old one still the default? If so, perhaps a gradual step would be to
set the new one as default for a couple of versions before doing a poll. A
lot if people would use the default for the sake of either not knowing or
prefering the notion that since its a default its probably better

**Comment by Bouh** [comment]
> L'ancien est-il toujours celui par défaut? 
> […]

The new editor is used since[ 5 Oct 2019 on small devices](https://github.com/4ian/GDevelop/commit/c74fbc6c43843ca5d7628957a38a5ee8d3ff676a), and forced for everyone everywhere since [30 Apr 2020 ](https://github.com/4ian/GDevelop/commit/cbad5de1060119be9c0ba975dda92d9dea8e8615).

**Comment by 4ian** [comment]
This new editor is indeed the default since a long time now, it's the one shown when doing a right click, and the only one shown for mobile devices. 
While we've maybe lost the advantage of the search in all conditions/actions at once, the new editor is more scalable, better organized, responsive and I think more intuitive for new users. This is because you either choose an object first (then a "method": an action/condition) or an action/condition. This mimics the way we write code (`object.method(parameters)` or `freeFunction(parameter)`) and is more scalable for objects (we only show actions/conditions that can actually be used).

I think the reason for the old one being still used is just "inertia" and old habits dying hard :) The only advantage (searching in everything at once) could be brought back by improving the search on the new editor.

So overall I think we should remove the old editor.

**Comment by Silver-Streak** [comment]
While I'm a large proponent of the old editor, the general feedback I've seen on the discord (_especially_ from new users):

1. It's not readily apparent that the search DOESN'T search all actions/conditions if they haven't already selected an appropriate object, leading to users thinking something they used before doesn't exist, or not being able to find something new.
2. Because selecting an object is required, search feels not useful or confusing if you're going from the top level.
3. Users feel like it takes more clicks to select a condition or action than the older editor (I'm not 100% sure I agree with this one, but I can see how it could apply in some cases)
4. The old editor feels more aligned with all other lists in the engine, such as the expression builder or variable selector. (This one I do agree with)

All of the above said, I think a good short-term compromise would be to allow the new editor search to search all conditions or actions from the top level without selecting an object. (basically, search returns results like they did in the old editor, but navigating manually allows users to see items as they would with the new editor). 

On a large-term/harder path fowrd, I really think it would be better if you took 3 of the current "selector" methods (Old action/condition editor, new action/condition editor, and the new Extension search) and merged them: 
Allow a full search like the old editor AND
Allow filtering by type like the new editor but on the left bar like in the extension search AND 
Allow for tags to start being added to the actions/conditions/etc that people could search by (or maybe even filter by). 
I expect this one to be a lot more work, but leads to a more uniform design, and potentially the best of both worlds

Super quick mockup:
![image](https://user-images.githubusercontent.com/24237149/104117058-ad17bd00-52e3-11eb-89e8-84a0888a785b.png)

**Comment by 4ian** [comment]
Thanks for the detailed feedback :) 

> It's not readily apparent that the search DOESN'T search all actions/conditions if they haven't already selected an appropriate object, leading to users thinking something they used before doesn't exist, or not being able to find something new.

Fair enough, it's true that it's not obvious and you could expect it to search everywhere - especially because this is the first panel.
I'm less concerned about the two other points that you mentioned (more click: surely a feeling, because you select the object first, less aligned with other lists: that's because it's not really a list).

> All of the above said, I think a good short-term compromise would be to allow the new editor search to search all conditions or actions from the top level without selecting an object

Also agree, that seems the most obvious "feature" that was lost since the update to the new editor. 

So I think I can change the way the search is done so that it's searching in all actions/conditions. If you select an object action/condition this way, the editor will show the object as the first parameter (like in the old editor). It's only when you'll close the editor and open it again that you'll get back to the "canonical" view, where you have the object selected first (and no more "object" parameter).

This should bring the benefits of both world:
- a "quick search" in *everything*, to be sure nothing is missed.
- still a UI that presents object first to help the user learn the distinction between an "object action/condition" and an action/condition unrelated to an object.

> On a large-term/harder path foward, I really think it would be better if you took 3 of the current "selector" methods (Old action/condition editor, new action/condition editor, and the new Extension search) and merged them

So this idea is to have a "library" that is searchable a bit like assets/extensions. It's an interesting idea but I think it would be more something opening when you click a button "Search in the library" or something like that. I like the idea that the current editor is responsive and usable "quickly" for example when you do a right click:

![image](https://user-images.githubusercontent.com/1280130/104123070-31e8f200-5349-11eb-8267-8c2eaefaa3fb.png)

Much like in coding it's fairly fast to do something when you know what you need (just write with your keyboard `myObject.theMethod();`), I want users to be able to quickly do something whenever they know exactly what they want (in the current editor: enter "myObject", press Enter, enter the action name, press Enter).

I'll open a PR with the search being done on all actions/conditions to see how it goes :)

**Comment by arthuro555** [comment]
Anyways, if we're dropping the old editor in a few versions, I'll close this issue as we wont fix the bug. Let's open a new issue for discussing what could be improved on the new editor.
