### ISSUE TITLE
Numpad key inputs are not working at all.

### ISSUE THREAD

**Issue by INNOVATIVEGAMER** [4ian/GDevelop#2193]
## Describe the bug
Numpad key inputs are not working.
On adding any kind of key input with "NumX", action linked to the condition does not get executed. 

## To Reproduce
Just add conditions related to num inputs.

https://user-images.githubusercontent.com/55017197/103985713-717bd680-51af-11eb-9467-b161579bbc50.mp4

**Comment by Bouh** [comment]
This is the expected behavior. In fact you miss `Numpad0` and you use `Num0` which is different.

![image](https://user-images.githubusercontent.com/1670670/104032079-f1b13480-51cd-11eb-90c0-29011c38b922.png)

Also you have all your conditions in one event block without OR condition, this mean all your condition are in a AND state.

Num1.. AND Num2... AND Num3... etc

You should use the OR like this:
![image](https://user-images.githubusercontent.com/1670670/104032351-58cee900-51ce-11eb-8dfd-95d92c570647.png)
