### ISSUE TITLE
Large rotated tiled sprite invisible in editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2212]
Rotated tiled sprites disappear when they're larger than the viewport.
Open the project and zoom in.
[invsiblelargetiled.zip](https://github.com/4ian/GDevelop/files/5817524/invsiblelargetiled.zip)

GD5 beta 103 on Windows 10 64

**Comment by Bouh** [comment]
The preview window takes into account the limits of the blue box when you select the object in the scene.

Since this selection does not take care of rotation and the instances are is hidden when it is outside the preview (+100px margin), the instance disappears.

[This PR will fix this issue](https://github.com/4ian/GDevelop/pull/2017). But it seem the author gone, it was almost finished :/

**Comment by PascalLadalle** [comment]
Yes, the current selection box is not great.

**Comment by Bouh** [comment]
Unable to reproduce in b114
And selection box as been improved by https://github.com/4ian/GDevelop/pull/2751
