### ISSUE TITLE
Noise extension example

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop#2214]
Hi! I made a simple example project that shows how to make a top down procedural generated world. 

  I'd like to submit a new example to be added to GDevelop.
  Here is the link to download it: **[Procedural.Generation.Example.zip](https://github.com/4ian/GDevelop/files/5821101/Procedural.Generation.Example.zip)**.

  I confirm that any assets can be used freely by anybody, including for commercial usage.

**Comment by ssangervasi** [comment]
[Here's an example PR](https://github.com/4ian/GDevelop/pull/2025) that adds an extension example project. It might look like a lot of files, but most of them were touched by [these scripts](https://github.com/4ian/GDevelop/issues/1354#issuecomment-571753219), so it was pretty easy to submit the PR.

**Comment by Add00** [comment]
@ssangervasi are you saying to submit this as a PR? (Sorry for asking a dumb question)

**Comment by arthuro555** [comment]
[Procedural Generation Example.zip](https://github.com/4ian/GDevelop/files/5842438/Procedural.Generation.Example.zip)
I cleaned up the events, adding some more comments, and removing redundant actions.

**Comment by 4ian** [comment]
Thanks @arthuro555 and @Add00 
It seems that in this version, the tiles are all black and white. Is this normal?

![image](https://user-images.githubusercontent.com/1280130/106212429-85b95f00-61c2-11eb-8e33-f78391067fa9.png)

Let's also do two changes:
- unfold all events. It's confusing for new users to have events folded by default when they open an example.
- let's use the mouse button released as the trigger to make a new world, so that it's compatible with touscreens.

**Comment by Add00** [comment]
Thanks for taking the time to review the example. I must have messed something up when uploaded to github since it shouldn't be in black and white. I'll be sure to fix that and implement your other changes.
