### ISSUE TITLE
Possible regression in p2p performance 

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2234]
GDevelop nightly builds
Possible regression in p2p performance or latency?
tested server on local and glitch.com

I updated to nightly builds due to a bug with lights, I wanted to add light blockers but newly spawned lights would crash the game so testing this in stable version wouldn't be one to one the only other thing I added was a shader effect and ping calculations but I have that disabled.

https://www.youtube.com/watch?v=nOxLsbTK3l4

**Comment by 4ian** [comment]
@arthuro555 I don't think there was any recent change to this?

Might be because the handling of the events is done too late, it's a complex topic and it might be a good idea to make your game logic resilient against this?

> tested server on local and glitch.com

Interesting, can you tell more about your usage of glitch.com?

**Comment by arthuro555** [comment]
Well there may have been an unnoticed regression while converting to typescript though I doubt it as I don't see how the changes would impact performance.

The p2p extension do has some issues I was working on locally (the worst one being that the "no data loss mode" handles events Last in First out instead of First in First out) but those issues where present in older versions as well.

**Comment by Entr0py404** [comment]
I am using glitch.com to host the PeerJS server but I also tested locally

**Comment by arthuro555** [comment]
#2238 Just fixed some p2p issues, could you try it and see if you still experience issues? You can find the nightly build [here](https://gdevelop-releases.s3.amazonaws.com/master/commit/0bf6cf204b4f4ebe255ca268800459ed9ce6b990/GDevelop%205%20Setup%205.0.0-beta103.exe).

**Comment by Entr0py404** [comment]
Thank you! @arthuro555
Its something to do with light blockers
https://www.youtube.com/watch?v=QaZGxrSAzq4

**Comment by arthuro555** [comment]
Huh? That's very very weird.
@HarsimranVirk Any idea why the light blocker might delay networking via WebRTC?

**Comment by 4ian** [comment]
The issue might be because the game is slowed down (less frame per seconds) when using light blockers (because of more computation to do, so less frames rendered per seconds), and so your game is handling less events.

Did you try the dataloss mode? It seems that you're sending a lot of events, you might be interested only in the last ones.
A quick description of how you use p2p could help - getting something that is scalable and efficient is not easy.

**Comment by 4ian** [comment]
> Any idea why the light blocker might delay networking via WebRTC?

We need more information, about how the game logic is constructed before inferring any correlation. It would be good to see all the events handling the update of the object positions :)

**Comment by arthuro555** [comment]
Ah yes sorry for my hasty conclusion. It might also help to try using this to see if it resolves problems: https://github.com/4ian/GDevelop-extensions/pull/100

**Comment by Entr0py404** [comment]
Player positions
![Screenshot 2021-01-25 054105](https://user-images.githubusercontent.com/75917656/105707532-53f97d00-5ed0-11eb-95df-4bd4b44a1982.png)

Shooting
![Screenshot 2021-01-25 054321](https://user-images.githubusercontent.com/75917656/105707566-5fe53f00-5ed0-11eb-90b9-1a93268d7aec.png)
![Screenshot 2021-01-25 054243](https://user-images.githubusercontent.com/75917656/105707567-607dd580-5ed0-11eb-9467-2e913ebff78a.png)

**Comment by Entr0py404** [comment]
https://www.youtube.com/watch?v=3ktr--MH3cs

**Comment by 4ian** [comment]
> You might want to try using this to see if it helps with the problem (as it helps processing more events per frame): 4ian/GDevelop-extensions#100

It's definitely interesting!

> Player positions

Make sense thanks! This is sending the player position at every frame, so between 60 and 120 times a second, which I think might be filling the network - could you try spacing a bit in time each event?
