### ISSUE TITLE
Extensions objects

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2255]
## Description

When making a complex object, linking objects is often fine. But it isn't scalable and gives a pretty poor user experience.

## Solution suggested

Add to extensions the capability of making custom objects. A custom object would be kind of like a React component: it is constituted of one or multiple default or custom objects, and can be then used as a normal object.
Each objects would have functions for the functionality, similar to a behavior, and a layout, similar to an external layout, for the rendering. 

## Implementation details

Internally, the objects in the custom object would be treated normally, but instead of being put in the layer container, they are put in a container that is the actual object, and they are not accessible from the scene but from the `eventsFunctionContext`. 
This should be probably further discussed before beginning any work on implementing this.

## Implementation possibilities

- Hitboxes
  - [ ] Use a rectangle around all objects as hitbox
  - [ ] Collision check with all user selectionned child objects

## Mockups

![image](https://user-images.githubusercontent.com/19349038/106452332-02309400-6488-11eb-8cd4-0306356a63e8.png)
![image](https://user-images.githubusercontent.com/19349038/106453552-c991ba00-6489-11eb-997c-e1e9027bd3a3.png)
![image](https://user-images.githubusercontent.com/19349038/106453946-5b012c00-648a-11eb-9544-134c1ae8b968.png)

**Comment by 4ian** [comment]
This is more or less related to this: https://trello.com/c/6RGVk9Zg/446-add-objects-that-can-be-containers-for-other-objects-nodes-composite-objects-sub-objects

It would be interesting to think about how flexible this could be: how could we easily move from an object in the scene editor to an object in an "extension".
For a large game, it would also be interesting to see if we can organize somehow these objects.

There is also some architectural decision to be done: 
- do we use a Pixi container?
- do we store objects inside other objects, or do we try to keep a flat list of objects? 
  - It might sound obvious to treat "composite objects" as an object "containing others", but from a "data driven design" point of view, it might be more performant to keep everything in the game engine in a flat list of objects.
- in theory these custom objects would have behaviors that can be added to them. Would we also be able to specify some mandatory behaviors? Or some incompatible behaviors? 
- is this linked to a notion of "prefab"? (cc @Bouh that told a bit about it, but might be a different notion)
- how do we handle resources for these objects?

This can be a very very interesting, and at the same time very complex project - and we would need to strike the good balance between:
- best performance possible (avoid any slow down because of complex object hierarchy/graph)
- as easy as possible to author. You don't want to spend too much time to move your 2 or 3 objects into a custom object. You want to design something that is so intuitive that you can turn a few objects into a "custom object" very easily.

Finally, note that there is also a request to more simply "link" objects to another (when a parent object is moved, children follow it, like the weapon of a character, or its equipment, etc...). This could be done with custom objects (and is surely the best solution), but would there be a way to easily do this? 

Finally (again), would custom objects be able to contain... other custom objects? 
In theory: hell yes.
In practice: same concerns about: 1) making this performant and 2) making this intuitive, fast, seamless to use.

This last remark goes in the way of "nodes" (like Godot) (but reusable nodes) and also tends to make scene "something that is basically a huge custom object, with events and no behaviors by itself". But this is going a bit far, let's try to keep our feet on the ground ;)

**Comment by arthuro555** [comment]
> in a flat list of objects

🤔 Wouldn't that introduce conflicts to the object names? Sound like a lot of problems for not much in exchange.

> in theory these custom objects would have behaviors that can be added to them. Would we also be able to specify some mandatory behaviors? Or some incompatible behaviors?

I think it should be handled like any other object: if the extension says it supports any object, it should also support custom objects. Else's it uses object specific features and should be âneries as working only with this object.

> how do we handle resources for these objects?

I don't see why ressources should be handled another way?

> This can be a very very interesting, and at the same time very complex project - and we would need to strike the good balance between

Agreed, though I am not sure how many possibilities of implementing this there are.

> to make scene "something that is basically a huge custom object, with events and no behaviors by itself"

Personally, i think that would be unnecessarily complex and would make the learning curve much more complex and GDevelop more unintuitive to use.

**Comment by 4ian** [comment]
> 🤔 Wouldn't that introduce conflicts to the object names? Sound like a lot of problems for not much in exchange.

It would be done so that there is no conflict (just by using a convention like generate a name that is prefixed by the parent object name and a dot, or slash, etc...).

This could help keeping all objects of the same type is the same array, and when iterating on objects to update them, it's faster for CPUs to iterate on objects of the same type, because you can take advantage of CPU caches: in a traditional, naive "scene graph", if you go from a Sprite object, to a text object, to another sprite object, to a shape painter object, the CPU has to load in its cache the data and instructions from different part of the memory, doing a lot of cache trashing.
Conversely, if you group things of the same "type" together, you *might* get an improved.

I really recommend this very nice article: https://gameprogrammingpatterns.com/data-locality.html (and actually the whole book, it's amazing and very well explained! A pleasure to read). Take 20 minutes to read it, you might understand a bit better the idea (that could be applied to behaviors too by the way). Note that in JavaScript, we don't have a lot of way to influence how things are laid out in memory, but still.

> Personally, i think that would be unnecessarily complex and would make the learning curve much more complex and GDevelop more unintuitive to use.

Sure, I think we should start with a clear use case, and be sure we have all the UI mockups/ideas to be sure it will be easy to understand - and actually useful!

> I don't see why ressources should be handled another way?

Objects are supposed to expose their resources, so custom objects might have to expose the resources of their inner objects. Just a detail but still.

**Comment by Bouh** [comment]
>is this linked to a notion of "prefab"? (cc @Bouh that told a bit about it, but might be a different notion)

Kind of.
Objects from extension is a great idea!

>do we use a Pixi container?

Yes, we need a PixiContainer on the scene editor for the end user.
No need to make selectable a child of a parent if the parent object come from an extension.
This is important to avoid that users easily delete a child object that would break the internal logic of the prefab.
Child objects would only be editable in the extension.

<details >
  <summary>Fr</summary>
Oui il faut que sur l'éditeur de scène pour l'utilisateurs final on ai que un PixiContainer.
Pas besoin de rendre selectionnable les objets enfant si l'objet parent provient d'une extension.
C'est important pour pas que les utilisateurs suppriment facilement un objet enfant qui casserait la logique interne du prefab.
Les objets enfant seraient éditable seulement dans l'extension.
</details>

![image](https://user-images.githubusercontent.com/1670670/106542053-63497d80-6503-11eb-89a8-f0b7b09469e7.png)



>do we store objects inside other objects, or do we try to keep a flat list of objects?

Our goal is to have multiple objects that depend of another.
So we have child objects and parent(s).
With this we keep a flat structure.
And with this parenting system we would finally have a way to "group" in the list of objects.

<details >
  <summary>Fr</summary>
Le but ici est d'avoir de multiple objets qui dépendent d'un autre.
Donc on a des objets enfant et un/des parent(s).
L'idée est donc d'avoir des objets qui en contiennent d'autres, on peut l'avoir avec un syteme de parent. 
Avec ça on garde une structure plate.
Et avec ce system de parent on aurait enfin un moyen de "groupé" dans la liste des objects.
</details>

![image](https://user-images.githubusercontent.com/1670670/106542006-4ad96300-6503-11eb-8f4d-d050a9896142.png)


>how do we handle resources for these objects?
Based from extensions that are a json file. The images would have to be compressed into text in the extension file to keep everything portable.
Otherwise the format of the extensions have to be changed to a container.
With a container the resources would be copied into the main project. (In a sub-folder so that one knows where the resources come from).

<details >
  <summary>Fr</summary>
En partant du principe que les extensions sont un fichier json. il faudrait que les images soient compressé en texte dans l'extension pour que tout reste portable.
Sinon on change le format des extensions pour un conteneur.
Avec un conteneur on irait copié les resources dans le projet principal. (Dans un sous-dossier pour qu'on sache d'où viennent les resources)
</details>

**Comment by arthuro555** [comment]
🤔 The biggest problem I can think of with a flat data structure is deleting an object. If I delete the main custom object, and it doesn't know it's children, then we have to iterate over *all objects* to find the children, which makes deleting very expensive :/

> Based from extensions that are a json file. The images would have to be compressed into text in the extension file to keep everything portable.

Personally, I'd store them as URLs. I am not a big fan of putting all resources as data URLs in a JSON, that sound like it would make those way too heavy and conflicts way harder to resolve if one uses extension objects in their project versioned with git. But I also see how this would be useful. Maybe we can make extensions actually zip files with the ressources and the JSON when exporting it? That would make the main "code file" easier to maintain and still be able to pack the extension with resources for export.

> do we use a Pixi container?

I think that would be the most performant and functional way. This would allow us to use those as really any other objects, as all pixi main features are present on containers, like object effects (when they are added).

**Comment by 4ian** [comment]
I think there was some confusion about the flat datastructure. It is *at runtime*, in the game engine, not in the editor.
Just an implementation detail anyway, for now.

A pixi container is fine for implementation for the pixi renderers.

> If a user click on a child from the object list, a popup appear for ask if he want really open up the object editor from the extension.

Yes that's a great idea.

I also think of something like: 
- you select a few instances on the scene, and can choose "Group in a custom object", 
- This would extract the selected instances, put them in a custom object, remove the objects from the scene and finally replace the "main object" that you select by this custom object (and replace any remaining instances on the scene by it too).

So that you can quickly go from prototyping stuff on the scene to a custom object. Maybe events should be transferred automatically too, though hard to see exactly how.

> Maybe we can make extensions actually zip files with the ressources and the JSON when exporting it? That would make the main "code file" easier to maintain and still be able to pack the extension with resources for export.

Yes for export I think it's preferable to use zip files in case we need to bundle some extension json + resources.
Export would work as now, but in addition to "simply" saving the extension as a file, it would also iterate on object exposed resources (much like when you click on save as for a project) (and possibly we would zip the whole thing).
It also means that importing the extension would add these resources to the project - a bit like what is done for the assets store.

There are also other questions about usability of this concept:
- Let's say that I have two sprites that I want to turn into a custom object, because these sprites are working together (it's a character and its weapon for example, and maybe an invisible collision box). I also use the actions to change the sprites tint. Now that I have a custom object, I add an action to change the custom object tint (this custom action is launching the actions to change the sprite tints on the two "child" objects). So far all good! Now if I need to re-do this for other objects (create a custom object, add an action to update the sprite tint), it's starting to be a bit cumbersome... Should somehow some actions/conditions be "transferred" from the child object types to the custom object?
-  For collisions, should the hitboxes be a merge of the child object hitboxes? Probably not all, there should be a way to mark the objects to use as hitbox.

**Comment by arthuro555** [comment]
> Should somehow some actions/conditions be "transferred" from the child object types to the custom object?

I cannot see any way to cleanly do that. Technically we could copy all events that use the object, but how can we now if those events don't depend on an event that doesn't use those objects? 

> For collisions, should the hitboxes be a merge of the child object hitboxes? Probably not all, there should be a way to mark the objects to use as hitbox.

Good point, I'd also let the user select the object whose hitboxes should be used.

> I think there was some confusion about the flat datastructure. It is at runtime, in the game engine, not in the editor.

Yes, I meant instances deletions at runtime, not in the IDE.

**Comment by 4ian** [comment]
> Technically we could copy all events that use the object, but how can we now if those events don't depend on an event that doesn't use those objects?

Not sure I followed everything 😄 There is maybe no easy answer, but we should really think about the speed of creation of these custom objects. Of course if you're designing a reusable checkbox object extension, you don't care that much about existing events (on the contrary, you want to expose only a few set of actions/conditions to manipulate your checkbox), but when you're working on a game and want to "group" all the objects of your player in a custom "Player" object, it will be much less cumbersome if the transition is easy.

> Yes, I meant instances deletions at runtime, not in the IDE.

That's not a problem, you can still keep references to your child objects in your object. It's just that the scene would group them in an array of the same object types (hoping that it could be stored contiguously in memory). That's a detail anyway.

**Comment by Bouh** [comment]
>1. you select a few instances on the scene, and can choose "Group in a custom object",
>2. This would extract the selected instances, put them in a custom object, remove the objects from the scene and finally replace the "main object" that you select by this custom object (and replace any remaining instances on the scene by it too).

Great idea. This could be added later.

>So that you can quickly go from prototyping stuff on the scene to a custom object. Maybe events should be transferred automatically too, though hard to see exactly how.

>Not sure I followed everything 😄 There is maybe no easy answer, but we should really think about the speed of creation of these custom objects. Of course if you're designing a reusable checkbox object extension, you don't care that much about existing events (on the contrary, you want to expose only a few set of actions/conditions to manipulate your checkbox), but when you're working on a game and want to "group" all the objects of your player in a custom "Player" object, it will be much less cumbersome if the transition is easy.


Let's keep this for later because many scene and global variables are used by users to act indirectly on objects.
Exporting objects and their events is too complex.

Creating a custom object with a selection of objects will never be as advanced as doing it directly in the object editor.
One can forget for now the functionality to extract events associated with the objects.

The extract for events to a function was good because we were based on a selection of events made by the user, he is supposed to know what he is exporting.
If a bad export of objects and their supposed events it is done incorrectly it will be a waste of time for the user to checking what wrong with it.
We should not propose a functionality that would only export part of the events.

I think it's cool to have such a feature but we'll be able to think about it once we've thought about an object editor and the technical constraints it brings to us.


Is possible to edit the first post for list the contraints to solve?
- How manage the resources in an extension. (e.g: Sprite for objects)
- How rendering the custom objet on scene? (in a PixiContainer)
- How handle the hitboxes?

For hitboxes we should use by default the bbox of the custom object (PixiContainer).
If we have custom hitboxes in child objects we iterate on all theses hitboxes.

**Comment by arthuro555** [comment]
The way I see a generated object is pretty much something like this:
```js

gdjs.evtObjects.objectName = function(runtimeScene) {
  gdjs.RuntimeObject.apply(this);
  this._renderer = new PIXI.Container();

  // Initialize child objects
  this._object_Slime = [new gdjs.SpriteRuntimeObject(runtimeScene, runtimeScene.getGame().getGameData().extensions.extensionName.ObjectName.initialInstances.Slime1).setContainer(this._renderer)];
  this._object_Name = [new gdjs.TextRuntimeObject(runtimeScene, runtimeScene.getGame().getGameData().extensions.extensionName.ObjectName.initialInstances.Name1).setContainer(this._renderer)];
  this._object_Collision = [new gdjs.SpriteRuntimeObject(runtimeScene, runtimeScene.getGame().getGameData().extensions.extensionName.ObjectName.initialInstances.Collision1).setContainer(this._renderer), new gdjs.SpriteRuntimeObject(runtimeScene, runtimeScene.getGame().getGameData().extensions.extensionName.ObjectName.initialInstances.Collision2).setContainer(this._renderer), new gdjs.SpriteRuntimeObject(runtimeScene, runtimeScene.getGame().getGameData().extensions.extensionName.ObjectName.initialInstances.Collision3).setContainer(this._renderer)];
}

gdjs.evtObjects.objectName.prototype = Object.create(gdjs.RuntimeObject.prototype);

gdjs.evtObjects.objectName.preObjects = function() {
  //evt sheet code
}

gdjs.evtObjects.objectName.postObjects = function() {
  //evt sheet code
}

gdjs.evtObjects.objectName.update = function(runtimeScene, renderContainer) {
  this.preObjects(runtimeScene);
  this._object_childObjectSlime.forEach(o => o.update(runtimeScene);
  this._object_childObjectName.forEach(o => o.update(runtimeScene);
  this._object_childObjectCollision.forEach(o => o.update(runtimeScene);
  this.postObects(runtimeScene);
}

gdjs.evtObjects.objectName.getRendererObject = () => this._renderer;

// Mimic an object context
gdjs.evtObjects.objectName.getObjects = function(name) {
  if(name === "Slime") return this._object_Slime;
  if(name === "Name") return this._object_Name;
  if(name === "Collision") return this._object_Collision;
}
```

Here, there is a new `setContainer` method on the `gdjs.RuntimeObject`, which forces the PIXI container to another than one from a layer, which could look like this:

```js
setContainer(container) {
    if(!this.isInCustomContainer) this._runtimeScene.getLayer(this.layer).removeRendererObject(this.getRendererObject());
    else this.container.removeRendererObject(this.getRendererObject());
    this.container = container;
    this.container.addRendererObject(this.getRendererObject());
    this.isInCustomContainer = true;
}
```

This is not a thoroughly thought out sketch, please don't hesitate to criticise everything out of it.

**Comment by 4ian** [comment]
Overall yeah that's the idea! :)
nitpicking: `preObjects`/`postObjects` => `preObjectUpdates`, `postObjectUpdates`.
As you found out with setContainer, objects are currently made to be directly used in a `runtimeScene`. It might be worth refactoring gdjs.RuntimeObject so that they have 1) still access to runtimeScene but 2) and a `container`, used as much as possible - without special case `if`. 

(in other words, I would architecture things so that instead of:
```js
if(!this.isInCustomContainer) this._runtimeScene.getLayer(this.layer).removeRendererObject(this.getRendererObject());
    else this.container.removeRendererObject(this.getRendererObject());
```

we do just:
```js
// this._container is set by the parent, i.e: either the runtime scene or the parent object.
this._container.removeRendererObject(this.getRendererObject());
```

This might need to introduce an interface `gdjs.RuntimeObjectContainer`, which could be implemented by runtime layers and by runtime objects (not sure, just thinking about this now).

**Comment by arthuro555** [comment]
I have a question, what APIs belongs in an "objects context" (I guess that is how it is called? I am speaking about runtimeScene/eventsFunctionContext) and where is it defined in the code generator? It would be useful to know to see what the object would have to implement to let itself be used as one (if that is the right way to go).

**Comment by 4ian** [comment]
I think you mean this:
https://github.com/4ian/GDevelop/blob/30aa5e78fd05b1f84979a2427955862914661ac8/GDJS/Runtime/types/global-types.d.ts#L13-L44

and it's generated here:
https://github.com/4ian/GDevelop/blob/30aa5e78fd05b1f84979a2427955862914661ac8/GDJS/GDJS/Events/CodeGeneration/EventsCodeGenerator.cpp#L214-L351
