### ISSUE TITLE
Spawning light object

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2261]
The light object spawns at 0,0 for the first frame on creating a light in events

Lighting layer is using "Automatically follow the base layer" option

https://puu.sh/Hd1rM/0fd1f1265f.webm

Windows 10
GDev Preview 104 beta

**Comment by 4ian** [comment]
@HarsimranVirk let me know if you have an idea about this :)

**Comment by HarsimranVirk** [comment]
@4ian I guess the major reason is that the first frame takes a considerable amount of time, one workaround is to not show the object in the first frame, but for this, we'll have to do a check in the `update()` function (also the check would be performed unnecessarily all the time later).

**Comment by 4ian** [comment]
Not sure I really understand, because even if the first frame would take a few more micro/milliseconds to render, it should still show the object at the proper position?

**Comment by 4ian** [comment]
@Entr0py404 Anyway you can make a game to reproduce the issue on a minimal game with just light objects (and a few obstacles if needed)? Would be easier to debug.

**Comment by Entr0py404** [comment]
[LightExample.zip](https://github.com/4ian/GDevelop/files/5951117/LightExample.zip)

**Comment by HarsimranVirk** [comment]
> even if the first frame would take a few more micro/milliseconds to render, it should still show the object at the proper position?

I'm not sure about this either, I've checked the sequence of function calls to determine the `x` and `y` positions of the object. It's (0,0) in the constructor, then `ensureUpToDate()` is called, and after that `setPostition()` is called which finally changes `x` and `y`. Also, I'm not sure whether we can alter this sequence or not 🤔 (maybe like calling the constructor with the proper positions in the first place).

**Comment by 4ian** [comment]
So the issue is that `ensureUpToDate` is called only before the events, through the call to each object `update` method.
If position is changed (or the object created, then position changed, like in this case) in between, the object is at the wrong position for one frame.
The solution? Usually for other objects, when the position is changed we also call the renderer to change the position of the associated Pixi object.
Lights are more complex because they used the obstacles around to compute the vertices, so it's very costly and should be done at most once per frame. 
We might need to add a `updateBeforeRender` method `gdjs.RuntimeObject` and call it on all objects in gdjs.RuntimeScene, in something like `_updateObjectsVisibility`. This is typically the kind of object that need it - and `update` is the wrong place to do it.

Note that for other objects we want to avoid using this most of the time because we don't need to make anything if nothing (position, etc...) is changed.

**Comment by HarsimranVirk** [comment]
> We might need to add a updateBeforeRender method gdjs.RuntimeObject and call it on all objects in gdjs.RuntimeScene, in something like _updateObjectsVisibility. 

Should it be done in `_updateObjectsVisibility` or `_updateObjectsPostEvents`? I'm not sure what is `gdjs.callbacksRuntimeScenePostEvents` and whether it would have an effect or not.

**Comment by 4ian** [comment]
`_updateObjectsVisibility`. 
`_updateObjectsPostEvents` is really about doing things *after* the events, but it's not a guarantee that it will run *before* the rendering... which means that things like the `callbacksRuntimeScenePostEvents` callbacks that you mentioned could do anything (including moving) the objects (and it's fair!). Basically, `_updateObjectsPostEvents`/`callbacksRuntimeScenePostEvents` are about running **logic** after the events.

I think we should also rename `_updateObjectsVisibility` to `_updateObjectsPreRender` to make it explicit it's about rendering (so it updates visibility and then do anything needed for each object), so we can run `updatePreRender` (I changed my mind from naming it `updateBeforeRender`, because `pre`/`post` are already used in the codebase).

**Comment by 4ian** [comment]
> [LightExample.zip](https://github.com/4ian/GDevelop/files/5951117/LightExample.zip)
> 
> Using the enemy for spawn position for the light does the same thing
> ![Screenshot 2021-02-09 052518](https://user-images.githubusercontent.com/75917656/107363554-8e9a1280-6a97-11eb-961d-9eeb8bbde350.png)

Verified that it works with the fix, thanks for making the demo game and thanks @HarsimranVirk for the fix :)
