### ISSUE TITLE
Separate action applied multiple times

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2281]
It seems that the action "move A away from B" applies repel force to A for each instance of B.

https://user-images.githubusercontent.com/25978830/107097876-41574000-680e-11eb-830c-7c0f26337f90.mp4

![image](https://user-images.githubusercontent.com/25978830/107097967-66e44980-680e-11eb-8d97-c2105a3ffd5c.png)
![image](https://user-images.githubusercontent.com/25978830/107097988-706db180-680e-11eb-8abc-9ef51d86ec5e.png)

On a side note, shouldn't the action phrase be consistent with the action label?
![image](https://user-images.githubusercontent.com/25978830/107098065-aad74e80-680e-11eb-9d91-f379cf0d17f3.png)

GD5b104

**Comment by 4ian** [comment]
That's indeed a behavior less than ideal. This is because each object around the moving object (here the player) is checked for collision. Then, each of them will gives back a vector to separate the moving object out of the collided object.
This works well when objects are not on the same axis: 
![image](https://user-images.githubusercontent.com/1280130/107101274-b591e380-680e-11eb-8184-aa60af3e772e.png)

But objects that return a vector on the same axis will get them added:
![image](https://user-images.githubusercontent.com/1280130/107101320-d5290c00-680e-11eb-87d8-a0381e3a6ea1.png)

Instead we could project each vector on the axis and only keep the longest:
![image](https://user-images.githubusercontent.com/1280130/107101437-3d77ed80-680f-11eb-989f-35015a2e6eca.png)

But not sure this would work for things that are not axis aligned, for example this:
![image](https://user-images.githubusercontent.com/1280130/107101671-00f8c180-6810-11eb-89f1-158966dc0cb6.png)

Seems like there is no obvious solution, but something to look at more in depth: https://gamedev.stackexchange.com/questions/68486/separating-axis-theorem-with-multiple-polygons

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
