### ISSUE TITLE
Games not working anymore on KaiOS

### ISSUE THREAD

**Issue by Sekuta82** [4ian/GDevelop#2290]
There are some loops using const variables that will cause issues.
Const variables cannot be re-assigned.

https://github.com/4ian/GDevelop/blob/d9862648d9e2be22812c1ee07f72a2e3f1de2886/GDJS/Runtime/libs/jshashtable.ts#L88

**Comment by 4ian** [comment]
Have you tried running a similar code to check if it works? ;)

**Comment by 4ian** [comment]
To be clear, this is supposed to work. MDN lists this in examples: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#using_for...in

This may not work in older browsers, but in this case we would recommend upgrading browsers rather than staying on outdated browsers that are also surely not the best in terms of performance or that would fail on other more complex use cases :/

**Comment by Sekuta82** [comment]
It's not working on KaiOS, which basically is an old firefox browser :)

**Comment by 4ian** [comment]
That's a bummer :/ I guess there is no more updates for it?

**Comment by zendrael** [comment]
KaiOS is a direct descendant of FirefoxOS (now defunct) and besides releasing lots of mobile "feature phones" and receiving investment from google, there are no updates on the gecko engine for it.

**Comment by Sekuta82** [comment]
KaiOS 3, based on a modern Firefox and updated b2g has been announced but it might still take a year to be released.

**Comment by zendrael** [comment]
They say that there are already millions of KaiOS devices sold - I'm not sure that all of them will be updatedable.

**Comment by Sekuta82** [comment]
No, they won't be updated. FF 48 returned from the dead and won't be leaving any time soon  :)

**Comment by 4ian** [comment]
So we're stuck with a 4 years old Firefox :/ 
One possibility would be to run the generated game Javascript files through babel (https://babeljs.io/), to convert all the new syntax to Firefox 49-compatible syntax. This is something that we avoid doing by default in GDevelop because it's additional slowness/complexity for the build and can trigger de-optimization in modern JS engines.

**Comment by zendrael** [comment]
> So we're stuck with a 4 years old Firefox :/
> One possibility would be to run the generated game Javascript files through babel (https://babeljs.io/), to convert all the new syntax to Firefox 49-compatible syntax. This is something that we avoid doing by default in GDevelop because it's additional slowness/complexity for the build and can trigger de-optimization in modern JS engines.

Using Babel seems a way to go, will add one more step when testing on device but is a way to go for sure. Thanks!

**Comment by 4ian** [comment]
I think it's something that was used by someone to keep compatibility of a generated game with IE 11 (though I can't make *any* promise that something else will work... hopefully FF 49 was good enough apart from this).
You might have to make a script to run babel on all the JS files, then hope it's enough (should be good if you ask babel to translate everything to "ES5").

If it works, we could document this in a wiki page I think :)

**Comment by Sekuta82** [comment]
That's good enough for me, if it's just being mentioned somewhere, that it's compatible with KaiOS 2.
I'm actually not using this software mayself. Another dev told me that it didn't work anymore and I looked into it.
