### ISSUE TITLE
Add support for additional variable types when using "For each child variable (of a structure)"

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#2307]
## Description

The new "For each child variable (of a structure)" function works only when using a single-level, scene, structure variable.  

This function does not seem to use other types of variables, including:

- Object variables
- Multi-level variables (grandparent.parent.child)
- Global variables

This request is to add support for these types of structure variables.
 
## To Reproduce

1. Create a structure variable from the list above 
2. Create a "For each child variable (of a structure)" event
3. Create a sub-event that changes the background color (this simply confirms that the ForEach() loop was entered)
4. Preview the game and see if the background changes

## Other details

* Tested on GDevelop beta 105

## Example game
[ShadowClone8.zip](https://github.com/4ian/GDevelop/files/5979792/ShadowClone8.zip)

## Screenshot

![Screenshot 2021-02-14 231619](https://user-images.githubusercontent.com/8879811/107911888-ad2a5e80-6f1a-11eb-8627-13a794c7dd3c.jpg)

**Comment by 4ian** [comment]
That's indeed an unfortunate limitation. Duplicating the event for each variable kind if unfortunately not a viable option (nor a good user experience anyway!). 

Instead, I think this is part of a larger refactoring/reworking of how variables work to introduce a new `variable` parameter type, that would allow any variable to be entered using an expression: an object variable, a scene variable, or a global variable. Or later an extension variable, or a local temporary variable.

With this support for "expressions" that return variables, we would easily be able to use any kind of variables with the for each event, and also the action/condition that use variables, like the ones to transform a variable from/to JSON. See this card that I made on the roadmap: https://trello.com/c/FwShg063/487-add-support-for-a-generic-variable-parameter-that-would-allow-to-choose-any-variable-object-variable-scene-global-extension-vari

cc @Bouh, @arthuro555 so that you know about the plans of this in the long term.

**Comment by arthuro555** [comment]
Yes, this was mentioned multiple times and is in my opinion really needed. It will also help with avoiding mistakes as currently we have to declare one instruction for each variable type 😬 
Would this be a good GSoC project idea? Maybe it is a bit too big?
