### ISSUE TITLE
Web request error string returning function name from engine

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#2449]
![Screenshot 2021-03-19 042012](https://user-images.githubusercontent.com/75917656/111772877-9ef99600-886a-11eb-9043-de3b3722fed5.png)

also the first web request takes the longest and maybe more time then it should ?
(after the first request, request responses are faster for any host)
in the .net framework if you don't set proxy to null or other it will try to autodetect proxy settings taking longer not sure if that could be a case here.

GDevelop version: 106 on desktop
OS: Windows 10

**Comment by Bouh** [comment]
For me on exported game online:
![image](https://user-images.githubusercontent.com/1670670/111883156-e5113f80-89b9-11eb-8482-34cec1c44dc7.png)
and
![image](https://user-images.githubusercontent.com/1670670/111883163-ee9aa780-89b9-11eb-9dbb-77422f34da1f.png)
Otherwise it work like a charm in the preview.

**Comment by Entr0py404** [comment]
I was aware of the cors error, my issue with the error message, is it's the same message when you have no internet connectivity, and possibly other errors?

**Comment by Entr0py404** [comment]
I guess this is another scraped game made with gdevelop
good for making prototypes bad for making games..

**Comment by 4ian** [comment]
So the problem here is the "[object ProgressEvent]" right? Looks like a fairly simple mistake in the engine when sending a request, should not be too hard to fix :)

**Comment by AlexandreSi** [comment]
@Entr0py404 I had a look on this issue: it looks like it's a big difficult to detect that request couldn't even be sent (see https://stackoverflow.com/questions/872206/what-does-it-mean-when-an-http-request-returns-status-code-0/14507670#14507670)

So I suggest that we return a constant string if we detect that we are in the case "request couldn't be sent", whatever reason is the root cause (as listed by the SO answer).
At the moment in the #3515 PR, the string is `UNDEFINED` but it's maybe not clear enough, it could be mistaken for an error response from the server. Maybe `REQUEST_NOT_SENT`

**Comment by AlexandreSi** [comment]
![image](https://user-images.githubusercontent.com/32449369/150179926-da474839-0ff4-4f66-b524-6afe99555adc.png)
