### ISSUE TITLE
b106 - Structures with "-" in the name create fatal error

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#2457]
## Describe the bug
If you have a global variable structure with a "-" dash in the name and you try to clear the children of of that structure then you will be unable successfully start a preview.  The following can be seen in the console log:
```
commontools.ts:129 Uncaught TypeError: variable.clearChildren is not a function
    at Object.common2.variableClearChildren (commontools.ts:129)
    at Object.gdjs.New_32sceneCode.eventsList0 (code0.js:17)
    at RuntimeScene.gdjs.New_32sceneCode.func [as _eventsFunction] (code0.js:29)
    at RuntimeScene.renderAndStep (runtimescene.ts:466)
    at SceneStack.step (scenestack.ts:36)
    at runtimegame.ts:546
    at gameLoop (runtimegame-pixi-renderer.ts:520)
```

## To Reproduce
On scene start -> Clear the children of "levels.1-1"
[DashCharStructureBug.zip](https://github.com/4ian/GDevelop/files/6176586/DashCharStructureBug.zip)
I included a console.log dump in that zip as well.

*This is a regression in b106 and has not been seen in the past*

## Other details
* GDevelop 5.0.0 b106

**Comment by krunkster** [comment]
I've figured out a workaround, which is to just change the reference format to enforce the fact that the "key" is a string:
levels["1-1"]
The IDE autocompletes to the "level.1-1" as a valid reference, and that did work before b106.
I'm not sure if the new arrays/typing logic changed that.

I also noticed that following oddness:
levels[1-1] -> levels.0 (it does the math apparently)
levels[A-1] -> ERROR (same as original above)

Here's a new example that might help if anything is confusing:
[DashCharStructureBug.zip](https://github.com/4ian/GDevelop/files/6177848/DashCharStructureBug.zip)

**Comment by 4ian** [comment]
There are multiple problems I think :) 

> The IDE autocompletes to the "level.1-1" as a valid reference, and that did work before b106.

It's weird that it did work before. When there is an "operator" sign like -, +, /... etc in the name, or even a space, the IDE should go for the "bracket notation": `Levels["Whatever here as long as it's a valid string :) !!"]`.
I should fix that.

Unsure why it was working before.

> On scene start -> Clear the children of "levels.1-1"

Seems like your example is trying to clear a variable called `1-1`. In any case this should not crash (see below), I'll also fix this.

> levels[1-1] -> levels.0 (it does the math apparently)

Yes, since beta 106 you can either use string: `MyVariable["MyChild"]` or a number : `MyVariable[1]`. This is useful for arrays (it works with structures too).

> levels[A-1] -> ERROR (same as original above)

Yep, so the error is:
`A-1` or `1-1` is not a valid variable name. Well it is, but it can't be used in an expression without quotes. So while `Levels["1-1"]` is perfectly valid, `1-1` alone is not. So GDevelop generate code for an unknown variable doing nothing, but when trying to clear this "unknown variable", it crashes.
I'll fix that.

**Comment by 4ian** [comment]
Fixed for next version. Suggestions will now be accurate, and invalid variable names not even suggested. Also fixed the crash when an invalid variable is still used.
