### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Richie785** [4ian/GDevelop#2464]
=> I was editing my game and as I was trying to add a new sprite the game crashed. I had not saved any of my work for a while so I am afraid I will lose it all. I am using GDevelop 5 for my school project and I really don't want to lose my work

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
undefined
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in a
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in h
    in h
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta101-f0392cfede2c8b68b2c9d652001d999eac819299
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18362,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta101 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @Richie785 
This error has happend on a old version of GDevelop (beta 101), this version is released some months ago.
It's probable this bug has been fix in next releases, today the current build is beta 107.

If you have any information about how reproduce this error we could investigate, otherwise we will close this ticket.
We recommend you to use the lastest release if you can.

Best regards
Bouh
