### ISSUE TITLE
First frame wrong position with custom hitbox

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2626]
When spawning and rotating an object, the object first appears with an offset if a custom hitbox has been set.
Example project attached.
b key acts normal, while c key shows the bug.
![image](https://user-images.githubusercontent.com/25978830/117546587-6f296c00-b02b-11eb-8b3f-aa4f197e209a.png)
[My_project.zip](https://github.com/4ian/GDevelop/files/6446181/My_project.zip)

Spotted on GD5b108 by a Discord user

**Comment by 4ian** [comment]
Thanks for reporting this and for the example project. This is indeed a bug that has been there for a while! Thankfully I've fixed it a few days ago! :)
I could confirm that the example project shows the issue on beta 108 and is fixed with the latest master version.

I should release a new version in the next few days :)
