### ISSUE TITLE
Improved BreakOut example

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#2629]
Improved BreakOut example:  
[BreakOut.zip](https://github.com/4ian/GDevelop/files/6457637/BreakOut.zip)

![MenuBreakOut](https://user-images.githubusercontent.com/73597906/117662336-0f62ca80-b1bd-11eb-94e5-3ce0c9ba040f.png)

![gameBreakOut](https://user-images.githubusercontent.com/73597906/117662351-138ee800-b1bd-11eb-9faa-c6ada759b58c.png)

:)

**Comment by Midhil457** [comment]
Thanks for the review! I have updated the first comment with the updated project.

- The OnFireParticle is rotated at a speed of 0/s so that it moves instantly if you put 0
- The Life is clamped with another event so that most the events related to Lifes can added into a single group, and not here and there

I have also fixes some other issues, typos and changed some of the events

:)

**Comment by Midhil457** [comment]
Thanks @D8H. As you suggested, I will remove the speed powerUps and add a multiball powerup. I have also decided to refactor some small parts. And as I have done many small changes. I think re-making the physics version might be easier. So, it might take a few days for me to finish it. Thx!

**Comment by Midhil457** [comment]
Hi, I have finished making the changes, 

[BreakOut.zip](https://github.com/4ian/GDevelop/files/6493626/BreakOut.zip)


There was a work around I had to make because of the limits to the physics engine. As you can't get the angle of forces of the physics object, I had to use a calculation that I got from the forum. It outputted a negtive value for reflex angles, and it gave me some problems checking if the movement angle was between 170 and -170. So, this was the only easy solution I got.

![Angle](https://user-images.githubusercontent.com/73597906/118486211-f87d2480-b736-11eb-92b0-088b6e2ebee0.png)

:)

**Comment by D8H** [comment]
I added some annotations:
https://www.dropbox.com/s/14lhamsse0qbqq2/BreakOutLeoRed3.zip?dl=1

I'm able to read the bonuses on a 24" now, but it's not comfortable to determine the arrows direction. Maybe a color could help to differentiate good and bad effects?

**Comment by Midhil457** [comment]
Hi, I have made all the changes (If I remebered to do all)

Sadly, I lost the svg file where I had all the original assets. So, now I can't do any further changes to the assets :disappointed: 

Also, I didn't fully understand the multi-ball deletion related comment. I did try doing the changes from what I understood and it introduced some bugs where the last ball also would be deleted, leaving no more balls in the scene.

Here is the new version: [BreakOut.zip](https://github.com/4ian/GDevelop/files/6522688/BreakOut.zip)


:)

**Comment by D8H** [comment]
> Sadly, I lost the svg file where I had all the original assets. So, now I can't do any further changes to the assets
Sad indeed. Some programs allow to shift an interval of hue but it may look bad on contrasted edges

In case the last 2 balls fall at the exact same frame, they will both be deleted because of this:
* number of balls > 1 => true
* Ball.Y() > ScreenHeight() => 2 balls picked and removed

Testing number of balls > 0 allows to always be in the case where there is no more balls and it has to be created for the next round. It's forcing the bug in a way :wink:
Another solution is to use a "for each instance". I think it's a bit heavy but it's a mater of taste.

**Comment by Midhil457** [comment]
I think I have fixed it, also some other bugs

New file: 
[BreakOut.zip](https://github.com/4ian/GDevelop/files/6526133/BreakOut.zip)

Thanks for the review!

:)

**Comment by 4ian** [comment]
The non physics version works well! :) 
I had some strange issues though with the physics version: 
- the speed of the ball randomly changes, sometimes become very slow
- when there are two balls, I had the issue of one falling and disappearing (as expected) but then the other started to move erratically, like forces are added on it.

I think we should make sure the physics version is a bit more bulletproof, otherwise this would give a bad view of GDevelop on this :)

**Comment by Midhil457** [comment]
Thanks for the reviews!

> the speed of the ball randomly changes, sometimes become very slow

I have fixed that, now the ball will be given a force when it gets to slow, and the linear damping is increase when it goes too fast

> when there are two balls, I had the issue of one falling and disappearing (as expected) but then the other started to move erratically, like forces are added on it.

That might have been because I used a scene variable to test the ball's ForceAngle and it used the same values for all the balls. Now it should be fixed

> In case the last 2 balls fall at the exact same frame, they will both be deleted because of this:
>number of balls > 1 => true
>Ball.Y() > ScreenHeight() => 2 balls picked and removed

It turns out that the fix I tried didn't fix it. Now, instead of using a variable, it uses the condition to check the number of balls

- Also fixed some issues with OnFire, ball keeps moving after the game is won/lost. Now the physics behavior itself is deactivated

- Tried restructuring the GameState to help understand it better

I have also fixed some other bugs and tried making the both versions more robust

New version: 
[BreakOut.zip](https://github.com/4ian/GDevelop/files/6533187/BreakOut.zip)

:)

**Comment by tristanbob** [comment]
> * I have fixed that, now the ball will be given a force when it gets to slow, and the linear damping is increase when it goes too fast

I haven't had time to look at your game, but I think Physics should be very easy with these settings:

Linear Dampening = 0
Angular Dampening = 0
Restitution = 1 

This way no force is lost and it will act very similar to the non-physics version.

**Comment by Bouh** [comment]
Here few of my feedback:

- I suggest removing the limit of FPS, put zero on min and max fps.
- Remove the red border sprite, this is useless, the position can be checked it's faster to check a position than test a collision.
And the position checking is way more efficient because if the ball goes through the red border the ball can continue and the party is stuck and have to be restart.
- The resolution is 2560x1440, if the resolution can be lower or better dynamic.
Because a big resolution takes more time to be computed on a low-end device.
- I would see this game project as a complete responsive game for desktop and mobile, anchor behavior can be used on objects for pin it on sides.
- Add text in Menu scene for normal and physic game icons are pretty but a text is a way understandable. 
- Color of GUIBackGround and the background scene color isn't enough contrast, hard to see the limit between both. A darker background is welcome like the modal window in GDevelop the bckground is darker and transparent and the modal window is on first plan.
- Adds a horizontal line on the x-axis where is stand the paddle to see faster if the ball is under the limit or not.

**Comment by Midhil457** [comment]
Thanks for the suggestions
> Gravity = 0
Linear Dampening = 0
Angular Dampening = 0
Restitution = 1

I am not 100% sure, but I think that's the settings the project is using. The restitution might be 0.9 instead of 1. Not sure.

>Remove the red border sprite, this is useless, the position can be checked it's faster to check a position than test a collision.
And the position checking is way more efficient because if the ball goes through the red border the ball can continue and the party is stuck and have to be restart.

That's there so that the ball has a object to bounce off in the non physics version. I don't know if I can do it without an object. In the physics version too, it serves as a barrier so that the ball will bounce off it

> The resolution is 2560x1440, if the resolution can be lower or better dynamic.
Because a big resolution takes more time to be computed on a low-end device.

I can decrease the resolution, but I have lost the original svg file that had all the assets. The current assets will look enlarged on the screen. 

Doing it dynamically would be great. How can I do it? Using "adapt screen resolution to screen"?

:)

**Comment by Midhil457** [comment]
Hi, I have made all the changes

- The game resolution is now 1920x1080, and resized the assets to fit
- Changed some of the assets
- Set the max FPS to 0
- The blocks in the layout are now better organised
- A PaddleLine has been added
- A life will be reduced when ball is below PaddleLine instead of the widnow
- Tags have been added to objects
- Changed the BreakOut logo in the Menu
- Added text that explains each scene
- Now the width is changed when resized
- The game will always be in the center, when resized (instead of the game moving to the left when resized)


But, sadly I wasn't able to make the UI elements anchor to the sides, most of the UI objects are used in multiple places and it broke when anchor is added. 

:)

**Comment by Midhil457** [comment]
I have opened this example in the new example repo, https://github.com/GDevelopApp/GDevelop-examples/pull/32

:)
