### ISSUE TITLE
Stacked ledges cannot all be grabbed

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2674]
In some conditions, the ledges of some stacked blocks cannot be grabbed.
Example project attached.
On the first column, all ledges can be grabbed.
On the second column, some ledges cannot be grabbed (third from bottom, and the highest one, in my testing). 

[LedgeBug.zip](https://github.com/4ian/GDevelop/files/6535105/LedgeBug.zip)

Tested on GD5b110 Win10x64

**Comment by D8H** [comment]
Thanks for reporting this.

I did some tests
* Changing the order of the block will change which can be grabbed.
* Make half height size again show it often (doing ungrab, fall, grab a lot are skipped)

I think that the issue is that there is serval platform candidates to be grabbed and only one is checked.

**Comment by 4ian** [comment]
Thanks @D8H! I think your general approach is right. Added a comment to maybe make things a bit less costly in terms of computations, but otherwise looks pretty good.
