### ISSUE TITLE
Show child variable references in autocompletion

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop#2679]
Show child variable references in autocompletion

#### Context
* The preference "Suggest names of variables used in events but not declared in the list of variables" is enable.
* Some children variables are defined in the variable list.
* Some children variables are use in the event sheet without being defined in the variable list.
* The user is writing a variable name in a variable field of the event sheet.

#### Actual
* Only defined children variables appear in the autocompletion.

#### Expected
* Children variables used in the event sheet should appear in the autocompletion the same way defined children variables do.

#### Context
* EventsVariablesFinder gives every variable reference expression it found. Child names or indexes can be calculated with expressions (for instance `PlayerInfo[1+1].Score`).
https://github.com/4ian/GDevelop/blob/master/Core/GDCore/IDE/Events/EventsVariablesFinder.h

#### Actual
* EventsRootVariablesFinder ignores every child references
https://github.com/4ian/GDevelop/blob/3125956dfcd7d3137e531d6c66b261a45f48c93b/newIDE/app/src/Utils/EventsRootVariablesFinder.js#L3-L5

#### Expected
* Use a regex to keep child variable references that doesn't contain expression.

### Going further
* Should autocompletion be done one path element at a time to avoid displaying every child?

**Comment by 4ian** [comment]
> Use a regex to keep child variable references that doesn't contain expression.

We should probably go a bit further:
EventsVariablesFinder should probably, instead of returning the "raw" expression string, should return the expression parser (to parse things like `PlayerInfo[1+1].Score`). Then we can run a class extending from ExpressionParser2NodeWorker on the result of the parser (the ExpressionNode that contains the result of the parsing). This class will "walk" through the nodes, and return a vector describing the variable shape.
When walking through the nodes, the class will expect to find either a `VariableNode` ("PlayerInfo"), a 
 `VariableAccessorNode` (".Score") or `VariableBracketAccessorNode` ("[1+1]"). So it can return a shape like this:
```js
// Note this is just an incomplete example in JSON notation.
{ 
  name: "PlayerInfo", 
  type: "array", 
  keyShape: {type: "number"}
  childrenShape: [{
    type: "structure", 
    keyShape: [{key: "Score"}]
  }]
} 
```

And augment this "shape" by reading multiple variables.

This "shape" information could then be used to complete variables in the variable lists :)

**Comment by Bouh** [comment]
This is complete now I think @4ian ?

**Comment by 4ian** [comment]
We did the reverse thing, but yeah I think it's not applicable anymore.
