### ISSUE TITLE
The Japanese version of the mathematical tool is incomplete.

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [4ian/GDevelop#2699]
The Japanese version of the math tool is incomplete.
The number of tools is small and there are no "Cube root" and "Floor".

![g1023](https://user-images.githubusercontent.com/68310169/120327232-7ee35a00-c324-11eb-98a2-9cef72c07c5e.png)

I used version 5.0.0-beta110.

**Comment by Bouh** [comment]
Some functions use the same text, that's why there is only one result in the list.

(This is also existing on extension with conditions/actions when you create your own action with an existing name in the engine.)

I've approved your changes on Crowdin for [Floor (round down)](https://crowdin.com/translate/gdevelop/1/en-ja#3733) and [Cube root](https://crowdin.com/translate/gdevelop/1/en-ja#3730).
This way **Cube root** pass from  平方根  to 立方根 
**Square root** keep 平方根 and will be visible on the next update.

The same idea for **Truncation**, as Truncation use 切り捨て and **Floor (round down)** was on the same text the list display only one result.
Now **Floor (round down)** use 切り下げ

**Comment by PANDAKO-GitHub** [comment]
@Bouh Thank you.
I wait for the next version.😊

**Comment by Bouh** [comment]
I close this has been fixed on Crowdin and will be effective at the next beta 111.
