### ISSUE TITLE
Allow fuzzy search for action/condition names

### ISSUE THREAD

**Issue by ClementPasteau** [4ian/GDevelop#2864]
## Description

When adding a new Condition or Action in the events tab, searching for the name is really strict which can be frustrating.
Ex: In order to find the action "Change the scene", I cannot be searching "Change scene"

![image](https://user-images.githubusercontent.com/4895034/128033358-b4cf4da0-e618-4b35-add9-c5bf252b4283.png)
![image](https://user-images.githubusercontent.com/4895034/128033400-0f2582ed-c388-413a-a3cd-0759515ce02c.png)

## Solution suggested

It would be great if the search was a bit more fuzzy, allowing missing words, typos or words in a different order, as it would speed up the creation of a game.

**Comment by 4ian** [comment]
Note that we do have some fuzzy search implemented in the`fuzzyOrEmptyFilter` function (weirdly name as a function btw). It's used in the CommandPalette.

Pretty sure we can apply it to the function filtering the instructions (i.e: conditions or actions), instead of just a lowercase search.

The only risk of this is that this can be more expensive to run, but not a lot I think because the fuzzy search is O(searched string), which should be similar to indexOf.
