### ISSUE TITLE
Ability to rename resources and have the name change be applied everywhere  (former name: New object type: Audio)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#3080]
## Description

Objects are used to describe various properties including static data (the source file) and defaults for dynamic data (size, z-order, layer, rotation, etc).  This enables users to use the object multiple times and know that it will have consistent defaults and it provides a single location to change the source file.

GDevelop should create an audio object that can take advantage of these benefits.

For example, a game dev can start with a placeholder sound file "FakeRoar.wav" and when the game is almost done they can replace it with "RealRoar.wav" without editing every action that is used to play that sound.

## Solution suggested

New object type: Audio

Static Properties:
- Source file

Defaults for dynamic properties:
- Volume
- Speed
- Looping (boolean)

## Alternatives considered

None.

**Comment by Silver-Streak** [comment]
@tristanbob As a workaround, the type of "Replace once and update all events" you're talking about can be done today, you just need to update the file in the resources. The "name" won't change in the event sheet, but the actual sound will.

**Comment by 4ian** [comment]
Yup, that's actually the idea behind resources. Resources have by default the name of the file they are representing, but this is just an easy way to automatically name resources.

In this situation, I would recommend to name your resource "Roar" and to change the file from "FakeRoar.wav" to "RealRoar.wav".
Note that maybe we can improve how we deal with resources (I'm not sure if currently if you rename a resource, it's being renamed in objects and events using it... if not we definitely need to do this), but this abstraction is made for this.

**Comment by Silver-Streak** [comment]
@4ian To clarify, you cannot currently rename resources at all. only their source paths. I'd probably agree there should be an option to rename resources.

![image](https://user-images.githubusercontent.com/24237149/134381975-5cf96e48-bc28-4548-8c65-8b78d4abb923.png)

**Comment by 4ian** [comment]
You can with a right click in the list (yep, not obvious too). But a warning will tell you that GDevelop won't update the rest of your game - which is sad and could be improved.

@tristanbob Would this be a good solution to your question?

**Comment by Silver-Streak** [comment]
Oh yeah, renaming the resource should *absolutely* update all events using the resource, rather than breaking events. In my opinion that'd be the best case to cover both scenarios. I'd be interested in Tristan's input on it, though.

**Comment by tristanbob** [comment]
> You can with a right click in the list (yep, not obvious too). But a warning will tell you that GDevelop won't update the rest of your game - which is sad and could be improved.
> 
> @tristanbob Would this be a good solution to your question?

Primary objectives:
- [x] Ability to choose new source files for audio resources 
- [ ] Ability to rename audio resources and have the name change be applied everywhere 
- [ ] When editing an audio action or condition, ability to select from existing audio resources using a drop-down list (similar to how object names work)

If I can do all 3 of these, then I would be happy.  :)

**Comment by Silver-Streak** [comment]
> * [ ]  When editing an audio action or condition, ability to select from existing audio resources using a drop-down list (similar to how object names work)

This one should exist today:  
![image](https://user-images.githubusercontent.com/24237149/134418121-bae70c8b-aa32-4b7c-8aed-48faf0088723.png)


So I think that second bullet (renames flow through to all events) is the big thing that would need to be fixed.

**Comment by 4ian** [comment]
> So I think that second bullet (renames flow through to all events) is the big thing that would need to be fixed.

Yep I think that's the only thing then!

**Comment by Midhil457** [comment]
I think the bug/annoyance I am dewcribing here is pretty similar to this, so I will add to this instead of opening another

If you rename an asset and then scan for resources, Gdevelop looks for different resource names instead of paths, so if you rename `Player` to `NotPlayer` ans then scan for images, another resource `Player` (same path as `NotPlayer`) would be created and considered a unique resource and it's a headache fix it.

It is really annoying when you work on projects made in a different OS because of the `/` and `\` difference, and it's a real pain to change.

Another issue is importing from the asset store, when you import an asset from the asset store, the resource name would just be the assets name (`Milk Chocolate.png` and not `asset/Milk Chocolate.png`) so the problem occurs here too

https://user-images.githubusercontent.com/73597906/134525221-3f1016ab-2d55-425f-9a39-411bd978c6cb.mp4

I do know you can fix the issue by renaming the assets to the filepath, but no one would be interested in doing for nearly 100 assets
:)

**Comment by 4ian** [comment]
> If you rename an asset and then scan for resources, Gdevelop looks for different resource names instead of paths, so if you rename Player to NotPlayer and then scan for images, another resource Player (same path as NotPlayer) would be created and considered a unique resource and it's a headache to fix it.

Indeed, that's also a bug - only the filename is used to check if the resource already exists, which is not correct. I'll fix that!

> Another issue is importing from the asset store, when you import an asset from the asset store, the resource name would just be the assets name (Milk Chocolate.png and not asset/Milk Chocolate.png) so the problem occurs here too

Yeah that must be linked, only the name is used instead of the file so same problem I think.

I think with this fixed and the renaming not flowing through the rest of the project fixed too, we should be in a much better position (you can rename resources without breaking your project, and you can removed unused resources/scan for new without fearing for duplicates).

**Comment by 4ian** [comment]
Both resource renaming and scanning for resources (that was improperly adding back resources because it was not looking at the file of the resources, just the name - which was totally wrong) should be fixed for next version :)
 
 This will allow you to use resources at they intended to be: a name that can be anything, so that you could have a generic name and change the file later.
