### ISSUE TITLE
Blurry TrueTypeFont text

### ISSUE THREAD

**Issue by Frederic-Modine** [4ian/GDevelop#3258]
## Describe the bug
With a project with no antialiasing and Round pixel in Game Settings, text in TrueTypeFont of a text object or BBcode are always blurry. More text have a little size, more the blur is important.

![image](https://user-images.githubusercontent.com/1670670/142270479-712c79b8-5c05-459e-b3a4-29f3e8ae99c5.png)

## Other details
Mac and Windows
GD 5.0.121, Desktop + web-app

**Comment by Silver-Streak** [comment]
Hello! 

Unfortunately, my understanding is this is not a bug and is due to how operating systems and web browsers render text. Electron (what your game runs in) is a Chromium browser that wraps the game files to displwy.

Because OSes render the fonts, when you use a pixel/retro style font instead of a more modern vector font, they scale up to be blurry when you start scaling up from a smaller resolution. Vector based fonts will have this as well, but to a much smaller degree.

There are two options for this:

1. If you wish to keep using ttf directly, you will need to ensure they aren't being scales at all. This means your game resolution will need to match the desktop resolution (usually 1080p) when fullscreened, or be close to that if windowed. You will need to scale up your other assets by editing them and increasing their size 2, 3, or 4x (or more as needed) to keep your game looking roughly the same virtual resolution  it has today. I generally don't recommend this unless you absolutely have to use BBText for some reason.
Or

2. Use the Bitmap Text object instead of BBText or Text objects. Bitmap Text doesn't use Chromium or Operating System font rendering and therefore doesn't experience these issues.

I opened a bounty around this a few years back and Bitmap Text was implemented as the solution. You can read through that proccess here https://github.com/4ian/GDevelop/issues/1449

**Comment by Silver-Streak** [comment]
Just checking if you tried Bitmap Text objects and if it solved the issue for you?
