### ISSUE TITLE
Exporting can be cancelled by switching tabs

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3407]
## Describe the bug
While exporting, if you switch the tab, the exporting can be cancelled (I don't know if it's internally cancelled)
## To Reproduce
1. Go to export dialog
2. Export to stores
3. Export the game
4. Switch the tab to some other export option

## Other details
* Desktop
* GDevelop 5.0.124

## Solution suggested
- Have the tabs disabled and the dialog not closeable when exporting or even better, have GDevelop handle multiple types of exports at once (Desktop and mobile, etc..) which can be accessed in the different tabs

**Comment by ClementPasteau** [comment]
Hello, thanks for reporting!

So the exports that are started are never cancelled internally (except if they fail, but you'd still see the results).
They are then accessible in the "See all builds" section (being reworked, so the name is changed on my screenshot)

![Screenshot 2021-12-28 at 09 35 37](https://user-images.githubusercontent.com/4895034/147546681-35963c0a-d1d1-4fca-b1a7-c9e3f6cf948e.png)

You would see the running build in the dialog (again, the design may differ a bit)

![image](https://user-images.githubusercontent.com/4895034/147546658-8ca1e87d-d1fd-4de0-a7bf-2a2ff9099a05.png)

I can see a few bad implementation points indeed:
- If you switch tab when a build is running and come back, the build disappear, which can be scary for the user
- If you access the "see all my builds" in the first 10-15 seconds of the build starting (not fully initialised yet) the running build doesn't appear in the list

I can see 3 improvements:
1. I like the idea of disabling any action (tabs, close, etc...) in the beginning of the build, at least to the point where it is running and we're waiting for it to be available. (~10 seconds)
2. We could also keep the tab state, so that if you switch tab and come back, you still see the build running (ensure of this though, because it means you can't start another build of the same type though, which can be impacting if you realise you've done a mistake, change it, and want to build again)
3. Finally, we could add some kind of indicator (little dot) on this "See builds" button when a build (any build) is running, so that they click on it and realise it's in there.

I'd vote for 1 & 3 :)

**Comment by 4ian** [comment]
Improvement 1 seems the best quick fix to do (though we'll need to find a way for the dialog to know when a build is running), we don't want to stop a build that is not running already.
Even if we do improvement 2, we still want to avoid closing the dialog before the build is running.

> ensure of this though, because it means you can't start another build of the same type though, which can be impacting if you realise you've done a mistake, change it, and want to build again

Well, as soon as you've opened the dialog, you won't do any change to the game, so starting a build of a type once is 1) enough and 2) you probably never want to launch it again, because your game would be unchanged.

So it might make sense to look, for this dialog only, if we can instead of unmounting tabs, keep them always mounted but not visible (this is what we do for the main frame tabs for example).

**Comment by Midhil457** [comment]
I like option 2. Maybe a cancel option could be added to fix the issue

Or maybe the dialog could be closable, but it will spawn a non-closable snackbar with the export type, progress. And will also have a link to the build list. But, it will create another problem of teh user able to close the project. Is there a cancel option for exports? I also don't know if the snakbar allows for this much complexity

**Comment by ClementPasteau** [comment]
The export process has been improved with #3432 and the point 1 is now implemented: you can't switch tabs until the build is actually launched, meaning you will not have the case where you click "see all builds" and don't see your build.
Let's see if that's enough once released before implementing something else!

**Comment by AlexandreSi** [comment]
Hi @Midhil457 !

Following @ClementPasteau's improvements, do you think this issue is still relevant?
