### ISSUE TITLE
Timers break down and are unrealiable for time measurement.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#3594]
## Describe the bug
Timers have a huge game breaking bug that when measuring elapsed time to trigger an event when desired amount of time has passed, or just measuring elapsed time .

It is broken to the point of timers becoming useless for measuring valid time.
For if there is enough load on the game to have an effect on frame rate be it of any reason OR having lag spike of any kind.

In the image 
Elapsed time using Timers 9,95sec
System time in seconds 26sec
Elapsed time using Timestamps from system 26,469sec...
Calculation used (Present Timestamp - StoredTimestamp)/1000
![image](https://user-images.githubusercontent.com/90930609/152500508-384431ea-face-40c5-9cc7-1e321c79a020.png)

## To Reproduce
Make enough effects and load on the game to slow down framerate significantly to see the problem escalate immensely.ie. 5 seconds measured takes 15 seconds in real time.

Here's the example to suffocate the renderer and printouts on timers triggered to start when system time in seconds reaches 0

printout of the timers
printout of the system time in seconds
Printout of timestamps
printout of the elapsed time using timestamps

[BugTest.zip](https://github.com/4ian/GDevelop/files/8001420/BugTest.zip)

## Other details
![image](https://user-images.githubusercontent.com/90930609/152493320-4862d002-4663-4c69-8d3e-148339e01b59.png)
OS Windows 10

**Comment by VanCastar** [comment]
Timers as their name states, should [u]always[/u] rely on [u]actual[/u] time elapsed and not on arbitary approximation of rendered frametime.

**Comment by Silver-Streak** [comment]
While I'm not 100% sure on the code, Timers as far as I know have always been frame dependent. I believe this is by design otherwise they can't be impacted by time scale changes.

If you are looking for timescale/performance independant timers I think you would need to use variables that add TimeDelta() to their value.

This is just going off my memory, however. A contributor more familiar with the code may be anle to confirm.

**Comment by VanCastar** [comment]
Yeah, I thought about that on my drive home that it might be because of the timescaling.
That should be optional tbh like as a tab to check in the event so we could use true timers or the modified ones.

I'm already replacing all the timers as Timestamp comparisons to workaround this problem.

**Comment by 4ian** [comment]
This is indeed by design :) A timer is just a variable that increments as fast as the game is simulated, which means this *will* derive from the "real world" time when:
- the game is going below the minimum framerate that was configured. Set it to 0 if you don't want this to happen.
- the time scale of the scene (or the layer of the object) is changed.

Note that because of these two reasons, this *is* the good design decision. You don't want your game simulation output to vary according to the framerate, and if timer were following the time given by the computer (which is btw non necessarily having monotonicity: the time can sometimes go back by a few milliseconds/seconds according to the leap seconds or approximations like this), we would have serious inconsistencies (for example, a speed calculation different than the actual distance followed by an object during time).
