### ISSUE TITLE
Small firebase usability adjustments

### ISSUE THREAD

**Issue by jack-ii** [4ian/GDevelop#3603]
- [ ] **Remove the text "is not" in the event sheet of query filter actions**
![f2](https://user-images.githubusercontent.com/81538128/152656634-a45ff04c-92ab-49fe-b3cc-3af8b8f636d8.png)

- [ ] **Rename the Firestore Queries "Initialize" category and "Start" actions to "Create"**
As it is already called in the eventsheet.
If non-programmer see in the wiki they need a "Create a query" but only find "Start a query" it could be confusing. Start sounds more like Execute than Create and in localized versions it could be completely weird. In general it helps if condition/action has the same name in sheet and editor.

- [ ] **Sort the Queries categories in a logical order. Create > Filter > Execute**

- [ ] **Show the callback variables in Authentication actions eventsheet text, as it is at firebase actions**

- [ ] **Remove "result" or "state" from "store result state in" at the eventsheet text of Write a field in firestore action.
Maybe also remove the "Merge: yes/no"**
It prevents the action from becoming two lines and is not really necessary to display there.

- [ ] **Possibly rename "Cloud Firestore" to "Firestore Database"**

**Comment by Bouh** [comment]
cc @arthuro555

**Comment by arthuro555** [comment]
Also I think someone told me the send password reset email action is broken (it asks for authentication, when obviously it shouldn't)

**Comment by arthuro555** [comment]
>  Remove the text "is not" in the event sheet of query filter actions

Why? It is true, all documents that do not match the condition will be excluded by the query.

>  Possibly rename "Cloud Firestore" to "Firestore Database"

Why? That will only confuse people, let's keep the official name so that people know what we are referring to. Inventing terminology for something that already has existing one already will always only lead to problems. It might be confused with Firebase Realtime Database or make you think that Realtime database is more real-time than Firestore, which it is not.

>  Remove "result" or "state" from "store result state in" at the eventsheet text of Write a field in firestore action.

Disagree, the parameters should be everywhere to be able to edit them from the event sheet via the inline popover. Your 2 lines are subjective, other users with different screen sizes, zoom levels, or amount of subevent indentation will have a different available width for the action, making it wrap either way for some users or not at all as it is.

**Comment by jack-ii** [comment]
> Why? It is true, all documents that do not match the condition will be excluded by the query.

I was not 1000% sure, but it looks wrong. Because we have to choose a logical operator ourselves. It is then != != or != == in a row. If that's correct then I didn't say anything :)

> Why? That will only confuse people, let's keep the official name so that people know what we are referring to.

![01](https://user-images.githubusercontent.com/81538128/153732402-e8f743c2-8a2c-4d07-a293-81759003c5e7.png)
Because of that and the GD Wiki article also never mentions an Cloud Firestore.
For me the distinction with Realtime is easier if both have the same scheme. But okay was just a suggestion. 


On FullHD, with an UID, without subevent, it always breaks into a second line because of 2-3 letters. And that is confusing. 
**(store result state in** is a unnecessary too long text, in an already very full action.
"doc." instead of "document" would also help. But ya is your decision.

**Comment by arthuro555** [comment]
> Because of that and the GD Wiki article also never mentions an Cloud Firestore.

🤔 I see. But otherwise, it is called everywhere cloud Firestore. Let's go with "Cloud Firestore Database" then maybe?
