### ISSUE TITLE
Save the Web builds

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3684]
When we generate a Web build, the link is not saved in the builds' menu, so it gets lost, and we need to generate a new one, which needlessly consumes the build server bandwidth and storage.
![image](https://user-images.githubusercontent.com/25978830/155154506-270789d2-c594-41c8-b130-fb9e05248d3a.png)
Can it be added to the build history?

[source](https://forum.gdevelop.io/t/getting-share-links-for-exported-game-on-liluo/38299/2)

**Comment by 4ian** [comment]
Can you double check?

They should be in the builds:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1280130/155166130-a287d5d2-cdc7-45d6-979f-e48c50797358.png">

And also accessible in the games dashboard:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/1280130/155166274-08892e31-2ead-4e9b-ae7b-e9df1bc4e721.png">

**Comment by PascalLadalle** [comment]
I did check, and the button remains disabled.
I guess only the other builds enable the button.
Easy fix, then, I bet. :)

**Comment by 4ian** [comment]
Would be worth checking on the development version/next release because the button works well for me when tested? Or there is a race condition.

**Comment by PascalLadalle** [comment]
In the dashboard, I don't see the current project for which I tried the Web build, but the project is not mine, so I get the analytics warning, maybe that is interfering?
![image](https://user-images.githubusercontent.com/25978830/155170963-80581e64-3540-45ec-98c9-94508951557d.png)

**Comment by 4ian** [comment]
Totally, this means you also don't have the rights to publish this game on Liluo, or access the builds of the game (you can make "instant" web build, and you will get a link to share, but because it's not *your* game, it's not associated to the game on Liluo and you don't get the unique URL to share on Liluo).

@ClementPasteau Would be worth letting the button open the builds dialog but with a message "This game is not owned by you, so you can't see the builds or publish a build to the game page on Liluo.io."

**Comment by 4ian** [comment]
Also in the future we should let users nominated users to be owner of their game, so you could share the ownership of a game with another user, or at least get "write" access so you can publish a new build on Liluo :)

**Comment by ClementPasteau** [comment]
Interesting!
Yes, because this project is not yours, you can't access the builds that are linked to it.
I agree that UX-wise, it would be better to let you click on it an explain why you can't see them.
+ as you mentioned, It would be great to allow multiple owners :)

I'll try to take a look at this.

**Comment by ClementPasteau** [comment]
Addressed in #3704 - button is enabled and shows a warning explaining why this is not accessible.
The feature of allowing multiple owners is another story :)
