### ISSUE TITLE
Allow expressions where objectList is expected

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#3697]
Would it be possible that anywhere an objectList is expected, expressions are allowed?
![image](https://user-images.githubusercontent.com/25978830/155861054-5be8acf8-728a-49a3-b63e-bccbe5ceb7be.png)

**Comment by 4ian** [comment]
I'm pretty sure there is a thread somewhere on GitHub or on the forum but the short answer is: "no", because:

- This makes refactoring your game super hard. If you rename an object, all of these expressions become invalid.
- This destroy any hope for optimisation because GDevelop has no idea what objects will expected. 
- GDevelop might not even remember the name of objects in the running game, replacing them by identifiers/numbers so that your game performance is not tied to the length of your object name.
- You can't know which objects you will get, so you would not be able to use specific object expressions.
- This makes the expression parser grammar ambiguous (is this an object, is this a string, do you accept both?)

I understand the need, but this encourage a style of "coding" which is more fragile and harder to read. If you need to apply things to multiple objects, conditions are here for this. In other words, things should be done according to whatever variable, behavior properties etc... are on the object rather than on the name of the object. If things need to be applied on multiple objects, groups are here for this. If the condition to count objects should be applied on an object according to something, a variable is probably what we would recommend :)

**Comment by PascalLadalle** [comment]
I get the idea.
I guess I'm in an edge case of sorts because I want to spot nonexistent objects (cf. Count object = 0) which, by definition, have no variable or anything that could help identify them.

Some context about the screenshot if you wish:
I have several scenes, all with a varying number of text objects, all named sXX, XX being a number, and (external) navigation arrows call the objects in each scene through a number variable.
I wanted to know when the navigation reaches a nonexistent instance, to skip to an existing one (0 if next arrow, max XX if previous arrow).
The only solution I found is to hardcode the number of objects in each scene (Set objectCount scene variable to XX).

I should use a text file and load the strings in a single text object, but I was only doing a change of interface, so I built on existing code with XX text objects in several scenes, and a "no instance of (expression) exists" seemed the easiest and logical way to proceed.

Cheers

**Comment by 4ian** [comment]
I see! In this case you could try the "reverse" condition approach with a variable:

Set a variable to a value (like "true")
Run your condition checking for the existence of some objects. If so, set the variable to false

Finally, run your actions if the variable is true. Basically, you just inverted the logical result of the condition. You can also use the "NOT" advanced condition to do this in theory.

Give it a try and let me know if this can work?

**Comment by PascalLadalle** [comment]
Yes! Gave me a hard time but I managed :)
Cheers
