### ISSUE TITLE
Copy and paste variable objects

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3761]
I believe we must have a regression here! Now to copy object variables, we must do more steps than before

https://user-images.githubusercontent.com/23488207/159143367-3583705e-3a69-4abb-bcaf-aa41942fbe21.mp4

**Comment by Silver-Streak** [comment]
I've renamed this a bit for clarity, as I instructed William to post this.

Too add context for anyone who looks at the change: since the Get Started button was added to empty behaviors/variables/etc, the Paste/delete/etc buttons at the bottom of the variable page doesn't appear until after clicking "Add A Variable" first. 

This is an additional step/regression from prior workflows, and means that you have to add an empty/useless variable before you can paste.

Those buttons should probably remain visible/usable even before the Add A Variable button is clicked.
