### ISSUE TITLE
Object variable does not save as it should

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#3967]
Previous versions of GD, when inserting an object variable and modifying it, whenever we left the object, this variable automatically recorded. Now that doesn't happen anymore, when modifying the value of a variable, and clicking on another object, the variable is reset. Only if we click on something in the panel is recorded.

https://user-images.githubusercontent.com/23488207/170849914-c672120d-6852-4f87-ad94-a804c4bced10.mp4

Notice in the video, that for the variable to be recorded, I have to click above, otherwise the edit is not saved.

**Comment by 4ian** [comment]
This is indeed a bug! Thanks for reporting.

@AlexandreSi This is because [we removed](https://github.com/4ian/GDevelop/commit/3356400026d8b9312426a79e2787d11b8455ce30#diff-8353daf5f30a3f18f4c70447e54b450cc9b5b2310750dcd064121ee2b6561c8bL141) `commitVariableValueOnBlur` which was telling the internal SemiControlledTextFields to store changes at every letter typed. Useless when the VariablesList is in a dialog (because this is demanding in terms of re-renders), but useful when it's in the `InstancesPropertiesEditor`, where it can be unmounted at any time without being blurred.

We should probably fix his by doing the same: a prop to tell "please commit changes even if not blurred", by passing commitOnBlur to true or false.

**Comment by krunkster** [comment]
I was just about to write up this same bug... it took me a while to figure out what was happening!
Thanks for looking into it!

**Comment by tristanbob** [comment]
I have experienced the confusion that this bug causes.

### Steps To Recreate:

1) Add an object variable
2) Click on an instance of that object
3) Click the value field of the instance variable
4) Type one character 
5) Focus leaves the instance variable field
6) Any extra typing may trigger hotkeys in the editor (this happened to me)

### Preferred solutions:
- When a user clicks in the value field of an object variable, automatically convert it to an instance variable and let them type (without stealing focus)

OR

- Add an "Edit" icon button on right side of an variable value field to convert to an instance variable and automatically move focus to the value field
