### ISSUE TITLE
White modern theme

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#4040]
## Description

Recently, the Dark modern theme has been added to GDevelop and it looks Gorgeous !!!
but some people (maybe just me :p) still prefer the white theme of GDevelop :3
but still want this modern look from the dark theme to be the same but in White.
For example:
in the modern dark theme we have rounded buttons and another colors (highlights) got added everyone, from the events to objects lists to properties, to buttons (purple)
so if possible can we have this in the White version, so it would be like this:

GDevelop White theme Default
**1-** purple buttons.
**2-** Rounded buttons.
**3-** Highlight added to properties/panels/settings..etc.
**4-** Shadow for buttons.

**Comment by Bouh** [comment]
Hi
You can already try the white modern theme on the web editor!
https://editor.gdevelop.io

**Comment by 4ian** [comment]
Yeah this is because you need to open the app a first time online (it will silently update), then you need to close it entirely after a few seconds (make sure to close all tabs), then finally open it again and it should update.

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/1280130/174091739-3789c731-5a18-4d11-9902-827cfe735a46.png">
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/1280130/174091787-1d422399-197d-4455-862e-bb79b380e3e8.png">

:)

**Comment by VegeTato** [comment]
Wow that looks soo cool ! 😍
Cant wait to use it in the offline version ❤️
