### ISSUE TITLE
Add particle emitter examples provided by pixi into GDevelop asset store

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4082]
## Description

Particle emitters have so many variables it is often overwhelming for new users to get started.

GDevelop should include a variety of particle emitters in the Asset Store so that people can quickly get a feel for what is possible and perhaps modify one of the examples for their own game.

## Solution suggested

Pixi has ~30 particle emitter examples that we can use to quickly get started with this.

Test example particle emitters (click "Load"):
https://pixijs.io/pixi-particles-editor/#

Source code:
https://github.com/pixijs/particle-emitter/tree/master/docs/examples

**Comment by Bouh** [comment]
We can't directly import these particle effects from PixiJS, but we could totally recreate them with the Particle Object in GD and make them importable from the Asset Store I agree.
The process would be:
- Create a project with all the object particles inside.
- Send it to me, and I package the objects for the Asset Store :) !

We've a bit of documentation about the how to on the wiki, but maybe it's unclear, because it as been done once by Florian for the Wishforge Games' Particles objects.
I can totally help to recreate these object ;)

**Comment by VegeTato** [comment]
I can help in that :3
Check list of finished particles (From pixi to GDevelop example)

- [X] Trail
- [X] Flame
- [X] Gas
- [ ] Exposition 1
- [ ] Exposition 2
- [ ] Exposition 3
- [ ] Megaman Death
- [ ] Rain
- [ ] Pixie Dust
- [ ] Smoke
- [ ] Bubbles
- [ ] Bubble Stream
- [ ] Bubble Spray
- [ ] Vertical Bubbles
- [ ] Cartoon Smoke
- [ ] Cartoon Smoke Blast
- [ ] Pixel Trail
- [ ] Snow
- [ ] Sparks

**Comment by VegeTato** [comment]
Here is the project, i did my best to get the same results as pixi particles examples 👍
[Particles Example.zip](https://github.com/4ian/GDevelop/files/9067122/Particles.Example.zip)

**Comment by Bouh** [comment]
I started to implement the objects in the Asset Store.
I'll keep you informed here of the progress.

@planktonfun unfortunately objects can't yet be wrapped with their events, I'll skip this object for now.
