### ISSUE TITLE
Change the name of exports to be based on the name of the game (instead of "game.aab")

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4103]
## Description

Android exports are always named "game.aab".  This is confusing if you are managing multiple games.  

## Solution suggested

Change the name of Android exports to be based on the name of the game (instead of "game.aab").

Note:  This should also be the same for other exports, such as "game.exe" for Windows exports.

**Comment by tristanbob** [comment]
I would also love to see the version number included.  I'm sure there is a max length for file names but I'm not sure what it is.  We could trúncate the project name as needed.

**Comment by AlexandreSi** [comment]
There are 2 approaches I think:
- Either we change the names under which we save the builds in the backend.
- Either we change the way we download the build so that the browser/electron changes the name of the file.

I would vote for the second option. Here is a link to something we could try: https://stackoverflow.com/a/67601262/9517183

**Comment by AlexandreSi** [comment]
I opened a draft that sends the required filename to the build endpoint so that the code that computes the filename is exposed in this (public) repository and not in the backend. There's still some work to do server-side.
I will resume work on this next week.
