### ISSUE TITLE
'Not equal to' sign in event sheet is misaligned

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#4109]
## Describe the bug
When using the 'not equal to' sign in a comparison condition, the actual symbol is displayed in the event sheet, but it's misaligned such that the slash appears *after* the equal sign, instead of *through* it.

If you click on it, a popup allows you to change the sign, and the sign displayed in the popup displays correctly.

![image](https://user-images.githubusercontent.com/2385329/179396135-c0d4b9a4-0eb9-48b6-86f4-08a0f3294950.png)

## To Reproduce
1. Go to the event sheet for a scene
2. Click on 'Add condition'
3. Choose a condition that lets you select the 'Not equal to' sign (e.g. 'Compare two numbers')
4. Fill in the condition parameters, selecting 'Not equal to' as the sign
5. Save the condition and view its summary in the event sheet

Here's a link to an example: [not-equal-to.zip](https://github.com/4ian/GDevelop/files/9127523/not-equal-to.zip)

## Other details
I'm running GDevelop v5.0.138 on Manjaro Linux (KDE Plasma v5.24.6).

**Comment by AlexandreSi** [comment]
Hi,
I think the issue comes from your machine.
I'm on Mac and I see that this is a single character (see below)

<img width="225" alt="image" src="https://user-images.githubusercontent.com/32449369/181282557-f66914d9-79e0-4d79-89cb-c2fe97e1cd9e.png">

When inspecting it, I can see this is a single character, so it looks like it's a font issue.

The same character is used in both the dropdown and the summary (≠ or character https://unicodelookup.com/#%E2%89%A0/1)

This might be due to the fact that in the summary, it is not wrapped in our text component which uses our default font (Fira Sans) but it directly uses the user's system's font.

Have you spotted this "off" equal sign anywhere else on your computer?

**Comment by Bouh** [comment]
FYI on my Windows 10, it works fine.
![image](https://user-images.githubusercontent.com/1670670/181366673-94f82749-cb51-444b-9b70-92390f60f975.png)

**Comment by BWPanda** [comment]
I've confirmed that this is an issue with the font on my system:

![image](https://user-images.githubusercontent.com/2385329/182049661-82fa240a-dd8d-465d-b3a3-4e281c7c0c39.png)

I don't have any of the fonts listed to display this character, so it defaults to Noto Sans which is the default sans-serif font.

`-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,"Helvetica Neue",Helvetica,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"`

So not a bug with GDevelop, sorry. Feel free to close this issue now.

**Comment by AlexandreSi** [comment]
Thanks for your response!
Let's close this issue then.
