### ISSUE TITLE
Object cannot be seen - X scale of 0 - Wrong instance targeted? - b118

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#4125]
I reopened a project from last year which used to be functional, and it's very much broken now.
Aside from the recent Physics "fixes" that seem to break it even more, some change was brought in beta 118 that broke one of the game mechanics.
I'm attaching a dummy project demonstrating the issue.

[buggootest.zip](https://github.com/4ian/GDevelop/files/9159540/buggootest.zip)

The related event, inside a custom behavior, is:
![image](https://user-images.githubusercontent.com/25978830/180222577-05798be6-65bb-4bab-9f45-6e72fd977d30.png)

Tagging @D8H as he started to investigate it.

**Comment by D8H** [comment]
The example uses a behavior function to iterate over Object aka goo instance one by one and still use the same object as a parameter (ExistingBrick aka goo).

![image](https://user-images.githubusercontent.com/2611977/180271038-0ae68e35-1f78-457c-b7ac-975d927f1427.png)

What happens is that the current instance of Object is linked to Link and the same instance is also into ExistingBrick which is link to Link. As this is the same instance its distance with itself is 0.

What happens with 118+ is this:
- The link size is set using the 2 right instances of "goo"
- But then it is set again using the same instance for the objects which result to 0
```
Change link width to 156.3111429321172
Change link width to 0
```
I find it odd the it doesn't log these lines twice as the same sing should happen with the other "goo" as Object. Maybe this is the bug.

I'll try with the 116 to see if 4 lines are logged or if this is just the order that changed.

I guess that these events probably only work by chance and I would advise to
- use 2 objects instead of "goo"
- create one instance of each one on top of the other
Note that it may create 2 links for each link but with some thinking it could work.

**Comment by D8H** [comment]
I tried with the 115 and the result is the same but in the other order:
```
Change link width to 0
Change link width to 156.88957384552202
```
There is no contract on the order of the picked instances, so this is not a bug.

**Comment by PascalLadalle** [comment]
Thanks for investigating!
I don't quite understand why there are two _link width change_ actions, since there is only one **link** instance on the scene, and only one **goo** instance that can act as "Object", the one currently being dragged.

The point of using a custom behavior was to allow the use of "link instanceA with instanceB" without GDevelop being confused about which was which, and it does work very consistently until b118, even with large structures and multiple ExistingBrick instances.

I'll try to switch to another method, but I guess I'll need three objects, right? new brick, existing brick, and goo on top of both to achieve the same result visually.

**Comment by PascalLadalle** [comment]
Oh, right, of course.
One might wonder why it ever worked. 😅
Thanks for taking the time.
