### ISSUE TITLE
Inconsistency with how blank layers are shown in events

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#4219]
Both the "Move the object to a different layer" and "Create an object at specified position" actions allow you to leave the layer blank to indicate the default base layer:

![image](https://user-images.githubusercontent.com/2385329/186348863-be9d9383-6d47-4de8-a5b1-26fff1a0e617.png)

![image](https://user-images.githubusercontent.com/2385329/186348753-1b6a528c-95d6-4bc5-b922-327df34dd456.png)

However, when you do so, they display differently in the event sheet, such that it looks like there's an error with the "Move the object to a different layer" action:

![image](https://user-images.githubusercontent.com/2385329/186349481-bfc40db4-8bd1-4724-82cc-f0a3312c4039.png)

It'd be nice if these could display consistently.

**Comment by Bouh** [comment]
@D8H I assign this to you because I remember you were the one who added inline errors in the event sheet.

**Comment by D8H** [comment]
> I guess there is a problem with optional parameters. But here, both should be required and errored.

Extension definitions set if a parameter is optionnal or not.

In this case:
- an object is created on the base layer by default so the layer parameter is optional.
- when an object must be put in another layer, the destination layer must be set, the parameter is mandatory.

In short, this is expected. There is nothing to fix.

**Comment by BWPanda** [comment]
> when an object must be put in another layer, the destination layer must be set, the parameter is mandatory.

So then why does it say "base layer if empty"? If it's a required field then it shouldn't mention being able to leave it empty.

I don't agree that "There is nothing to fix." Something needs to change here to make this more consistent and user-friendly...

**Comment by Bouh** [comment]
> Something needs to change here to make this more consistent and user-friendly...

I agree that is inconsistency.
Both are same parameters with same descriptions. A fix can just be to change the description.

The sentence for moving the object of layer could be:
`Put OBJECT on another layer LAYERNAME`
And we add the optional value on the layer parameter because after all the parameter is already optional as there is an auto-completion on it.
This way there is no more error at the end of the action due to the optional parameter, and if there is a layer filled it will be shown in the event sheet like the Create object action.

**Comment by D8H** [comment]
> > when an object must be put in another layer, the destination layer must be set, the parameter is mandatory.
> 
> So then why does it say "base layer if empty"? If it's a required field then it shouldn't mention being able to leave it empty.
> 
> I don't agree that "There is nothing to fix." Something needs to change here to make this more consistent and user-friendly...

Yes, sorry, I missed that part.

> > Something needs to change here to make this more consistent and user-friendly...
> 
> I agree that is inconsistency. Both are the same parameters with the same descriptions and that is normal. But a fix can just be to change the sentence.
> 
> The sentence for moving the object of the layer could be: `Put OBJECT on another layer LAYERNAME` And we add the optional value on the layer parameter because after all the parameter is already optional as there is an auto-completion on it. This way there is no more error at the end of the action due to the optional parameter, and if there is a layer filled it will be shown in the event sheet like the Create object action.

It would be a solution.

I still think that the parameter must remain mandatory but the parameter description should be change from "Move it to this layer (base layer if empty)" to "Move it to this layer".

Because leaving an empty layer when creating an object means "I want to create an object and I don't care about the layer". The same thing for the move action wouldn't make sense: if I want to move an object to another layer, I do care about layers.
