### ISSUE TITLE
Variable tweens are not setting the variable to starting value at creation.

### ISSUE THREAD

**Issue by VanCastar** [4ian/GDevelop#4270]
When creating a variable tween, the starting value is not set as the variable value when creating the tween.
The variable is refreshed only after the next pass.

And this example quits instantly.
![image](https://user-images.githubusercontent.com/90930609/188507283-14428a75-3c8e-418d-b822-05986f50bfa8.png)

The only way to work around is to set the Variable as 255 before the Tween starts OR start the tween AFTER the variable checking 
![image](https://user-images.githubusercontent.com/90930609/188507317-3ded32f1-0e2b-4b7d-a203-8c6b97462cbd.png)

Windows 10 with GDev version 5.0.140

**Comment by AlexandreSi** [comment]
Hi @VanCastar!
Thanks for taking the time to report this.
Basically, what happens is that tweens are processed during the pre events phase.

So here is the chronology:
- Frame N
  - Tweens are processed (nothing happens)
  - The events you show are executed:
    - Variable `Dong` is directly set at 600
    - A new tween is created
- Frame N+1
  - Tweens are processed 
    - Variable is set at 253.4543933 (time has elapsed since last frame)

Is anyone would expect that the tween is effective right away, we should consider it a bug and fix it.

Otherwise we could add an optional Yes/No parameter in all the tween actions that would read something like "Start tween right away" default `Yes`.
=> But it feels weird, we might as well consider it a bug and fix it.

**Comment by D8H** [comment]
Every other Tweens use the current value for the beginning and only the targeted value is specified.
I think that the tween variable action should act the same:
- the "from" parameter should be removed
- users should use the variable actions if they want to start at another value.

I don't really like the variable tween, it feels hacky to me. I think it would be better to have a value tween action that modify an internal value and let users get this value with an expression.
