### ISSUE TITLE
Traduction bug

### ISSUE THREAD

**Issue by TomatoSupremo** [4ian/GDevelop#4403]
If you right click on an object, copy it and then want to paste it says paste instead of "pegar"
![image](https://user-images.githubusercontent.com/77708346/196060907-d89699fe-0fd9-4b1a-be3a-79bdfc16590f.png)

**Comment by ClementPasteau** [comment]
Thanks for reporting @TomatoSupremo 

It looks like the Paste action label is not translated at the moment, because it tries to display which object you are copying (in your case "Puerta").
https://github.com/4ian/GDevelop/blob/2c92ce74ce3ae3d79bf16cca3a50482cd267d756/newIDE/app/src/ObjectsList/index.js#L86-L97

I'll update this
