### ISSUE TITLE
Repeat while event freeze the game

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#4460]
## Describe the bug
When there is an action incrementing a variable in a repeat while event it freezes the game until the condition is met.

## To Reproduce

[Project Repeat While.zip](https://github.com/4ian/GDevelop/files/9893343/Repeat.While.zip)

1. Start the project,
2. Launch the preview
3. Wait for two seconds
4. See the timestamp is stopped
5. Resize the window, and a black bar appear, the game is frozen.

## Other details
GD all versions
Reported on Discord

**Comment by Bouh** [comment]
Is it possible to make the loop asynchronous so that it does not block the game?
The fact that there is no warning on the game we don't know if it's broken or if it does something. In any case it's unusable.

**Comment by 4ian** [comment]
The thing is that you're asking GDevelop to make an (almost) infinite loop, so it's doing it. 
If you want to make something that does not block the game, you have to do it every frame. I really have the impression here we're talking about an hypothetical issue instead of a real problem: what is the real problem the user had? Why did they use a while loop that was doing 100000 iterations per frame? Why they need this? 

Then we can answer the question "could it be done asynchronously" (but I already see the issues if we allow these things to run asynchronously, like a "wait" action. Someone WILL be also using it without understanding it and someone will launch EVERY frame a loop that is running 100000 iterations at EVERY frame, so the problem is that you have now in a second not one but 60 loops doing 10000 iterations => the problem is now worse).

If anything, we could try to detect frames that are too long and display a message "whoops seems like your game is frozen, better double check if your events or a rogue extension is not blocking your game or making it nearly unusable with a computation that is way too long".
