### ISSUE TITLE
Lucid Icon Pack V1.1

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#4500]
27 new icons were added, and some were updated

![Preview](https://user-images.githubusercontent.com/73597906/200028522-01630161-570b-4738-a028-9f18ffb8abe0.png)

## Description

- License: CC0
- Author: Leo
- Link to the original website: https://leo-red.itch.io/lucid-icon-pack
- Zip file: [LucidV1.1-Icon-Pack.zip](https://github.com/4ian/GDevelop/files/9940385/LucidV1.1-Icon-Pack.zip)

][

**Comment by Bouh** [comment]
Hello

The filenames are wrong, animations are not correctly generated because you used `-` instead of `_`.
For instance you named:
```
Chevron-Arrow-Down.png
Chevron-Arrow-Right.png
```
![image](https://user-images.githubusercontent.com/1670670/201103690-0422348d-f81b-4ba1-833e-933c8a928795.png)


These give two objects. I recommend to edit to do one object with two animations.

It should be:
```
Chevron Arrow_Down.png
Chevron Arrow_Right.png
```
![image](https://user-images.githubusercontent.com/1670670/201103916-e7dca5fc-2943-4885-8d99-b4e5bf3df0a9.png)


This is an example, there is a lot of filename for fix.
Let me know when it's done ;)

Entropy has made an awesome tools to check the filenames, and how it could looks like in the asset store, [try it here](https://github.com/Entr0py404/GDev-Asset-Store-Tool/releases).

**Comment by Midhil457** [comment]
😅 
Fixed Everything (I hope so)
[LucidV1.1-Icon-Pack.zip](https://github.com/4ian/GDevelop/files/9990368/LucidV1.1-Icon-Pack.zip)

:)

**Comment by Bouh** [comment]
The pack is now updated.
Thank you for the update, and sorry for the delay.
