### ISSUE TITLE
Isometric Interiors Asset Pack Submission

### ISSUE THREAD

**Issue by buggystudio** [4ian/GDevelop#4599]
## Description
- Attached is the zip file for my Isometric Interiors. The pack contains over 200 assets to create an isometric-style environment. 

- License: CC0
- Author: Millennium Bug Studios
- Link to the original website: [www.buggystudio.com](www.buggystudio.com)
- Zip file: [mbs_iip_ol.zip](https://github.com/4ian/GDevelop/files/10118564/mbs_iip_ol.zip)

**Comment by Bouh** [comment]
Thanks for this submission!
I fixed few files names to fit our convention from the [guide](https://wiki.gdevelop.io/gdevelop5/community/contribute-to-the-assets-store).
For instance: 
`wall_blue_nodoor_a.png` -> `wall blue nodoor_a.png`

I removed the underscores, because they are used as separator to generate the animations.

The syntax is:
`my object name_animation name.png`

This will generate a frame in the object named `my object name` within the animation `animation name`.

If there is more animation frames increase the number at the end starting at 1, like:
```
wall blue nodoor_a_1.png
wall blue nodoor_a_2.png
wall blue nodoor_a_3.png
```

**Comment by buggystudio** [comment]
Hi!

Thank you and I will make note of that on all my future submissions.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Bouh** [comment]
Thanks. The pack is now live in the asset store! 🎉
![image](https://user-images.githubusercontent.com/1670670/206678349-3b5533ce-6eb3-4d0b-b2ee-f0fc684c1d14.png)
![image](https://user-images.githubusercontent.com/1670670/206678375-ee34f83c-20b5-4fae-92e6-1b02263551da.png)
![image](https://user-images.githubusercontent.com/1670670/206678420-d32e5b63-cb32-4ee3-9e14-8383a729e8ca.png)

**Comment by buggystudio** [comment]
Good morning,

Wow thank you! I will be bothering you pretty soon with some more packs. I just need to work on the names to make sure there are no issues.
You guys are awesome. Thank you for all you do.


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
