### ISSUE TITLE
Art Packs by Chierit

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop#4780]
- License: CC-BY 4.0
- Author: Chierit
- Link to the original website: https://chierit.itch.io
- Zip file: [Chierit.zip](https://github.com/4ian/GDevelop/files/10346230/Chierit.zip)

**Comment by Bouh** [comment]
It's integrated this week, I promise :)

**Comment by Bouh** [comment]
@Entr0py404 I found that the Arrow object in `Chierit\Elementals` wasn't visible in the asset store preview.

- The reason is that the sprite in the idle/normal state is simply named `Arrow.png` while the other states are with an animation name like `Arrow_Hit_1.png`.
So the object isn't visible, the `Arrow.png` must be renamed something like `Arrow_Idle.png` to be visible.

Simple name on object are used only when there is no animation.
Is a test can be added to the File Name Validator ?

- I can see few black sprites, I don't know why, I tried to extract files twice but it persist.
![image](https://user-images.githubusercontent.com/1670670/210796904-39eaa95f-7edd-4cab-bd62-2ae6b5d1bcfa.png)

It's maybe a false positive or something going wrong with the cache of my file explorer, don't bother too much about it if you didn't have idea on how to fix it.

I'll start to integrate the pack in the dev mode to see how it goes.

**Comment by Entr0py404** [comment]
Indeed I forgot forgot to rename the arrow for idle. I will look into your suggestion on adding a rule for missing animation name
On assets with multiple animations.

The black images are blank full transparent images windows explorer sometimes shows transparency as black.

I normally try to remove these if they are not needed but, if it's at the end of the animation, I noticed in gdevelop the last frame is not accounted for because the timing is "time between frames" and there is no next frame after the last, ie animation finished is called immediately on last frame and not after.

so I think keeping them at the end sometimes helps but, I have removed some in the past like in sprite particles. I figured if the user had a issue in how they ended that they would add a blank frame themselves if needed.

**Comment by Bouh** [comment]
> I normally try to remove these if they are absolutely not needed but, if it's at the end of the animation, I noticed in gdevelop the last frame is not accounted for because the timing is "time between frames" and there is no next frame after the last, ie animation finished is called immediately on last frame and not after.
> 
> so I think keeping them at the end sometimes helps but, I have removed some in the past like in sprite particles. I figured if the user had a issue in how they ended that they would add a blank frame themselves if needed.

It sound like something to fix in the engine.

> The black images are blank full transparent images windows explorer sometimes shows transparency as black.

Glad you learn me that! I really wondered where the logic was^^

**Comment by Entr0py404** [comment]
In the middle of adding the new rule to the name validator, I found "Leaf Ranger_Defend.png" needs to be renamed to Leaf "Ranger_Defend Pose.png"

**Comment by Bouh** [comment]
I fix it.

I found `Diagonal Arrow.png` needs to be renamed too, otherwise the objects animation won't works.

**Comment by Bouh** [comment]
Another thing I don't understand is why the Trap object have a Throw animation with a sprite which is different in the preview and in the explorer.

![image](https://user-images.githubusercontent.com/1670670/210866684-daa2dfeb-1990-4c3a-826f-a37ff5e2c9b6.png)

**Comment by Bouh** [comment]
Here how looks the pack in GDevelop:
https://streamable.com/yfpvv0

The Elementals characters are small.
For instance the with the Leaf Ranger due to the beam in the Special Attack animation.

Here the project file with all the assets imported in a scene.
[gdevelop-game.zip](https://github.com/4ian/GDevelop/files/10360586/gdevelop-game.zip)

What do you think about the animation needs the blank image?

**Comment by Entr0py404** [comment]
Looks good, thank you bouh!

In the long run hopfully gdevelop will fix the animation time issue in the future, but for now the options are 

1. Leave them in

2. Replace them with the last non-blank image

3. let the user in gdevelop duplicate the last frame that way an extra file image is not needed

**Comment by Bouh** [comment]
I'll leave them in, then come back delete it once the issue were fixed.
