### ISSUE TITLE
Copy grid settings when duplicating an external layout

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#4947]
## Description

External layouts are great ways to create many levels with new content by carefully placing each object.  The editor grid is very important in this workflow, but there is no way to keep a preferred grid setting when creating a new external layout.  

## Solution suggested

My workflow usually includes duplicating the previous level, so I would like:

- Duplicating external layouts keep the same grid settings 

## Alternatives considered

- Offer a way to set default grid settings for all new scenes and layouts

**Comment by tristanbob** [comment]
I just tested this again, and the grid settings did get copied.  I must have done something wrong in my initial testing.

**Comment by VanCastar** [comment]
This problem seems to persist and it's really annoying.
Duplicating External Layouts always have the default grid settings and not the ones that were copied or duplicated.
Not even when the scene that the external scenes were linked to had the same grid setups.

Original external layout with grids visible
![Image](https://github.com/user-attachments/assets/522add71-e2d1-4318-b74e-6b5282c61ed5)

New external layout that was either copied or duplicated with default grid setup (needed to set the grid visible first).
![Image](https://github.com/user-attachments/assets/bb06b958-45c9-48dc-8912-224bf3de9499)
