### ISSUE TITLE
Asset Bug

### ISSUE THREAD

**Issue by ayhangazisite** [4ian/GDevelop#5042]
## Describe the bug
There is a problem. Images or fonts get corrupted when I move an object or fonts in the game engine or open another game.json in its own file.

## To Reproduce
1: Create a project.
2: Create an image
3: (Add to room.)
4: Move that picture.
5: Then close the game engine.
6: Then open the game engine.
7: Open the project.

Even if I let it move the images to its own file, that problem exists.
![resim](https://user-images.githubusercontent.com/125784354/222116461-850df5b6-e2a2-4ae5-85ae-676b75d4e1ba.png)

## Other details
* Linux Mint 21.1
* GDevelop: 5.1.157 (Desktop)

**Comment by ayhangazisite** [comment]
Hi.

Let me explain the problem like this. The image that is inserted into the engine (whether it is in its own directory or not), when it cannot find it, the image disappears. Even though I moved the files, when I open the backup of game.js, the project breaks down.

If this is exceeded, I want to continue using it.

**Comment by Silver-Streak** [comment]
To make sure I am understanding correctly:
You add an image to a sprite.
You then move the image file (not the sprite), or the game.json file, and no longer see the image.

Is the above accurate? Because if so, that is expected behavior. The project only keeps relative locations to the game project folder, so if the source image is copied to the folder when adding the sprite, and then moved from the folder (or game.json is moved) the images will not work.

As an example:
1. I create a game project at C:\My Project or (for some reason) /home/My Project
2. I create a sprite object.
3. I add an image file (test.png) and let GDevelop copy it to the project directory, so it is now /home/My Project/test.png (or C:\My Project\test.png)
4. I save and close the project, then move the file somewhere else (so I move it from /home/My Project/test.png to /home/OtherFiles/test.png). 
5. I have now broken the known location for the resources from the game project. 
6. Alternatively, if I move /home/My Project/game.json to somewhere like /usr/Game Jsons/game.json, I have also broken the known location for the resources from the game project. The game.json just keeps relative file locations, not encoded file data itself, so without moving the files along with it, it will break the project.


Is something other than the above happening? If so, can you write up the steps on what you're actually doing involving "Moving the files"

**Comment by ayhangazisite** [comment]
This is the situation. If you can fix this expected, I want to continue using this program. Your competitor writes these files to its own data and even if you move/delete it, that file is there. Please solve this problem.

Or you can prevent the game.json file from opening if it cannot find that file. Have them find those files for the file to open. Thus, the graphical errors in that project will be fixed. If they don't have it then just replace it with the error graph.

**Comment by Silver-Streak** [comment]
I apologize, I'm still not 100% understanding what you're saying is the issue.

To be more clear, are you:
A. Moving the files out of the project folder (where the game.json is stored)
B. Moving the project file out of the project folder (Without also moving the rest of the project files with it)
C. Something else

If it is A or B, that is not a bug and is expected behavior. The project file must remain with the project files, and they cannot be moved without one another. 

If it is C, there may be something else going on and it can be investigated further.

**Comment by ayhangazisite** [comment]
A and B.

We also need to solve the problem of moving pictures.

**Comment by Silver-Streak** [comment]
I've mentioned it to the devs, but in general:
The game.json only contains your game logic and the relative locations of assets. It does not contain the assets itself, and is not intended to. If you move the assets away, those relative locations are no longer valid unless you move everything back to where it was originally. 

The intention is that all asset files should be contained in the project folder, and the game.json and assets should be kept in the same folder, even for backups. This isn't a bug, and I don't know that this will ever change, but I did forward this on.

**Comment by Silver-Streak** [comment]
I have heard back from the devs and confirmed

The entire folder is your project, not just the json file. The project.json file just contains the event logic, and will not contain your assets. To do backups you need to backup the whole folder, not just the game.json. This is the design of the project structure, is not likely to be changed in the future.

However, if you have moved just the game.json, you can access the resources panel and repoint your resources to the new asset locations.
![image](https://user-images.githubusercontent.com/24237149/222214290-c0fe3570-67e3-4f9f-a9e9-a17b05b91f8d.png)
![image](https://user-images.githubusercontent.com/24237149/222214447-2b336b8b-6e70-4188-9a1b-589cd82a2e40.png)

You will need to do this for any files you move from their original locations or if you move the project json without the rest of the project assets.

As this is not a bug, this issue will be closed out.
