### ISSUE TITLE
Add action to pick random object in group

### ISSUE THREAD

**Issue by AlexandreSi** [4ian/GDevelop#5070]
## Description

There is no easy way to pick a random object in a group. For example to create random objects for a game like geometry monster

## Solution suggested

Add action to pick random object in group
I feel like there will be issues regarding the type of the object but maybe it could be done.
=> This could be a parameter, so we would have: "Select X random object of type Sprite in group Group"

## Current workaround

Follow the steps here: https://wiki.gdevelop.io/fr/gdevelop5/tutorials/geometry-monster/5-adding-and-moving-shapes
Same tactic here: https://forum.gdevelop.io/t/group-of-objects-in-different-order/40686

**Comment by Bouh** [comment]
This isn't already in the app with this action?
![image](https://user-images.githubusercontent.com/1670670/224033101-4604874d-95d9-4bef-983e-5d04d5e6e943.png)

**Comment by Bouh** [comment]
On my screenshot the object is a group.

With this action we can select an objectsList, and this type allow to use an object, and a group of object (which is a list of object.)
But yeah in the object picking you canno't just use the objects from a group if the events parent already picked an object.
Because this mean you'll get the previous object already picked + all the objects from the object group.

To acheive that without the object already picked, we miss an action to clear the object pick list.

**Comment by 4ian** [comment]
I'm not sure this request is implying the need for a "clear the objects pick list".

Let's say @AlexandreSi has a group of objects called "Group". It contains:
- Object1
- Object2
- Object3
- Object4

Either:
1. The user wants to **create** one object randomly. So they use the action `Create object with name "Object" + RandomInRange(1,4)`. It's a bit of a pain because it means the name of the object have to be properly written and the "4" is not updated if you add an object.
  
  So we could maybe add an action "Create a new object randomly chosen in the group X". It would pick this object for the next actions/events.
2. OR the user wants to pick a random **instance already living** on the scene. In this case, the action shown by @Bouh should work?

**Comment by AlexandreSi** [comment]
Thanks for the clarification, I was talking about 1. indeed.

**Comment by AlexandreSi** [comment]
As discussed together, we might need an extension that allows that and allows the actions that users usually need (tweak the randomness/the probability)
