### ISSUE TITLE
Tile Map doesn't render

### ISSUE THREAD

**Issue by danilwhale** [4ian/GDevelop#5244]
## Describe the bug
When I create Tile Map object and insert map/atlas/tileset I have no tile map rendered in the world

## To Reproduce
1. Create project
2. Create tile map
3. Insert map/atlas/tileset

![image](https://user-images.githubusercontent.com/61111955/232881218-60547eac-e46b-4137-b21c-2dad7c57eef5.png)

[gTOE.zip](https://github.com/4ian/GDevelop/files/11265466/gTOE.zip)

## Other details
Windows 10
GDevelop 5.1.160

**Comment by convictedweirdo** [comment]
I believe there may be an issue with the files you have exported from Tiled. I have just imported your tiles from the PNG provided and made a tileset and map with the assets and they are working as intended. 

![image](https://user-images.githubusercontent.com/25803863/232936497-5fafe256-d16a-4aa0-babf-5202a5e15223.png)

![image](https://user-images.githubusercontent.com/25803863/232936659-5c4d7eec-b838-4434-b2e6-71486a580987.png)

You might want to consider recreating a fresh tileset within Tiled.

Working project below. Hope this helps.

[workingTilemap.zip](https://github.com/4ian/GDevelop/files/11267443/workingTilemap.zip)

**Comment by willianholtz** [comment]
I've seen many of these errors here on github, and I'll say one thing:

In "Tilset Json File", you only put the json of the tileset if you generate it inside Tiled or LDtk (does LDtk do that?). I see many users reporting common connection errors with these files.

One suggestion is to change this name so that there are no more problems with these things. Suggesting TMJ and TSJ would be way better than "Tiled" or "LDtk" in the first file!
