### ISSUE TITLE
Watermark enabled by default.

### ISSUE THREAD

**Issue by MadameMalady** [4ian/GDevelop#5275]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug
Edited-
For some strange reason, after recent updates, G Develop exports all have branding on them that you can't seem to remove..

You wouldn't be putting forced branding on an MIT licensed project with the idea of advertising your engine over peoples work until they pay you not to, right?

I'm not against G Develop making money, but this is a growingly intrusive method.
Please consider changing this for ethical reasons.
The splash screen is more than ample for advertisement.
I've used this engine for four years, and idk how much longer if this is how G Develop plans to profit in the future.

### Steps to reproduce

Make a project

export it

run it

cry when you see the gaudy, moving, forced branding

learn Godot

### GDevelop platform

Desktop

### GDevelop version

5.1.160

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Linux

*OS Version (e.g. Windows 10, macOS 10.15)*
> NA

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
> NA

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
> NA

</details>

### Additional context

Why would you use layers of forced branding as a tactic to make money. What the heck.

Edit; for the first several launches, the branding was on till I closed the game, after restarting my device, it stays on screen for about thirty seconds, it's mildly less intrusive like that, but I still do not understand the need to add more layers of advertisement beyond the splash screen (which I have no issues with).

**Comment by 4ian** [comment]
Hi, 

You can choose to have:
- the splashscreen
- or the watermark (which advertise your username on gd.games with a link to your profile)
- or both.

If you don't want the watermark, just go in the project settings and disable it: 
![image](https://user-images.githubusercontent.com/1280130/236674829-d1bee5f8-78ba-444c-8653-7f98d5d33e16.png)

I encourage you to keep it because:
- It's a perfect way to get your players to visit your profile (your username is shown first) and your other games.
- It just stays a few seconds and allow you to support GDevelop for free (developing GDevelop requires the work of multiple software engineers and this is not free at all). 

I suggest next time though you ask on Discord or the forum before opening a GitHub issue, as this is not a technical problem or bug ;)
Thanks!

**Comment by Silver-Streak** [comment]
Hello! 

As 4ian mentioned, you can swap between the watermark, the loading screen, or both via the project settings. The loading screen has always been part the engine, and the watermark was added as an option about 10-15 release versions ago.  

New projects have the watermark enabled by default, but you can swap between them via the GUI, or disable all of them via the GUI

**Comment by Bouh** [comment]
Here is how to disable the watermark. nor the splash screen without any sub.
![Animation](https://github.com/4ian/GDevelop/assets/1670670/d751ef28-f153-4277-bc56-20810e77c46a)

**Comment by 4ian** [comment]
I'm sorry you feel that way @MadameMalady but as we've all mentioned, you can remove the watermark and keep the splashscreen, like it always was - since **many many years**. 

This (splashscreen and/or watermark) is important for the growth of the engine and we need support from our users, either in the form of this splashscreen or subscriptions to sustain the hundred of thousands of dollars we're pouring into GDevelop development.
We hope you understand and continue to support us, as this is something that we let you deactivate! :)

**Comment by MadameMalady** [comment]
I can't actually get the export to work right now, it just freezes and crashes, so I will just assume that the last gif is correct and drop it :-/ don't actually have a way to test it, was working on something for the 3d jam coming up but I guess it's too heavy for the export step now.

I like your engine, but I don't love all the ads over everything by default. And it can't handle 3d objects quite yet sadly,  meaning it still makes sense for me to switch to an engine that's able to. I don't have interest in opening an issue rn for the export crashing, I'm going to 'unsubscribe to this issue' now.

**Comment by 4ian** [comment]
@MadameMalady for 3D objects, stay tuned because there might be some interesting news here (which required a lot of work from professional developers who have to get paid to eat and live ;)). 
Nobody like ads - I understand you. At the same time, it's again an easy way to help a bit GDevelop without paying - making an open source software sustainable is very hard. Not all open source projects work the same, see this interesting GitHub article: https://github.com/readme/featured/how-open-is-open-source

Anyway, wishing you the best of luck for your games made with GDevelop or with another engine - at the end it's all about making games :)

**Comment by tyashin** [comment]
As far as I understand, the IDE is licensed under the MIT license which allows for modification of the program (i.e.IDE).
As of 10/25/23 to remove watermark in your web exported game you'll have to find the snippet ""watermark":{"placement":"bottom-left","showWatermark":true}" in data.js file and edit it as follows: "watermark":{"placement":"bottom-left","showWatermark":false}

Tested on GDevelop version 5.2.176. Not sure what you should do to achieve the same result for other export targets, as I never needed those.
