### ISSUE TITLE
Bucky's Platformer City in Asset Store

### ISSUE THREAD

**Issue by SlumberPartyGames** [4ian/GDevelop#5419]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Hello! Here is the link to the pack: 
https://gdevelop.io/asset-store/bucky-platformer-city-5ea243a8-a1cb-47fb-8efb-fbbad7467b81 

What is wrong:
- Title should be Bucky's Platformer City  (the " 's " is missing)
- The numbers of the sprites is not correct. 

The correct numbers are:
Total Sprites: 511
Animated Characters: 6
Buildings: 29 modular pieces with 3 colors each (87 in total)
Props: 46 sprites
Tiled Sprites: 3
Audios: 45

Thank you and have a nice day :D !

### Steps to reproduce

Link to asset: https://gdevelop.io/asset-store/bucky-platformer-city-5ea243a8-a1cb-47fb-8efb-fbbad7467b81

### GDevelop platform

Desktop

### GDevelop version

5.1.164 

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by Bouh** [comment]
Hello,

The number of assets is generated from the files we've.
Some of them has been removed, because they are placeholder with a unique color. That kind of assets are not useful in an asset pack and shouldn't be inside. The placeholder are made by people creating their games depending of their needs.

We've fixed the title. It will be available in few hours.
