### ISSUE TITLE
Android Phone vibrates after a long click

### ISSUE THREAD

**Issue by fizzingpop** [4ian/GDevelop#5724]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

5.2.174 introduces a bug where on an Android phone if you hold a touch down (for example to jump higher in a platformer game), the phone will vibrate.

### Steps to reproduce

1. Export an Android project
2. Long click anywhere in the game

### GDevelop platform

Desktop

### GDevelop version

5.2.174

**Comment by ClementPasteau** [comment]
Hi @fizzingpop thanks for reporting. I can confirm I reproduce the issue.

It's extremely strange, as nothing should have changed on this side of things.
I can reproduce it on the web too, with Chrome, using an Android device:

A few versions before: https://games.gdevelop-app.com/game-1a2854f2-a513-44b7-a14b-fbf929e90851/index.html -> no vibration
Since 174: https://games.gdevelop-app.com/game-af9a8bfb-ce21-4020-8a31-be632bd04e97/index.html -> vibration

I've dug into it, but running out of ideas of why this can be happening. We'll need to take a look deeper.
