### ISSUE TITLE
Bug in windows exported game

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#589]
Hello,

I work on a new tiny project with GD5 (beta48), and i spotted two bugs on compiled executables for windows : 

1) Action "Quit the game" : 
If you trigger this action, the window just freeze (music continue to play)... Even if i stop the music before adding the action, the windows won't close, and stay frozen for ever.

2) Action "Activate fullscreen" : 
Nothing happen if i trigger this action. Even if i resize the windows size at the same time, borders of the window are still there.

A topic about these problem on the forum about this : http://forum.compilgames.net/viewtopic.php?p=67773#p67773

**Comment by 4ian** [comment]
So turns out that Quit the game was never properly implement for HTML5 games/GD5.
The changes should be done in `scenestack.js`, to call navigator.app.exitApp (on Cordova) or close the window on Electron for Windows/macOS/Linux.

For fullscreen, support was added using the HTML5 Fullscreen API, but seems that Electron is not supporting it/is not implementing it in the same way. Instead, BrowserWindow.setFullScreen should be called (after `require`-ing electron module). 

I'll try to provide quick fixes for these.

**Comment by 4ian** [comment]
Started some fixes here: https://github.com/4ian/GD/pull/590

Quit the game was easy to implement. Fullscreen is more complex.

**Comment by KinkGD** [comment]
@4ian , same problem on android builds : quit action made the game freeze and doesn't quit.

**Comment by 4ian** [comment]
Yep I've also fixed this (even if it's quite unusual on mobile to even have a close button - I think you can hide it and nobody will complain ;))

**Comment by 4ian** [comment]
This should be ready for next version - I'm closing the issue to track that it's done :)
