### ISSUE TITLE
Problem on with italic style on last character of text object

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#598]
The screen above is made from GD5, but i faced the same problem with GD4 earlier : When a text is in italic, and if the last character is "l" (L in lowercase) or "!", the upper part of the character is "cutted" by the edge of the text object. 

![italic-bug](https://user-images.githubusercontent.com/8144048/44685376-9e4e4980-aa4b-11e8-9db0-1c148225e86a.png)

Basically, i always corrected the issue by adding a space at the end of sentences with these two characters in last charpos, but a fix might be great.

PS : it's done with the default GD5 font, the problem is same, or even worse, with a custom font.

**Comment by 4ian** [comment]
It's related to the way Pixi.js render texts. I think I might have seen something to avoid this, might have to dig a bit into the documentation to see what they say

**Comment by 4ian** [comment]
So seems this could be fixed using `padding` option for the style passed to the text object: http://pixijs.download/dev/docs/PIXI.TextStyle.html#padding

I wonder if adding this padding will make the rendering of the text different. If yes, this should be a customizable option in the text object properties so that we can choose the padding to apply for every text (without polluting the rendering of text that don't have this issue)

**Comment by 4ian** [comment]
Should be "fixed" with padding option added by @wend1go :)

**Comment by Silver-Streak** [comment]
I am going through older issues to refresh attention to them or close them out.
I've tested this and it appears to be fixed:
![image](https://user-images.githubusercontent.com/24237149/126904986-0fc9704d-58f1-45f3-a20d-4b72fcc35ea2.png)

If anyone is still experiencing this please feel free to reopen.
