### ISSUE TITLE
Intermediate loading screen when changing a scene despite it being preloaded

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#6042]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

There is an intermediate loading screen when changing a scene despite it being already preloaded.
[BugReport.zip](https://github.com/4ian/GDevelop/files/13624612/BugReport.zip)

https://github.com/4ian/GDevelop/assets/98941240/a94d2264-f1ba-4ad1-8742-d5ec177e119a

### Steps to reproduce

Change to any scene that has been preloaded.

Instructions are also included within the bug report project.

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.3.183

### Platform info

Windows 10 21H2 (OS Build 19044. 1288)

**Comment by D8H** [comment]
Do you mean the black screen flash?

**Comment by ZachjuKamashi** [comment]
> Do you mean the black screen flash?

Yes. I am pretty sure it is due to the change with how loading works now.

**Comment by D8H** [comment]
Indeed, there is an intermediate loading screen in case there are 3D models to process. We must have missed it because initially the frame was the same color as the background but we changed it to black because it was causing some kind of fash after a loading screen.
We'll take a look on Monday, thanks for reporting this issue.

**Comment by D8H** [comment]
Thank you for reporting this issue, it should be fixed in the next release.
