### ISSUE TITLE
Yarn 

### ISSUE THREAD

**Issue by dagode** [4ian/GDevelop#6112]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When making a coloured tag which is possible only with BBCode text type there is a slight delay.

### Steps to reproduce

1. Go to Yarn.
2. Write a code for an animating text.
3. Add a coloured tag to a random text.
4. Run the editor.
5. The text has a slight delay.

### GDevelop platform

Desktop

### GDevelop version

This version of GDevelop is: 5.3.180

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by Silver-Streak** [comment]
Hello!  This is axtually an existing issue.

https://github.com/4ian/GDevelop/issues/3011

It is due to how yarn parses the text since it doesn't know/care about bbtext tag. The "delay" is it scrolling through the tags even though you don't see them rendered by the text box.

It's many years old and would require modifying the way Yarn's scrolling logic works.

**Comment by ClementPasteau** [comment]
closing as duplicate
