### ISSUE TITLE
Is it possible to allow each object to have antialiasing activated or deactivated?

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [4ian/GDevelop#6142]
One of the things I have seen while I have tried GDevelop is the scale mode, which allows us to activate anti-aliasing or not, for games that are pixel art or not.

But I have had several doubts
1. Is it possible to make GDevelop draw text without anti-aliasing?
2. Is it possible to make each object configurable to activate or deactivate its anti-aliasing?

I have been seeing that many games combine the Pixel Art aesthetic with the let's say anime aesthetic, and in my case the non-Pixel Art sprites and the text lose quality as the screen is scaled, all of this by not having antialiasing and not be able to configure that certain objects cannot have their antialiasing removed

**Comment by Silver-Streak** [comment]
Hello, Github is generally for reporting engine issues or requesting enhancements, not asking usage questions. However:

 1. GDevelop doesn't control text or bbtext object rendering at all besides color and font size. Those objects are rendered by your OS and tberefore whatever your OS does to text display will apply. However, if you use Bitmap Fonts with a bitmap text object, the text is rendered as an sprite image and then is controlled just like any other image rather than through your OS's font renderer.
2. Sort of. If you are using Nearest neighbor scaling in your project settings and ensure you are keeping your game at 1:1 aspect ratios to its original (e.g only zoom in 1x/2x/3x/etc and not 1.5 or 3.2x), you can enable or disable the "smooth the image" checkbox in your resources panel and it'll apply or not apply basic anti aliasing. You can somewhat do this with linear scaling as well but then your screen is going to have some base level of linear algorithms applied at all times regardless.

In the future, please bring usage questioj discussions to the forum or discord. Thanks!

**Comment by QuetzalcoutlDev** [comment]
I understand, I had forgotten that the questions go to the forum
