### ISSUE TITLE
GD5 : Sprite object edition enhancements

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#616]
Hello,

I've made some propositons on the forum about some enhancements for sprites edition, with screenshots of how it could look like, since i use a lot of complex animation in a project i'm currently making.

http://forum.compilgames.net/viewtopic.php?f=22&t=10633

These features would be really good for productivity, GD5 is really more time consuming than gd4 for sprites edition (animation part, hitboxes part, and basically organisation of a complex animation).

**Comment by 4ian** [comment]
Could you add the link to the forum post? :)

**Comment by KinkGD** [comment]
Damn it, it was in ! Sorry here you go : http://forum.compilgames.net/viewtopic.php?f=22&t=10633

**Comment by KinkGD** [comment]
Ok, yes i can only suppose it's a lot work !

What about duplicate frame feature ? Right now it's pretty "hardcore" when i have a lap of 0.07 between each frame and one image wich have to be displayed for 2seconds in the animation. 
As i explained, in GD4 , duplicating frames was easy (drag and drop from image list on the right), but the actual way of GD5.. "+" navigate to folder (because the editor don't remember the last opened folder) select image, validate.. again and again!

Another idea from frame duplication : ctrl+click and drag ? (like for event duplication) ?

**Comment by 4ian** [comment]
I've added a duplicate button (that will duplicate the sprites selected, i.e: the one you've right clicked but also any other that you've selected with the checkboxes).
Should be in the next version :)

![image](https://user-images.githubusercontent.com/1280130/45061667-66738180-b09d-11e8-8648-33cf397e7f34.png)

**Comment by 4ian** [comment]
Managed to add drag'n'drop for the vertices of the collision masks and the points :)
Should be welcome as it's true that it was a big pain point.

Zoom is not added because it's more work and I prefer do it step by step. I've added a card there to follow the demand: https://trello.com/c/kPRc19zV/147-add-support-for-zooming-in-out-when-editing-points-hit-boxes-or-in-a-preview-of-a-sprite-in-the-sprite-editor

![collisonmasks](https://user-images.githubusercontent.com/1280130/45123792-faa61d00-b15f-11e8-95f1-e13ee7fe868a.gif)

![points](https://user-images.githubusercontent.com/1280130/45123881-435dd600-b160-11e8-8204-5429bd43faf0.gif)

Will be in the next version!

**Comment by blurymind** [comment]
Very nice work! :D Gdevelop's newIde is becoming more and more usable every day!

**Comment by 4ian** [comment]
I'm closing this issue as there is no bug (and I want to keep GitHub issues for bugs) and instead have made a card on the roadmap about showing the resource name below the images (or when hovering them): https://trello.com/c/Rrltmxda/168-display-name-of-the-resource-below-images-or-when-hovering-them

Discussion can continue here though, there is a link to it in the Trello card :)
