### ISSUE TITLE
newIde: ability to drag and drop images into a scene or automatically scan the project folder for new resources

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#631]
## Description
Adding new resources to a scene is a painfully slow multi step process that requires to be repeated on each individual image. This makes it quite laborious to get a game prototype started

## Solution suggested
I have two suggestions to make this smoother:
- Ability to drag and drop files files into the resource manager
- A button to scan for new resources within the project folder or even better - make the newIde automatically scan for new resources every time a scene is opened/loaded

**Comment by blurymind** [comment]
Might give this a try this week :)

**Comment by 4ian** [comment]
Is the multiselection when choosing an image for a Sprite not enough?

![image](https://user-images.githubusercontent.com/1280130/45386983-9fb37080-b60c-11e8-9b48-da6db118fcb2.png)
![image](https://user-images.githubusercontent.com/1280130/45386986-a4782480-b60c-11e8-9138-9ddd17b68cf5.png)

And for other objects, adding an image is a matter of 2 clicks (click on Choose a new image, then choose your file):
![image](https://user-images.githubusercontent.com/1280130/45387096-fe78ea00-b60c-11e8-99a4-45d0c417d5bf.png)

Do you think it's not fast enough? I'm not convinced it's a problem of the resource manager in any case?

I'm saying this because resource manager is still something that should normally not be seen too much by the user. It's useful to delete unused resources or change the property of an image, but ideally GDevelop would manage all of this automatically :)
This being said, might still be useful if you want to take a look at either the drag'n'drop or the automatic scan (but again, think about if it's really useful?). For drag'n'drop, I'm thinking also of something that could be, when an image file is drag'n'dropped on the scene editor, to have a Sprite object created with this image and the image filename. (not sure if it's worth it though... but might help a few users that are used to this gesture in program like Sketch/Photoshop).

**Comment by blurymind** [comment]
@4ian 
In many cases (as it is with background elements and props), you would put one image per game object. 
I use the image sequence mostly for animated objects or things like switches.

Most game engine IDEs (Unity3d, godot, cocos creator, Unreal, etc) automatically scan the project folder for new resources and do not require the user to manually select and add them.I have to admit that I kind of got used to that :D 

You are right that it is also a matter of preference. I guess in my case I don't recognise it is a big problem, but it is definitely a turn off on the initial experience of starting a project from scratch, when compared to other engines. 

On the drag and drop into scene editor that would definitely be awesome - thats a great idea! :D
Should the dropped be sprite object or a tiled image object.. or perhaps we could have a drop down menu appear to select what object?

I started implementing a 'scan for new resources' command in the resources manager btw. It's in the menu for now - with undo and redo.
I might be able to show something soon.

**Comment by MercurioC** [comment]
Sorry if it's kinda tangential, but since you're speaking of managing resources: something that I'd like to suggest is a preference setting for NOT smoothing out images added into the project by default. It's kinda annoying to uncheck every time from the manager a new file made for a pixel-perfect game, it would be a nice time saviour :)

**Comment by blurymind** [comment]
Pull request here:
https://github.com/4ian/GDevelop/pull/634
![scanresourcesgd](https://user-images.githubusercontent.com/6495061/45394103-f0d05e00-b626-11e8-933e-961536259d1d.gif)

It scans the project folder and all subfolders for png files. If a resource has not been added,it adds it and updates the list

**Comment by Wend1go** [comment]
Now all that is missing is a way to choose images either from the resource manager or the file system when clicking on the white [+] square in the sprite properties dialog.
Or as another approach show the resource manager list in a new column inside the properties tab of the sprite object. But to be useful the list of resources would need a small preview icon of the image in front of its name like in the object list.

I'm also missing this feature from GD4.

**Comment by blurymind** [comment]
@Wend1go a searchable list would be nice, but I think that for an image sequence it makes more sense to simply select it from the folder as it is now. 

My next steps to improve this for now are to add drag and drop to scene editor to create sprite or tiled sprite objects as @4ian suggested. I think that is an awesome idea - it will make it more fun to do quick prototyping with free resources from the web :D 

Adding thumbnails to the resource list would be quite nice, but might make it much more taxing to render the UI

On thing that might be problematic is the way imported resources are named. The current design seems to not allow two resources with the same name to exist. This is ok, until you have something like subfolders in your project. Consider the scenario of these two resources:
project/redParrot/idle.png
project/blueParrot/idle.png

will both idle.png files be imported? Can somebody test this please? I might be wrong, but will check after work.

One suggestion is to import them and name them as follows:
redParrot.Idle.png and blueParrot.idle.png
I wonder if I should open an issue for that and try to fix it.

**Comment by Wend1go** [comment]
It is indeed a bug. Reported it here: #635

**Comment by blurymind** [comment]
@Wend1go thank you. I will have a look tonight if I can :) 

It probably needs to be addressed for piskel too

**Comment by blurymind** [comment]
fixed #635 and also added a command to clear all unused image resources

![removeunusedimagesgd](https://user-images.githubusercontent.com/6495061/45488385-2b3a1800-b759-11e8-90fc-24619519890b.gif)

Commit coming tonight, after I get back from work :)

**Comment by 4ian** [comment]
Sweet! 👍Would you mind adding a separator in the menu between your two new options in the two existing ones (Rename, Remove), to create a logical grouping?

**Comment by blurymind** [comment]
@4ian like this? :) 
![separatormenugd](https://user-images.githubusercontent.com/6495061/45490629-87079f80-b75f-11e8-8223-c7999f6d64c0.png)

Btw I wanted to add drag and drop images to, but that might be a bigger task as there doesn't seem to be an event listener and I'm not sure where to add the event listener for drop files

**Comment by 4ian** [comment]
Cool, let me review it again :)

**Comment by blurymind** [comment]
Ok this is partly solved now. Iwill work on the drag and drop into scene next :D

**Comment by blurymind** [comment]
@4ian Do we already have something like a dropper UI component? I was wondering whether to use something like
https://github.com/mfix22/dropperx
Or it is better to use drop target and have all the drop code in scene editor?

**Comment by 4ian** [comment]
Dropperx code seems rely simple: https://github.com/mfix22/dropperx/blob/master/src/dropperx.js

We could almost recode it/include it in the `newIDE/app/src/UI` folder to avoid having a dependency.

In both case (using it or not), we should have a React component that wrap the scene editor. When it detects a drop, it calls one or more functions on the scene to add an object and add the resource (if needed) :)

**Comment by blurymind** [comment]
When there are zero instances, the menu to scan for new ones can't be called. That is kind of a problem imo :)
Maybe we should have something there when there are zero?

**Comment by 4ian** [comment]
We can have a context menu on the list I think, that should be triggered when right clicking outside of an element of the list. The context menu can have the two options to scan/remove resources.

**Comment by 4ian** [comment]
Closing this as it's an enhancement/feature request, I've created a card for this on the roadmap: https://trello.com/c/8Tpqlh2T/167-enable-to-dragndrop-image-from-the-explorer-finder-into-gdevelop-to-create-automatically-an-object-with-this-image
