### ISSUE TITLE
Use webp compression instead of png - piskel export to gdevelop

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#643]
## Description
Png files support an alpha channel, but they are huge in terms of how much memory they take.
Jpg files have no alpha channel, their compression makes them smaller-but it reduces their quality.
There is better technology out there- for many years. We should be using it.

## Solution suggested
 Webp compression can be used on png files. Webp is great for gamedev, because it has several advantages over both classic png and jpg compressions.
You can get two types of webp compression- inside a png file. Lossy or lossless. Here are some sample files:
 https://developers.google.com/speed/webp/gallery2
- lossless webp compression results in smaller png files than old png -we still have an alpha channel
- lossy webp compression results in MUCH smaller filesize than old png compression. It has greater quality and is more efficient than jpgs AND has an alpha channel

If you test some of the samples in the link, you will find that they already work in gdevelop games.

My suggestion here is for bundled piskel's file saving in gdevelop- if the original author of piskel adds support for webp compression, I will update the piskel that is embeded with gdevelop and set it to use webp compression instead of png when saving image sequences.
It should reduce a gdevelop made game's file size by 20-30% just by using webp lossless compression in png files instead of the standard one.  I know the games are tiny to begin with, just thinking it would be beneficial when exporting to mobile

Filed a request at piskel's tracker as well:
https://github.com/piskelapp/piskel/issues/847

**Comment by 4ian** [comment]
This looks rather like a feature request for Piskel right?
Also a few questions: 
* what is the support for this format on desktop browsers?
* what is the support for this format on mobile, especially old Android versions or iOS?

Looks like the support for this format is tied to the browser support, so nothing much we can do? As it's not very actionable I would rather close this issue and push forward this format for Piskel, if you think it's worth investing time in it (depends notably on the stats I was asking about :)).
If at some point webp is used widely *and* supported properly by all major browsers without bugs, then I think we'll be able to make pull requests for adding explicit support for it in GD (while choosing a file for example).

**Comment by blurymind** [comment]
I tested with files in the link:
https://developers.google.com/speed/webp/gallery2

Notably the flower example seems to work fine on desktop games, but I haven't tested it on mobile export yet.

It will be great if others here help test on different devices.
The format was developed by google, so it's same to assume it works on android, but not sure about IOS.

Piskel's developer is adding it as an export option

**Comment by 4ian** [comment]
Looks like support is on its way but not available everywhere yet: https://caniuse.com/#feat=webp

In particular no support in Safari desktop nor Safari iOS, Firefox and Edge. "Both Safari & Firefox are experimenting with supporting WebP images" so things will improve.
It's a good thing that Piskel is adding support for it and that GD is ready to work with this once it's widespread, but for now as adoption is ~75% of the browser market it's too early to advice people to use it.

> so it's safe to assume it works on android

Ahah, beware of compatibility for Android. For having worked for a few years on mobile apps on Android I can tell that something that is new and "should work" is always bug crippled for a few time because of old Android versions :) Might be better since Android 5+, but for example Android 4.x was bundled with a system webview that was not Chrome and full of bugs for years. As we can see with the bug reports concerning strange flickering, support still varies amongst mobile. The conclusion of all of this: we have to be super extra duper careful before stating that something work.

**Comment by blurymind** [comment]
Ah I see. In that case I guess it should stay optional and not the default

**Comment by 4ian** [comment]
Yes - having the option in Piskel is good but should be a choice from the user :)
Can we close this issue for now?

You can reopen it in one year or more to reconsider the default format when adoption is >95% and only IE11 is not supporting it ;)

**Comment by blurymind** [comment]
Ok closing it :)
