### ISSUE TITLE
High-Speed Collision Detection Limitation

### ISSUE THREAD

**Issue by FrostyFlame1** [4ian/GDevelop#6491]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

When the speed of objects is significantly increased, the collision detection fails. In my case the  issue begins to occur when I set the scale to around 71 pixels per meter. Despite using the bullet option and implementing raycasting, the issue persists. 

### Steps to reproduce

link to the game: https://gdevelop.io/game-example/free/spherez

### GDevelop platform

Desktop

### GDevelop version

5.3.195

**Comment by AlexandreSi** [comment]
Hi @FrostyFlame1,
Thanks for opening an issue.
I'm not surprised by this result: there is a compromise to find between a performant game and a correct simulation. And if the speed is significantly increased, this compromise might not be satisfying.
Have you seen a different result in other engines?

If you want to discuss about the values between the word "significant", I recommend you publish a game on gd.games with a control on the scale and a test case so that we can have solid grounds during the discussion.

**Comment by tristanbob** [comment]
@FrostyFlame1 I'm the one who made that Spherez template, which uses the Physics behavior (powered by Box2d)

Box2d uses continuous collision detection (CCD) for dynamic objects against static objects, so it should never miss.
The "bullet" setting also enables this CCD between other dynamic objects.

What do you mean by "collision not detected"?  Are you using Physics collision or non-physics collision conditions?  The non-physics condition only triggers when the objects happen to be touching during the frame (no CCD).  My first guess is that you are using the wrong condition.

**Comment by FrostyFlame1** [comment]
I am using the Physics collision condition. When I changed the position of the specified event, the issue was resolved. So, the issue is not caused by the physics engine.

I deeply apologize for reporting this as a bug. and I am so grateful for your time and assistance.
