### ISSUE TITLE
colision doesnt work on large rotated platforms

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#676]
## Describe the bug
Putting aside that you can't actually rotate any instances atm, if you do try to do with the event sheet ,
their collision no longer works

## To Reproduce
Do +5 to angle of the tiledgrass platform at the start of the scene

You will get this:

![tiltedplatformsgd](https://user-images.githubusercontent.com/6495061/46248395-a31e6880-c410-11e8-874d-b8639a6881f4.gif)

**Comment by blurymind** [comment]
It does work on a smaller platform, but the player can only go down the slope. You can't walk uphill :)

**Comment by 4ian** [comment]
> sparkman recently made a video

This video is from 2017 ^^ Is that the one you wanted to link?

But anyway: 
- titled platform should work.
- it seems that there is an issue with collision boundaries on large/scaled/titled platforms.

**Comment by blurymind** [comment]
ah yes sorry you are right. Youtube decided to recommend it to me today xD
Increasing the slope indeed fixes it. 

I wonder why very big platforms mess up the collision

**Comment by blurymind** [comment]
if we have slope, wouldnt it be nice to be able to rotate platforms in the Ide?

**Comment by Lizard-13** [comment]
I think it shows the problem better:
![platformer-bug](https://user-images.githubusercontent.com/9782647/46251559-ed611300-c42b-11e8-8a14-4db734f9bed8.gif)
The blue line is imaginary, I guess it's the platform top surface when it isn't rotated, so there's a code that uses the non-rotated Y position of the platform, then the separation algorithm fixes it until the object is pushed down instead up like at the end of the gif.

**Comment by 4ian** [comment]
> if we have slope, wouldnt it be nice to be able to rotate platforms in the Ide?

You can with the "Angle" property in the property panel ;)

> The blue line is imaginary, I guess it's the platform top surface when it isn't rotated, so there's a code that uses the non-rotated Y position of the platform, then the separation algorithm fixes it until the object is pushed down instead up like at the end of the gif.

Great catch! Somehow there must be something wrong with the way the engine get the potential colliding objects.. might be `_updatePotentialCollidingObjects` called with a bad `maxMovementLength`.

**Comment by blurymind** [comment]
@4ian would you be open to the idea of adding rotation to the resize/move instance widget?  :) 
I can give it a try some time, if nobody else picked it up

**Comment by 4ian** [comment]
Yes, it was mainly not done because of no time for it. :)
Created a card for it on the trello: https://trello.com/c/cMYnMyTb/165-add-a-rotation-handle-in-addition-to-resize-handles-on-scene-editor

As for multiselection if that's easier you can start by rotating individually each instance without moving. Ideally move and rotate would be easier but that's a bit more fun work with `cos` and `sin` ;)

**Comment by blurymind** [comment]
I noticed that the resize sprite pixi is not used at all by the button. I
can fix that while at it if you want :p

**Comment by 4ian** [comment]
Ah yes true, feel free to remove it :)

**Comment by blurymind** [comment]
I think it should be its own button to make it easier on touch input
devices in the future :D

**Comment by 4ian** [comment]
Good remark, let's good for the circle - that what used to be in GD4 and I think it's quite understandable and useable :)

**Comment by 4ian** [comment]
So I found the issue, it's because the code to check what platforms are around the character (`_updatePotentialCollidingObjects`, which is using `gdjs.PlatformObjectsManager.prototype.getAllPlatformsAround`, which is calling `this._platformRBush.search`) is using a specific structure ("rbush") to store platforms positions in an efficient way. But only the bounding box is used meaning that rotated platforms won't be properly considered. (so that the character is moved into them, then moved out).

We'll have to come up with a better solution that using bounding box. Potentially have bounding boxes that are larger enough to contain the rotated object.

**Comment by 4ian** [comment]
Potentially a solution is in gdjs.PlatformObjectsManager to replace the ".owner.getAABB()" by a call to a function "getExtendedAABB()", and implement gdjs.PlatformRuntimeBehavior.prototype.getExtendedAABB to return a bounding box that is large enough. (and also remove gdjs.PlatformRuntimeBehavior.prototype.getAABB which is dead code it seems).

**Comment by 4ian** [comment]
Pull request coming that fix at the same time a bunch of collisions related features and improve performance.

**Comment by blurymind** [comment]
@4ian Thank you for the fix 😸
