### ISSUE TITLE
newIde - add a rotation widget to instances editor selections

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#687]
## Description
Following up from discussion in https://github.com/4ian/GDevelop/issues/676 we have an angle property in instances, but no way of intuitively rotating them when they are selected

## Solution suggested
I would like to try and add a rotation widget to make it more intuitive to manipulate the angle of selected instances

**Comment by 4ian** [comment]
As it's a new feature, can we rather make a card in the trello board?
I don't want to clutter "Issues" with things that are not issues but new features.

Discussion can happen on the trello card and then on any PR that is opened for it

**Comment by blurymind** [comment]
Yes of course :) not sure if im allowed to add cards to trello though

**Comment by blurymind** [comment]
We still have the 'New feature' template option when creating issues too

**Comment by 4ian** [comment]
> We still have the 'Feature request' template option when creating issues too

True. I see the "issues" that are feature requests as issues where we should:
1) Is there a card for this already? If no => add it and a link to it on the issue.
2) Close the issue.

Discussion can still happen on the card, or on the issue.

But what I'm trying to have is the Trello roadmap as the "go to" place when it comes to new features, and keep Issues only for bugs. Bug meaning something that does not work and prevent user from doing something or a game from working.

It's already there btw: https://trello.com/c/cMYnMyTb/165-add-a-rotation-handle-in-addition-to-resize-handles-on-scene-editor

I understand that it might be silly at first sight to have all feature requests, even the "tiniest" one like this on Trello but remember that:

1) For non technical users, the Trello is a better place rather than this strange Github "issue" page.
2) It avoids mixing bugs and feature request here.
3) The Trello board has the advantage to show everything on a single board, which is a great way to communicate to users that they are already a *ton* of things that can be done, so choices have to be made.

Of course some card on the Trello can be much more simpler (adding a rotation widget is simpler than adding a 3D engine in GDevelop for example ;)), but that's also a good thing to show to users: we are able to work on tons of small but super useful features.

> not sure if im allowed to add cards to trello though

You're a member of the trello board so you should be able to :)

I'm closing this task as there is already a card :)

**Comment by 4ian** [comment]
Also a great advantage of Trello is that we can move the card to "Planned" and "Doing" and then "Ready for next release" to give everybody an overview of what we're doing :)
(GItHub added a similar feature in the tab "Projects", but Trello is still more friendly for users so we'll keep using it and this allow to keep only bugs in GitHub).

**Comment by blurymind** [comment]
@4ian I went with rendering a circle in the end- to stay consistent with the other buttons
![capture](https://user-images.githubusercontent.com/6495061/46582449-bba90700-ca3e-11e8-8e49-d1408661cdd9.PNG)
will that be ok?

**Comment by 4ian** [comment]
That looks ok yeah! :)

**Comment by blurymind** [comment]
Made a pull here
https://github.com/4ian/GDevelop/pull/691
