### ISSUE TITLE
The event condition 'Escape key is pressed' is not working.

### ISSUE THREAD

**Issue by AwesomePaper** [4ian/GDevelop#697]
The event condition 'Escape key is pressed' is not working. But, if using 'any key is pressed' and press Escape key, it works. Can't I use 'Escape key' when i make games?

**Comment by zatsme** [comment]
It works for me, what are you doing exactly?

**Comment by AwesomePaper** [comment]
I want to make a game that if i press 'Escape' key, the game stops and view menu. For reference, I'm making a web game.

**Comment by Wend1go** [comment]
I can confirm this. Neither "Key pressed" / "Key released" nor "Key pressed (text expression)" / "Key released (text expression) work with "Escape". All other keys are working fine.

**Comment by zatsme** [comment]
Sorry, I thought I was using Esc in one of my games but I wasn't :(

**Comment by 4ian** [comment]
The handling of this key was missing, it's fixed for next version!
Thanks for reporting it.

If you absolutely need this for now, you can add a Javascript event, launched at the beginning of your game, containing:

```javascript
gdjs.evtTools.input.keysNameToCode["Escape"] = 27;
```

This will "patch" the missing key in the game engine.
![image](https://user-images.githubusercontent.com/1280130/46975853-a166cd00-d0bf-11e8-8911-dc5ce75d481a.png)

**Remember to remove this "hack" once the new version is out** because it could not work in a future version :)

**Comment by zatsme** [comment]
lol, was just looking at the code to see what might be going on and then see 4ian fixing it :)    I knew it was probably working on keycode .. i.e. 27 for Escape and that led me to wonder if it might be useful to expose keycode as an option in the IDE?
