### ISSUE TITLE
Variables crash

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop#7129]
### Describe what you were doing when the crash happened

**1-** Create a new object (any type).
**2-** Open events.
**3-** Use Condition or action object variable.
**4-** Declare that object variable.
**5-** Delete the object.
**6-** Go back to events.
**7-** Select the variable and click (Add or edit variables).
**8-** Crash !

### GDevelop version

Latest released one (auto update not manual)

**Comment by ClementPasteau** [comment]
Thanks for reporting @VegeTato 

I can reproduce this with easier steps:
- create an empty project
- add an action "Change variable value" for objects
- do not fill the object name / put anything in there
- click on either the "variables icon" or the "+ add or edit variables" in the variables field

The problem comes from the `ObjectVariableField` opening up the `ObjectVariablesDialog` even if the objectName may not link to an object.


https://github.com/user-attachments/assets/66ecf169-6e1c-44f6-a0d0-2a816f587cd4

Error is `Cannot read properties of undefined (reading 'resetPersistentUuid') in useSerializableObjectsCancelableEditor`

**Comment by ClementPasteau** [comment]
Should be fixed in next release, thanks :)

**Comment by Davi-Fiorini** [comment]
What are you guys talking about? I didn't report VegeTato.

Em qua., 6 de nov. de 2024 9:50 AM, Clément Pasteau <
***@***.***> escreveu:

**Comment by Davi-Fiorini** [comment]
I didn't even know you could report users in GDevelop

Em qua., 6 de nov. de 2024 10:34 AM, Aluno Selecionado <
***@***.***> escreveu:
