### ISSUE TITLE
[Piskel] Unhandled exception

### ISSUE THREAD

**Issue by rikazukun** [4ian/GDevelop#726]
## Describe the bug
I'm not sure if I should be making a report here, but since it is integrated on GD (and I believe it can be done here since it's the GD button itself that creates the instance of Piskelapp) I might as well make one in case this bug/instance isn't known.

## To Reproduce
* When you double press (fast) [Edit with Piskel] button on the Object panel. It will create 2 instances of Piskel, (I guess it doesn't have a checker if an instance already exists? Or if it is allowed to have multiple instances, it would be nice to just make it 1). If you close the first one, you won't be able to close the other one and will get an error, that the other instance cannot be destroyed/removed since it is already considered as null. 
(In my case I was able to get this error, because of my broken mouse that randomly double clicks when I press it once)

![123](https://user-images.githubusercontent.com/41359801/47914061-2bdd6800-ded9-11e8-8afa-34573767666c.JPG)

**Comment by blurymind** [comment]
Yes indeed, I introduced this bug when adding jsfx and noticed it while replacing it with jfxr, 
#716 fixes it.
I will do some refactoring to Piskel soon too

**Comment by rikazukun** [comment]
I see, my bad I didn't check that pull request.
Thanks
Closing~

**Comment by blurymind** [comment]
Hi no worries. You can keep the issue open until the fix is merged :)
Actually i would be greatful if you test gd after the merge and report if
it fixes it for you as well

**Comment by rikazukun** [comment]
Sure

**Comment by blurymind** [comment]
This should be fixed now :)
Can you try it on the latest master branch?

**Comment by 4ian** [comment]
Should be fixed in GD5 beta 56. If it's ok let me know so that the issue can be closed :)

**Comment by rikazukun** [comment]
Yes it is fixed now, @blurymind

**Comment by 4ian** [comment]
@rikazukun Totally unrelated to this topic, but I've seen that you added information about electron-builder in the wiki. This is fine but you've not finished the explanation, meaning that we had a page about electron with incomplete information/incomplete sentence on the wiki.

I've removed the changes for now: please only do complete and proof read addition to the wiki :) It's very very important because the wiki is the official documentation, and this is what everyone using GDevelop is reading. If it is incomplete, this will reflect badly on GDevelop and will look very unprofessional (and in fact people already criticized GDevelop for it).
