### ISSUE TITLE
Memory consumption constantly rising with scene editor open

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#728]
## Describe the bug
The memory consumption of GD5 Beta 50 and newer versions (Beta 48 and lower are not affected) rises by about 1% point per second when the scene editor is open on my test VM.
After a while actions like dragging the view or selecting an instance become sluggish and get performed after a delay of several seconds until the IDE stops responding and has to be killed.
The events editor seems to be not affected by this. If you manage to activate the events tab before it stops responding the memory rapidly drops to the usual level of around 6% and working with events is smooth as normal.
This happens on a VM with a Linux Mint 18.3 / 64 Bit / 4GB RAM. But might also happen on low spec PCs.

## To Reproduce
1) Start GD5 IDE (Beta 50 or newer)
2) Open a test game
3) Open a scene
4) Leave it running for some time -> Memory consumption rises about 1% point each second

* Testgame:
[dungeon.tar.gz](https://github.com/4ian/GDevelop/files/2547501/dungeon.tar.gz)
This test game is nothing fancy, just 10x10 sprite objects.

## Other details
The issue is **not** present on my main developing machine (also Linux Mint 18.3). Looks like it only affects machines with crappy hardware. The bug was introduced with Beta50, the test game runs smoothly in older versions of GD5 in the same VM.

GD5 Beta 48:
![gd48_dungeon](https://user-images.githubusercontent.com/7413059/48001773-d76cff00-e109-11e8-8b10-deef2cbf8a79.png)
Looks ok

GD5 Beta 55:
![gd55_dungeon](https://user-images.githubusercontent.com/7413059/48001778-da67ef80-e109-11e8-8be4-b89870ea6844.png)
The red markings are all "animation frame fired (raven.js: 1086 recurring handler took (60-100ms))
 (unfortunately I can't upload a report since even 10sec of profiling is around 100MB in size)

EDIT:
So raven.js is for error tracking. The VM doesn't have internet access. Maybe it is constantly stacking reports in memory that the script is unable to send.

**Comment by 4ian** [comment]
Looks like the VM does not support webGL as drawImage/renderCanvas is called.
This being said the CPU consumption seems really too high for it in the second screenshot.
Memory consumption looks ok in the graph - all numbers are actually lower in the second screenshot.

Pixi.js (used for rendering) was not updated between Beta 48 and the latest.
I wonder if this can be due to an error during the rendering (are there any error message showing in the console?), that would keep memory increasing. I wonder if that could also be the fault of faulty graphics drivers.

> (unfortunately I can't upload a report since even 10sec of profiling is around 100MB in size)

If you can host it on something like Dropbox/one drive/Google Drive that would be helpful to see if something is obviously wrong to me :)

**Comment by 4ian** [comment]
At least if you could upload a report of 2 seconds that would be useful to see where time is being spent during these 2 seconds on the scene editor :) (no need to wait for freezing, a few seconds is ok)

**Comment by Wend1go** [comment]
The performance has never been great since the Virtual Box driver can only achieve OpenGL 2.1 via software rendering, hence the high CPU load. But it was still enough to work on my projects.

I installed a new VM with Manjaro (all updates installed, newest kernel and up to date guest additions) and I get the same result as with the old Mint18.3 VM.

Here are the profile files (Zipping the files did wonders with the size):
[Profile-LM18.3.json.tar.gz](https://github.com/4ian/GDevelop/files/2552873/Profile-LM18.3.json.tar.gz)
[Profile-Manjaro17.json.tar.gz](https://github.com/4ian/GDevelop/files/2552874/Profile-Manjaro17.json.tar.gz)

**Comment by 4ian** [comment]
On the Linux Mint profile, all I can find for now is this:

![image](https://user-images.githubusercontent.com/1280130/48318807-8a9f9180-e5fd-11e8-8156-6b7e798e0ee5.png)

A call to drawImage, to render an image on the canvas, which takes ~30ms every frame, which is huuuuge. Honestly no idea for now what's causing it. I've not updated Pixi.js since a few versions so don't think it's because of it. It is possible that before beta 48, an older version of Electron (that is used to run GDevelop) was used (I upgraded it fairly recently as far as I recall). But this should not make things worse like this - unless the Chrome rendering/JS engine became less compatible with VM. Or maybe it triggered a bug where memory for rendering is not deallocated.

But all of these are hypothesis and it's hard for me to be sure what's happening :/

**Comment by Wend1go** [comment]
Thank you very much for looking into this. This bug is really a huge hindrance for my development.
What would I have to do if I wanted to build the newIDE myself with a specific version of electron?
(Or are we already using functionality that is only available in the newer version?)

**Comment by 4ian** [comment]
You should git clone the repository, install Node.js/development tools as explained in the [README](https://github.com/4ian/GDevelop/tree/master/newIDE).
In newIDE/src/electron-app/package.json, downgrade electron to version 1.7.9 used previously: https://github.com/4ian/GDevelop/commit/5c19c9bb1473694dc0099a08480631b622d7709e#diff-ccffc71bb560ad41db44189ced93db0dL38

Then run the standalone app running on Electron by [following this section](https://github.com/4ian/GDevelop/tree/master/newIDE#development-of-the-standalone-app).
And see if it's better.

The context menu API of Electron has slightly changed so you should also undo the other changes mentioned in the commit https://github.com/4ian/GDevelop/commit/5c19c9bb1473694dc0099a08480631b622d7709e

Note that it may also be a good idea to test with a more recent version of Electron. This might be a bug in the version of Electron being used currently that was fixed already. This happened for other issues (like flickering on some computers).

So I would advise by testing version 3.0.8 (latest stable release on https://github.com/electron/electron/releases):

```
git clone https://github.com/4ian/GDevelop.git
cd GDevelop/newIDE/app
npm install
cd newIDE/electron-app
(modify package.json in newIDE/electron-app to put 3.0.8 as the electron version)
npm install

# finally run the app:
./node_modules/electron/dist/electron app #for linux
```

**Comment by Wend1go** [comment]
I have built a version with electron 1.7.9 and 3.0.8. Will test them tomorrow in the VM and give you feedback.
For what I can say already is that 3.0.8 seems to run fine on my Linux desktop. Will test it more thoroughly in the coming days.

**Comment by Wend1go** [comment]
The test was successful. Both 1.7.9 and 3.0.8 run at full speed and without any issues in the VM.
From the Linux side upgrading GD5 to Electron 3.0.8 is free to go. 👍

**Comment by Wend1go** [comment]
I Noticed that 3 days ago Electron 3.0.9 was released.
Just tested it and it works well too.
Would be cool to upgrade Electron before GD5 Beta 57

**Comment by 4ian** [comment]
Cool, will probably upgrade to latest version then!

**Comment by blurymind** [comment]
@Wend1go good catch 👍 
@4ian thank you for fixing it so quickly
