### ISSUE TITLE
Copy an image on a sprite

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#737]
Copy an image on a sprite was previously in GDevelop 4, in the "effect" sub-menu of sprites, but it seems that it's not in GDevelop 5. Is it planned or is it possible to add it to the roadmap?
Thanks!

**Comment by 4ian** [comment]
I'm not planning it because this implies to create a texture in memory, then paste another by copying all its pixels, which is slow and quite inefficient (as you're creating textures which can quickly make performance go down) if used a lot.
This being said, I've added a card on the roadmap to see if there is any interest: https://trello.com/c/F2xG2QqI/186-support-editing-textures-during-the-game-by-pasting-images-other-textures-on-top-of-an-existing-one

I'll close the issue as we're only keeping bugs opened :) Discussions can continue here

**Comment by 4ian** [comment]
Yes that's a good solution. I don't think that's worse - most probably it won't change anything at all to the performance of your game - unless you have dozens of thousands of objects (in which case you'll want to prepare textures on your side). Could even be better in some case (like if you have a lot of different textures, graphics card can actually reuse the same texture for the logos instead of having in memory dozens of different textures)

**Comment by timotheeficat** [comment]
Ok then, thanks for your help!
