### ISSUE TITLE
Function event: some extensions used in functions are not included in preview/export

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#745]
## Describe the bug
If you try to change an animation of a sprite object inside a group via name from within a function it crashes the game.

## To Reproduce
1. Open the "Player" function extension in the example game
2. Open the "_Items" function
3. Changing the animation by name crashes the game (see screenshot)
The same logic works in the scenes event sheet (disabled in the example)

## Example
[dungeon_function_error.tar[1].gz](https://github.com/4ian/GDevelop/files/2581074/dungeon_function_error.tar.1.gz)

## Other details
![error_console](https://user-images.githubusercontent.com/7413059/48488437-09c0df80-e821-11e8-85d1-d701d6b826d5.png)
![error_logic](https://user-images.githubusercontent.com/7413059/48488438-0a597600-e821-11e8-9e92-b3b93376846d.png)

**Comment by 4ian** [comment]
So I took a look and this is due to the usage of the Inventory action.
As Inventory is not used in the scene, it seems that the extension is not included when exporting/previewing the game.
This is strange because it should work, extension used in functions should also be included automatically when using a function.

Anyway for now there is a workaround: create an event (that you can disable) in the scene using a dummy action from the Inventory extension (anything will do). This should be enough to include inventory when previewing/exporting.

**Comment by 4ian** [comment]
Update: so using extension works, but not if you have functions including other functions that are themselves using extensions. In which case you have to resort to the workaround of adding a dummy event in the events sheet of the scene to force the extension to be included.
