### ISSUE TITLE
Discussion: Function events

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#746]
I'd like to start a little discussion about the function events and get to know the opinion of others.

All in all I'm pretty happy with it. The functions enable one to structure a game in a pretty nice way.
There is one thing though. I tried to use the Function events to encapsulate the logic of game entities. Since I have to set all objects I want to interact with as parameters I have to add them to groups in order to keep the number of parameters low.
So to make the player check for solid objects for example, I need to bundle them in a group and pass them as a parameter, same for collectibles, enemies etc.
I know the function extension is designed to add additional functionality to game objects with portability in mind but when I try to use it in you own game to get a better structure the encapsulation is hindering me a little bit.
It would also be nice to hide some functions in an extension from the public that are only used internally.
Maybe every function that starts with an underscore is only visible from within the extension.

**Comment by 4ian** [comment]
> Maybe every function that starts with an underscore is only visible from within the extension.

That's a really interesting idea, this mimics the way some programming language distinguish between private and public methods (well it's a convention)

> I know the function extension is designed to add additional functionality to game objects with portability in mind but when I try to use it in you own game to get a better structure the encapsulation is hindering me a little bit.

I understand, functions are indeed totally abstracted from the game so they can't access anything. This can make them a bit "heavy" to use because you have to pass a lot of parameters.

In programming language, there is an "intermediate" way of doing functions (if I may say so) which is called "closure". Closure are functions that in addition to being called with parameters, can also capture automatically variables that are in the scope where they are declared. Example, instead of doing this:

```js
function getResult(a, b, c) {
    return a+b+c+d;
}

a = 3;
if (something) {
    b = 4;
    getResult(a,b,5); //Will return 12
    getResult(a,b,6); //Will return 13
    getResult(a,b,7); //Will return 14
}
```

You can do:
```js

a = 3;
if (something) {
    b = 4;
    function getResult(c) {
        return c;
    }
    getResult(5); //Will return 12
    getResult(6); //Will return 13
    getResult(7); //Will return 14
}
```

So it's an interesting concept. This being said for now all functions in GD are "globally" available (the way it works is that it creates extensions on the fly for these functions).
Not sure how "capture"/closures would translate in GDevelop

> Since I have to set all objects I want to interact with as parameters I have to add them to groups in order to keep the number of parameters low.

In a way, this forces you to create more structure in your game, by grouping objects with related semantic and forcing you to find a good name for your groups ;)

**Comment by 4ian** [comment]
Closing as functions are now available in custom extensions made with events.
