### ISSUE TITLE
Extend Particle system with spawning method

### ISSUE THREAD

**Issue by timotheeficat** [4ian/GDevelop#762]
For now, a particles emitter will generate particles at its position for a frame.
A problem appears when the emitter is moving at high speed.
Because of the framerate, you will see each position where the emitter create a stack of particles and holes will appears in the flow of particles.

The emitter should generate particles between its last position and its new position to avoid this behaviour.

**Comment by 4ian** [comment]
What speed is going your particle emitter at? If the game is running at 60 fps, and your emitter going at 1000 pixels per second, particles will be created every 16 pixels. If you radius of creation is at least 16 pixels, this should not be noticeable.

Can you try increase the radius?

**Comment by timotheeficat** [comment]
I don't really have a speed limit and my emitter has only a radius of 3 pixels.
I know this sounds a bit extrem but the emitter is from the engine of a spaceship that could travel really fast.
I tried to put the emitter on another layer to prevent this, but the result is not exactly as expected.

I know that some particle systems generate particles between the last position and the new one.
Also, I could implement this behaviour by myself but I don't really understand the structure of the extension. In what file should I try to modify the emitting function ?

**Comment by 4ian** [comment]
Probably you're searching for this file: https://github.com/4ian/GDevelop/blob/master/Extensions/ParticleSystem/particleemitterobject-pixi-renderer.js#L78

> I know that some particle systems generate particles between the last position and the new one.

You could emulate this by changing the spawning area so that it's a rectangle between your old and new position.

Particles are generated using pixi particles. You probably want to use `spawnType: 'rectangle'` (see https://github.com/pixijs/pixi-particles/blob/master/src/Emitter.ts#L196) and have a `spawnRect` in the configuration (according to what I see here: https://github.com/pixijs/pixi-particles/blob/master/src/Emitter.ts#L622).

BUT this is not going to work if your spaceship is rotated (because I don't think there is support for rotated rectangles as a spawning area).

Maybe another way to do it is:
- Create multiple emitters like 3 or 4, and divide the number of particles created by each by 3 or 4 too.
- Then, put the emitters behind your spaceship
- Then put every emitter a bit behind the spaceship, with some space between each one. The faster you go, the longer the distance between each.

This should simulate particles being created on a long distance :)

You can use the action Put Object around a position for each of the emitter. As a position, put your space ship position, and the spaceship angle. Set the distance so that it is behind the spaceship. Put a bigger distance according to the speed of the spaceship and the number of the emitter.

For example, distance could be 100 + Spaceship.Speed() / 100 for first emitter, 100 + Spaceship.Speed() / 60 for second emitter. This way, if speed is 0, they are at the same place. If speed is 1000, they will be at 1000/100 - 1000 / 60 = 6.666 pixels from each other. 

Of course this is in theory, you have to do test, maybe it won't look good.

**Comment by timotheeficat** [comment]
Both solutions looks good!
Thanks for your help, I will test these soon!
