### ISSUE TITLE
Problem with the scroll bar handle of the editor.

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [4ian/GDevelop#793]
## 

Problem with the scroll bar handle of the editor. I can't go all the way or expand the playing area. I have to zoom in to see the whole scene.

1. Open space shooter example
2. Move the scroll bar handle at the top right
2. Zoom out

Even with zoom, it is sometimes quite difficult to reach the top right part of the scene on the screen.

![capture](https://user-images.githubusercontent.com/19731340/49802453-3814da80-fd4d-11e8-9482-6c6036ce5b15.PNG)

* Windows 7 64 / Gdevelop 5 Beta 58

**Comment by blurymind** [comment]
You can mid click to pan, but also alt+scroll will do exactly what you need here. Ctrl + scroll with do it vertically

**Comment by Silver-Streak** [comment]
Scroll bar functionality has changed (now at bottom of screen rather than top, new scrollbar types, etc) and this behavior no longer appears to be accurate, you can keep scrolling past the current "max" and the bar adjusts (even if the selector bar stays to the right, you're still moving). Closing this out.
