### ISSUE TITLE
newIde resource manager - ability to remove paths or update paths to deleted/moved files

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#810]
## Description
Sometimes the user might delete or move some placeholder resource files. The resource manager will still have them listed, but it will not become obvious to the user which ones in the list are invalid paths and there is no command to remove all the invalid paths.

## Solution suggested
This issue can be easily addressed by:

- [x] Adding color indication in each item in the list for paths that are invalid
https://github.com/4ian/GDevelop/pull/818
- [x] Adding a command that removes all resources with inexistent paths
https://github.com/4ian/GDevelop/pull/810
- [x] Ability to set/update a path on any resource that is already added - so we can relink files that were moved while keeping their resource logic
#822 

trello
https://trello.com/c/RNI2jEqt/216-resource-manager-command-to-remove-resources-with-paths-to-deleted-moved-files

**Comment by 4ian** [comment]
Maybe coloring/adding an icon would be a good first step. Could you create a card for it in the Trello and had a link to this issue (then close the issue)?

**Comment by Wend1go** [comment]
Marking all assets that don't reside in the project folder would also be nice.

**Comment by 4ian** [comment]
Yes, I guess missing files should be red (that's an error) and files not in project folder should be a warning (because it makes the game less portable).

I look forward to add more of these error/warning messages in GD, for example to warn about images that are too large or similar "antipattern"/risky things. Would help a lot of users I think.
For this to be consistent, I think we need to agree on an icon (I think there are already warning and errors icons in material ui icons) and a color (the new expression parser will add the "red" error color). 
This considerations being said, it's perfectly fine to start adding warning and we can factor them using the same colors/icons as we add them.

**Comment by blurymind** [comment]
I created a command to remove them, will do a pull tonight. The coloration will be added in another one

**Comment by 4ian** [comment]
Coloration is a bit more work to do. 1) ideally you can add colors in the theme (DefaultTheme/index.js and DarkTheme/index.js) and then pull it when needed using ThemeConsumer and 2) you should surely enhance/modify `SortableVirtualizedItemList/index.js` (and/or `ItemRow.js`) to have items that can be marked as having error or warning.

These changes can be ported later to other list (ideally, all lists would use `SortableVirtualizedItemList` - but for now objects list and groups list are still implemented differently) so that we can add error/warning on objects later ;)
Having the color in the theme would also allow to reuse them for warnings/errors presented as messages in other parts of the software (like the error color for expression parser, maybe later for warnings about events, etc...) (I'd like to add warning when you're doing an "anti pattern" with events, like launching a music without conditions).

**Comment by blurymind** [comment]
I added the missing resource path color hinting with theming support. This is how it looks like 
![errorhinting-gdresourcemanager](https://user-images.githubusercontent.com/6495061/50289316-5d49cd00-0460-11e9-9558-ffc7abaa3286.gif)

Pull coming up tonight :)

**Comment by blurymind** [comment]
One thing that I thought would also be very useful to have is a command to set the path of a resource- so for any moved resources we can keep our connections in the project, but update their paths.

I could do that in another pull if it sounds good?

**Comment by 4ian** [comment]
@blurymind Changing the path of a file is useful, but unless I'm mistaken you can already update it:

![image](https://user-images.githubusercontent.com/1280130/50376108-e8fe5d80-0608-11e9-93e4-74f7a0191b2a.png)

Though a button to choose/edit the file would be useful :) (the same as when you can open Piskel or Jfxr... in short the same buttons to open the external editor as the one already existing :))

**Comment by blurymind** [comment]
@4ian you have to type the relative path, which is neither convenient nor intuitive :) I was thinking more in the lines of navigating to the file

**Comment by blurymind** [comment]
ok this can be closed now :)
