### ISSUE TITLE
Shift keys doesn't work

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#820]
## Describe the bug
LShift doesn't work, and RShift works but with the Shift key on left of the keyboard

## To Reproduce
Try to assign LShift on an action > nothing happen
Try to assign RShift on an action > RShift dosen't work, but LShift work instead RShift

## Other details
GD5 v61 Windows and editor.gdevelop-app.com

**Comment by zatsme** [comment]
Tested this, LShift doesn't seem to work at all, but if you test for RShift or "RShift" then both Left and Right shift work.  Missing definition somewhere?!

**Comment by Lizard-13** [comment]
Yup, right here:
https://github.com/4ian/GDevelop/blob/87acba510592285bea261594e1c9e19b773edbe4/GDJS/Runtime/events-tools/inputtools.js#L122-L125
Both "LShift" and "RShift" should share the same code `16`, give it a try :)

Note that they share the same code, hence GD can't differentiate if you're pressing left or right shift because hasn't been designed to read an extra property that allows this.

**Comment by zatsme** [comment]
Errrrrrr,  Lshift is 1 in the code which is why its not working.  Are you seeing things 😂

**Comment by KinkGD** [comment]
@Bouh @4ian 

Rshift and LShift now share the same code. 
So basically it's repaired, but it makes no sense to have to the two options in conditions key release or key press : User should have only the possibility to select "Shift" for both left/right keys ?

**Comment by PascalLadalle** [comment]
I just noticed this bug (redundant L/RShift). It would be nice to have both, though. These are useful keys, because of their position on the edges. 
I'm doing a two-player shared-keyboard game, like back in the days so, excuse the pun, but each key is key. 😅 
Is it too much trouble?

**Comment by geetesh-gupta** [comment]
So, finally what should has to be done? Should we have separate keys or same keys?

**Comment by Bouh** [comment]
Ideally shift left and shift right, should be two different button, same for ctrl and alt.
Because actually key code are same.
https://github.com/4ian/GDevelop/blob/master/GDJS/Runtime/events-tools/inputtools.js#L121

**Comment by NilayMajorwar** [comment]
I want to work on this issue. Here's my understanding of the problem:

Since LShift and RShift share the same `keyCode` and differ only in `event.location`(0 for general, 1 for left-modifier, 2 for right-modifier, 3 for numpad) and `event.code` (string, like "ShiftLeft"), we can't solve the issue just with key codes, and need some other way to represent keys uniquely, right? 

If yes, I see two options - represent keys uniquely with `event.code` , or with a combination of `event.keyCode` and `event.location`.

The GDJS InputManager uses a hashmap (with key as `event.keyCode`) to store keys status, so the unique determiner has to have a primitive type. So `event.code` seems like a better option.

Do I see it right? Or is there a better way?

**Comment by 4ian** [comment]
I'll let you find the clearest and fastest solution (being fast being the most important as this is a very used function). code might be a good idea, though might be good to investigate if event.location is just as good. 

We can do a second hashmap or special cases for this kind of key - up to you :)
