### ISSUE TITLE
Object & scene timers have different ordering of parameters

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#843]
## Describe the bug
The 'Value of a timer' and 'Value of a scene timer' have a different ordering of their parameters (e.g. 'Time in seconds' & 'Timer's name') which means switching between them causes a syntax error.

## To Reproduce
1. Add a new scene and go to the Events tab
2. Add an empty event
3. Click 'Add condition'
4. Search for 'timer' and click on 'Value of a timer'
5. Skip the object parameter, but enter 'test' as 'Timer's name' and 1 as 'Time in seconds' - click OK
6. Edit the same condition, search for 'timer' and click on 'Value of a scene timer' (this changes the original condition to the new one, copying over the parameter values)
7. Note that 'Time in seconds' is 'test' (syntax error) and 'Timer's name' is 1

![timers](https://user-images.githubusercontent.com/2385329/50660725-79458680-0fa9-11e9-9af3-5456bf3d3cd2.jpg)

**Comment by blurymind** [comment]
that is a very good catch! :)

**Comment by 4ian** [comment]
Indeed that's suboptimal. It's also a bit of a pain to migrate. One question though:
what would be the right order in your view? (I have an idea but want to know your views)

**Comment by Lizard-13** [comment]
My bad, I put the object timer params in the way I feel natural, didn't take into account the original order. But it's an engine problem more than UI, no?, or do you have a way to patch it with the IDE?

**Comment by BWPanda** [comment]
> what would be the right order in your view?

I don't really have a preference, but I'm all for consistency; both between timer events but also other events (e.g. I think from memory that other events put the value you're changing last...?)

**Comment by 4ian** [comment]
Yes in my view it's the "right answer", timer name should be first and the value at the end.

**Comment by PascalLadalle** [comment]
Actually, this problem is not limited to timers.
Some conditions/actions take more parameters than others, and others take completely different parameters.
For instance, when you switch from Play a sound to Play a sound on a channel, the channel identifier becomes "no" (loaded from the loop parameter). If then you switch to Delete a scene timer, for instance, the load path for the sound file is loaded as name of the timer.
Better than making sure the order is right, the values should be stored with a parameter id, so that they're only loaded when and where appropriate. That would also allow to go from sound to variables and back to sound and not lose the values. The buffer of values would then be wiped when the window is closed.
No idea how complicated that would be @4ian sorry. 😬

**Comment by gautamv95** [comment]
I looked into this, and found some solutions which might work:

`const gd::String initalValue = "the value which was chosen when saving the instruction"`
 ### 1) Pre-fill values in parameters based on parameter type
Those parameters will be pre-filled which have the same type.
So if one parameter is of the same type as `InitialValue`'s type, it will be filled with `initalValue`

**Implementation**
Can be implemented using std::map, with key as the parameter type and its map's value as `initalValue`

**Drawback**
- If an instruction has more than one parameter of the same type, it will be set to `initalValue` for both the parameters.
- There might be cases when parameters of two different extensions have the same type, but they have totally different context and no meaningful relationship can be formed between them. Eg: when choosing the event: **Current Animation**, we have to choose the operators, in "Sign of the test", this value is copied and gets pre-filled into "Channel" field when we chose a new event of **A sound is being played**

### 2) Pre-fill values in parameters based on parameter name
Those parameters will be pre-filled which have the same name.
So if one parameter has the same name as `InitialValue`'s name, it will be filled with `initalValue`

**Implementation**
Can be implemented using std::map, with key as the parameter name and its map's value as `initalValue`

**Drawback**
- If an instruction has more than one parameter of the same name(which is very rare), it will be set to `initalValue` for both the parameters.

**Advantage**
- With this approach, all the meaningless relationships will be resolved in the above approach and we can properly link parameter values.

**Assumptions**
- All parameters which have some relation must have same name.

### 3) No pre-fill at all
Since some instructions might be totally different in terms of context, it does not make sense to copy any parameter's value to another new instruction's parameter's value, even if the type/name is same.

**Drawback**
- Might be less user-friendly.

@4ian These are my views, can you please put in your thoughts/suggestions?

PS: I declared `initalValue` for the sake of explanation and would not be used in code 😅

**Comment by D8H** [comment]
This issue is fixed by:
* https://github.com/4ian/GDevelop/pull/3450

**Comment by 4ian** [comment]
I think we can close this one and open a new discussion for the "portability" of the arguments between actions/conditions (which I think we can do smartly without the need to annotate all parameters, by basing it on the type and order of the parameters)
