### ISSUE TITLE
Debugger returns errors and GD Crash

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#849]
## Describe the bug
When running a preview with the debugger, profiling or "refreshing the inspector" leads to a crash of GD. 

![image](https://user-images.githubusercontent.com/8144048/50730588-02e38880-1151-11e9-9b3d-5294a55e9227.png)

## To Reproduce
Unfortunately, i cannot determine what is the cause, or reproduce in a simple way.

It happens everytime if i refresh the inspector (even if the scene is at "pause"), and every time too with the profiler.

## Other details
Beta61, Windows 10

**Comment by 4ian** [comment]
The payload being extremely large means that there might be a very very heavy object to transfer between the game and the debugger. This is usually something that should not be there (like a Pixi texture) and should have been filtered out. If you can send me your game, I can surely debug it.

**Comment by KinkGD** [comment]
The game is not bugged, i just like to profile performances, and sometimes refreshing inspector because i'd like to check some values. 

Btw i can send you the project, but the number of objects actually used on the scene is far from the final expected number (i'd like really more objects, at least the same number i was able to handle on native platform of GD4, and until game performance aren't degraded).

No performance issues on the project, the issue is just that the debugger is totally unusable.

I'll send you the project by email.

**Comment by 4ian** [comment]
Fixed in 5f8546c3b99b4b42ac4488a0441998253e8924e1 - this was due to particle emitters sending way way too much data to debugger (well to be precise, the debugger wasn't filtering data).
Unfortunately you'll need for wait next version I'm afraid to use it :/

@Lizard-13 The fix was done by renaming the `renderer` of the particle emitter runtime object to `_renderer`, as it's done to other objects. The debugger will then filter this property (as well as other properties with specific names) to avoid getting too much data when getting a dump of the gdjs.RuntimeGame.
I could add "renderer" to the name of the filtered data... but I'd like to avoid. In the future, the debugger could just filter properties that start with a underscore, as it's kind of a convention in JS for "private" members.
All of this to say: I've seen that "renderer" is also used in the Skeleton objects. It's not an issue for now as it's not yet available in GD5, but maybe we should still fix this now or at least have a note to do it later. Where would you want to note this? I can keep it as a checklist on the roadmap on a card.

**Comment by KinkGD** [comment]
:)

Nice! Don't worry, i'll wait the next version.

**Comment by Lizard-13** [comment]
Added to my TODO :+1:

**Comment by 4ian** [comment]
Yeah the debugger should I think ignore all the "private" properties ideally. But that's a good reason to keep everything with an underscore if it's private :)
