### ISSUE TITLE
Objects are interactive even on a hidden layer [Preview]

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#857]
## Describe the bug
An object (text, sprite, others too?) on a layer whose visibility is on off is usable by a click or collisions.
This is possible in preview and game compiled [Here compiled game](http://gd-games.s3-website-eu-west-1.amazonaws.com/game-1546992246932/).

## To Reproduce
All is in this file
[layer_clickable_but_why.zip](https://github.com/4ian/GDevelop/files/2738822/layer_clickable_but_why.zip)

## Other details
* Win 10, GD5- Beta61

**Comment by blurymind** [comment]
I think it could be useful to be interactive on hidden layers. It would be
strange to have the visibility affect their behavior I'm. It should be up
to the programmer to decide when they are not interactive via another
action, separate from the visibility

**Comment by 4ian** [comment]
Indeed collision and click happen in the context of the "logical world" where things are not affected by their rendering, opacity or visibility.
This may be surprising, but also a desirable behavior one could want to continue having the collisions working properly even when a layer is not visible (for example, because there is some special effect going on, etc...).
This can also be a bit more surprising for clicks/touches - maybe a note in the description of the conditions would be useful?
