### ISSUE TITLE
Database support ? 

### ISSUE THREAD

**Issue by zilveer** [4ian/GDevelop#861]
Hi,
Does Gdevelop support databases and if so, where can I read about it ?

Regards

**Comment by 4ian** [comment]
Hi, issues are only for bugs with the software -  I'm very strict about it because otherwise it's counter productive for me to have to deal with questions and bugs and find the time to even do any work on GDevelop. For questions, please go to the forum or the discord ;)
(as for your question, there are storage actions (See the wiki for storage action) to store things not in a DB but in your game storage space. If you want to interact with a DB, you can make request to a web page that is interacting with a DB (an "API")).
