### ISSUE TITLE
"There is nothing to configure" popup

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#864]
## Describe the bug
When you add an expression that has no options/settings/parameters, you still get a popup with a message saying "There is nothing to configure" which you have to close. I'd rather this popup not display if there's nothing to configure...

## To Reproduce
1. Add a new action
2. Search for/click on 'Value of a scene variable'
3. Click the sigma button next to the 'Value' field
4. Search for/click on 'Identifier of the last touch'
5. Note pointless popup

![nothing](https://user-images.githubusercontent.com/2385329/51023744-46465880-1590-11e9-8b62-5007ef3b0d09.jpg)

**Comment by 4ian** [comment]
Thanks for reporting, it's true that this is indeed pointless but not entirely trivial to remove - even if not impossible. Could also be used later to display a few more information about the chosen expression.
Will tag "Non optimal UI behavior" for now.

**Comment by BWPanda** [comment]
If not possible to remove, maybe a way to automatically dismiss it...? (e.g. simulate clicking 'Done')

**Comment by 4ian** [comment]
Yeah, that's the "easy but dirty" way of doing it ;) (dirty because user will see the start of the dark overlay fading in and out - or maybe worse a beginning of the window to appear 😉). 
Proper solution is "simply" to not show the modal, but for this you have to analyze the expression to see that there is no parameters - knowing that there can be some "hidden" parameters that are asked by the expression to work properly (notably, the most common is a reference to the scene).

Nothing impossible again, but a bit of refactoring to do :)

**Comment by 4ian** [comment]
I've marked this as "Good first issue" in case someone wants to try it

**Comment by piyushpalawat99** [comment]
Hey, I just had a look at the expressions for which the "There is nothing to configure" popup appears. String expressions with no parameters are:

1. Insert a new line
2. Player identifier
3. Player name
4. Path delimiter

Numerical expressions with no parameters are:

1. Height of the screen/page
2. Width of the screen/page
3. Entire sensors category

Rest of the instructions include parameters, most common being `.AddCodeOnlyParameter("currentScene", "")`. Most of the expressions with the popup have parameters. In my opinion, if the popup is disabled for the expressions, it would result in odd results because some expressions will have the popup, while some won't.
