### ISSUE TITLE
Typo in wheel joint definition - Motor force instead of Torque!

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#870]
Somehow we missed this!

![2019-01-13 1](https://user-images.githubusercontent.com/17770123/51090597-f0cba080-1775-11e9-8e46-afed30d1f90c.png)

It's purely cosmetic but easy fix so just building and testing, although it's hardly going to break anything 🤣

**Comment by zatsme** [comment]
https://github.com/4ian/GDevelop/pull/871

**Comment by 4ian** [comment]
Merged, your PR, closing this :) Thanks for fixing!

**Comment by Lizard-13** [comment]
It's great to have somebody battle-testing it, because no matter how many times I recheck or use it, it was me the one that made the mistakes so there's a good chance to ignore the errors again, thanks a lot! :+1:

**Comment by 4ian** [comment]
@Lizard-13 Note that I've converted all the existing examples with the new physics engine and everything seems to be working good.
The only difference with the old behavior is that the direction of rotation is inversed when adding a torque. Is the new behavior having the correct one?

**Comment by Lizard-13** [comment]
Mmmh, what I did was removing all that coordinates conversion code, you don't need the Box2D world to be in the same coordinates at all, just synced with your "real" game world. So I removed all the -Y, -angle, and simplified a lot the parts both values were mixed. AFAIK all the angles (torque, angular speed, etc.) should be in the same system that GD angles, but I'll make sure right now :)

**Comment by Lizard-13** [comment]
@4ian Yup, the current direction matches the GD coordinates system :D

**Comment by 4ian** [comment]
Perfect then! 👌

>  So I removed all the -Y, -angle, and simplified a lot the parts both values were mixed.

Cool, thanks for rewriting this properly :) As you said what is important is the syncing, not the coordinates by themselves.

Not related, I was also thinking that maybe we should have, at least an option, to run the physics engine at a fixed time step. Most of the game without physics engine are fine with the adaptive time delta provided by GD, but in the physics engine this can introduce instability/different results for what seems the same inputs. Can be frustrating in games requiring carefully crafted conditions to achieve something (make a looping for example).

Note that maybe it's something that we should back directly in the game properties: either run at an adaptive time delta (with minimum FPS, which is something already in the game engine - so that the game "slow down" if FPS are not reached) or a fixed time delta (most probably 1/60) (which also means that the game will "slow down" if 60 FPS are not reached).

**Comment by Lizard-13** [comment]
So have the option to run the entire game at a fixed frame rate?, there was somebody asking for maximum fps in the forum: http://forum.compilgames.net/viewtopic.php?f=18&t=11049#p69663
So this would be useful for mobile too (battery drain) :)

If it's an option everything will be fine, options are the best, just some more maintenance work.

I can take a look, not right now but when find some time, I've to do that sprite sheets benchmark on my return too :)
