### ISSUE TITLE
Keyboard shortcut for 'Close Project' incorrect

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#875]
## Describe the bug
The keyboard shortcut for the 'Close Project' menu item (Ctrl-W) is incorrect - it closes GDevelop altogether and not just the current project.

## To Reproduce
1. Create a new project
2. Click on 'File > Close Project' (note the shortcut: Ctrl-W)
3. Note the text in the popup: "Close the project? ..."
4. Click OK and note that the project closes but GDevelop stays open
5. Create a new project
6. On your keyboard, press Ctrl and W keys
7. Note the text in the popup: "Are you sure you want to quit GDevelop? ..."
4. Click OK and note that GDevelop closes

**Comment by zatsme** [comment]
Windows 120 here and CTRL+W brings up the Exit GDevelop window, whereas if you click the menu close project it works as expected.

Is it different on Mac?

**Comment by 4ian** [comment]
Ok, can you locate in the menu if there is another item menu that would have Ctrl+W as shortcut?
I'll change it to Ctrl (or Cmd) + Shift + W anyway because that's the comment shortcut in IDEs and in browsers to close a project or a window, while Ctrl+W should close only the current tab.

**Comment by zatsme** [comment]
Specifically, CTRL+W gives you this and exits as expected!

![2019-01-17 1](https://user-images.githubusercontent.com/17770123/51337025-fb3fb000-1a7d-11e9-8d85-7582e9f11019.png)

**Comment by 4ian** [comment]
Looks like Ctrl+W is "automatically" binded to closing the window on Windows?

**Comment by zatsme** [comment]
Ah, there are two CTRL+W in the menu!

![2019-01-17 2](https://user-images.githubusercontent.com/17770123/51337168-5376b200-1a7e-11e9-9619-0d79efe655f5.png)

**Comment by zatsme** [comment]
So it's triggering the windows close and not the project close... 🤔

**Comment by 4ian** [comment]
Here we go :) That's the default system behavior it seems (I've not added it myself, I just asked to get the system "Window" menu)... It's not there on macOS. 

![image](https://user-images.githubusercontent.com/1280130/51337274-8f117c00-1a7e-11e9-889e-fb1c4e4e1597.png)

Still a pain because Ctrl+W is more for closing the current tab, and I wanted to use this to allow to close an editor. Anyway, I've done the changes for next version to close with Ctrl+Shift+W :) Closing this for now

**Comment by 4ian** [comment]
Thanks @BWPanda for reporting this btw :)

**Comment by BWPanda** [comment]
I'm a bit confused, so sorry if this is what you were saying already, but I just checked Atom and GIMP, and both of them have Ctrl + W for closing the tab/view, and Ctrl + Shift + W for closing the window/all.

Is that how GD will work in future too?

**Comment by 4ian** [comment]
Ctrl + Shift + W to close the project (which is equivalent to closing the window in my view, because GD only has one window) and Ctrl + W for closing the tab/view

**Comment by zatsme** [comment]
I wonder what gimp, atom and Firefox do on windows, override the o/s menu?

**Comment by BWPanda** [comment]
I'm on Linux BTW... ;-)

**Comment by zatsme** [comment]
We know 😏

I'm afk so can't test until later on Windows, but I don't know if we keep
same keys for all o/s or have different.

Would unnecessarily complicate imo 🤔

**Comment by 4ian** [comment]
Good to precise because I thought it was only on Windows ;)
Might be solved by removing all together the "Window" menu, I think it's useless - apart from annoying us with this default shortcut that we don't want.

**Comment by 4ian** [comment]
Removed the close option on Windows and Linux: https://github.com/4ian/GDevelop/commit/8e83f1581e71ebf29c1640cf7f839585dece8087

This way no irritating Ctrl+W shortcut on Windows and Linux.
Also moved "About GDevelop" menu item to help menu on Windows/Linux for consistency with other programs.

Now, ideally Ctrl+W would be mapped to closing the current editor, as this would mimic what browsers/VS code/atom are doing (closing a tab). I think it's fair to keep Ctrl+Shift+W to "Close Project", because for now GDevelop is single project/single window. When there is support for multiple projects, surely in different windows, then we can make it close the current window.
Should be good enough I think?

**Comment by 4ian** [comment]
If anyone want to try to implement Ctrl+W, could be useful :)
