### ISSUE TITLE
"Play Music on a Channel" action not working like it used to.

### ISSUE THREAD

**Issue by Shadowbonnie7** [4ian/GDevelop#878]
The action "Play Music on a Channel" does not play your music file. if one was to have music play at the beginning of a scene, no music will play in the preview.

## To Reproduce
1. Create a new project.
2. Put the condition "At the Beginning of the Scene" in conditions.
3. Put the action "Play a Music File on a Channel" in the corresponding actions and have it play a music file.
4. Save and preview. Chances are that the music file you told the game to play will not play.

Using Windows

In the meantime, there is a workaround to this problem. If you play the music file as a SOUND instead, it WILL play, like in mobile.

**Comment by KinkGD** [comment]
+1, i know this bug ! But it's strange because its working on local export. 
Also, in the preview : if you change scene for another, then come back to the scene where you sound file should play at beginning, it works..
Did you tried to build/export the game to windows (as executable ?).

**Comment by zatsme** [comment]
Yes, I press Esc to restart scene and as soon as you do that it's working, no delay, odd?!

**Comment by zatsme** [comment]
I understand that, but does it explain why sound command works, but music doesn't?

I just tested and the same mp3 music file doesn't play until scene refresh, but it works fine if played using the play sound command?

**Comment by 4ian** [comment]
Oh not sure about this, will have to investigate what is the difference then!

**Comment by Shadowbonnie7** [comment]
I did not export the project, to answer KinkGD's question. Does it work on export?

**Comment by zatsme** [comment]
Is this the same issue as https://github.com/4ian/GDevelop/issues/556?

**Comment by zatsme** [comment]
> Oh not sure about this, will have to investigate what is the difference then!

Answer is that Music forces HTML5 audio and Sound uses Web Audio by default.

![2019-02-15](https://user-images.githubusercontent.com/17770123/52889861-ca849080-3179-11e9-8053-95642da7c233.png)


I changed this line (237) in howler-sound-manager.js and then Sound and Music behaved the same, a delay before playing sound as Web Audio has to load the whole sound, whereas HTML5 Sound plays while loading.  

Not sure how you might change it to make it work any better, HTML5 playback is fine after a click or touch!

**Comment by 4ian** [comment]
Super interesting, I never realized this was related to this.
Ideally, the long term solution would still to either issue a warning ("for music to work in browsers, you have to launch it after the user interact with the screen") or work around this (put the music to play in some cache, and when the user interact, launch the music that was waiting, so that it's "almost" working).

**Comment by 4ian** [comment]
Actually, updating Howler.js sound library might be enough. I see commits related to audio locking: https://github.com/goldfire/howler.js/commits/master

We're on v2.0.7, while 2.1.1 is available. There is a card for it: https://trello.com/c/lV2jnvBq/163-update-howlerjs-to-latest-version

**Comment by zatsme** [comment]
I'll have a go at updating howler.js as I'm familiar with the issues, is this purely js or was it converted from GD4?  Do I just need to check for any API changes, update the js file and test?

**Comment by 4ian** [comment]
This is purely JS. 

> Do I just need to check for any API changes, update the js file and test?

Exactly :)

If there are some API changes, any changes should be in howler-sound-manager.js (so should be pretty limited - the rest of the engine is agnostic toward the sound manager implementation).

**Comment by Silver-Streak** [comment]
Looks like this was last updated in Feb. I'm seeing a bunch of new folks on the discord asking about this. My understanding is howler is now updated, but this issue still persists (play music/play music on channel do not play any files, while play sound/play sound on channel can play the same files fine).

Is there any other testing I can assist with on this that might help pinpoint it, or is there still a path forwards towards resolution being worked on?

**Comment by zatsme** [comment]
This is the browser working as designed. 

If you play as Music gd forces HTML5 audio, whereas play as Sound uses Web Audio. 

See my post 3 months ago for more detail on the differences 😊

**Comment by Silver-Streak** [comment]
> This is the browser working as designed.
> 
> If you play as Music gd forces HTML5 audio, whereas play as Sound uses Web Audio.
> 
> See my post 3 months ago for more detail on the differences 😊
> 
> Maybe we need to change the ide and doc to say Web Audio instead of Sound, and HTML stream instead of Music. 🤔

Thanks for the heads up, Zatsme. Just to check, would that impact Game Preview in addition to exported to HTML? Because using Play Music also doesn't work when previewing a game in most cases.

**Comment by zatsme** [comment]
ok, hopefully to clear it up:-

**If you use play sound:**

This uses the older Web Audio which cannot stream files.

Soundfile will load and play as soon as it's completely loaded, almost instantly for short effects, longer for music depending on filesize!!

**If you use play music:**

This uses HTML5 Audio which can stream files.

Soundfile can start to play as it's being loaded (stream) which is a better/newer system.

> 
> However, latest browser fixes do not permit any audio until user interaction so you must make user click/touch first although this could change again and be different for each browser.
> 
> Best bet is to have a loding/intro screen to click on and then use the HTML5 Audio to stream the music.

😖

**Comment by 4ian** [comment]
@zatsme is right. No way to work around this (other than loading/intro screen with a click/touch to start). Any idea to make this clearer in GDevelop is welcome!

**Comment by Silver-Streak** [comment]
@4ian @zatsme 
Thanks for the info. Recommendations: I would update the description of the Play Music events to specifically call out "This will only work in a browser if the player clicks on the game window itself."

That said, I still want to reconfirm: Does the above explain why the game preview doesn't work with Play Music either? Is preview mode still held by the same limitations as playing a hosted exported HTML game in a browser?

**Comment by 4ian** [comment]
Yes, because preview is running inside (basically) Chrome which has this limitation built in :(

**Comment by Silver-Streak** [comment]
Thanks for the heads up and clarification. Makes unfortunate sense to me.

**Comment by 4ian** [comment]
I've added this alert when using an action to play a music (or play a music on a channel):
![image](https://user-images.githubusercontent.com/1280130/58458182-70a04900-8120-11e9-87a1-f5f427c97498.png)

**Comment by PascalLadalle** [comment]
Since this is still open, I'm adding feedback from a confused user:

> Lotness: yeah I read that [warning]... from what I understood music should have started once I moved my character around (user interaction) and it wasn't working.
that's why I was a little confused :slight_smile:
Me: hmm...we can try to rephrase it, but the last sentence should be clear enough... :thinking:
Lotness: yup, it seemed plenty clear.  From how I read it, the action I had set out should have started playing once I started moving my character around, or firing or a jump or any other mouse/keyboard event.

So the warning has been understood as "music will only be played when user has interacted with the game".
Perhaps something more _practical_: "This action is incompatible with "at the beginning of the scene". In such cases, use the sound actions instead.", because I guess that _most_ music files are meant to be played at the beginning of scenes...

**Comment by Orghal** [comment]
Hello guys,
I am beginner here so I try make clear description - here is real solution for you all.
I found this out after many trials and compilations because like all of you know - peoples, users and probably customers too, hate technical problems, do not understand Chrome or any browser configurations and especially what is this called "streaming".
For us all of it is clear but here it is, how to skip the problem once and happy:

I checked it after 3 hours testing, compilations and publishing and it works:

- convert/create your music file as a MP4 -> H.264 and AAC audio (128 or 160 kbps),
- create object in your project and set it up as Global - right mouse button -> submenu -> choose "Set as global object" (if you want this music across every scene and available to control). Object should change style in list to bold-italic,
- better when you do it like a small object (it can be few pixels or something) so you can touch it in the scene,
- for me very simple - I create top right corner small logo, like ID for tv news, tv station etc. It is good for your advertise object :)
- put it in your starting scene where music start, not need to be in first one,
- add the Action "Plate the video of [video_name]" in the Events "At the beginning of the scene",
- it start you music non stop, don't forget loop it,
- good for this corner "logo" object make a transparency, so if you don't have any graphic content just set it to 0 - so no one see it.

All of this I checked in build application - any kind, publish for website (Liluo.io) and... it works :) Not sure every Android but I checked 8.0, 8.1, 9.0 and 11 it is okay too.

Very nice option to do any video especially for this problem if free software DaVinci Resolve 17, my recommendation guys :) Video settings for the smallest thing (you can scale it on the scene later), and very small file with music:
Format: MP4 / Codec H.264 / Resolution 420 x 256 / Frame rate - any, if you make nice logo 24 is enough :)

My logo with music its just 2MB and fade-in/out only.

Best regards to all
Orghal

**Comment by Silver-Streak** [comment]
Hello @Orghal,

Normally you shouldn't be posting in a closed issue, especially one that has been closed for ~3 years.

For the issue in this thread, the recommended solution is to use the "Play a sound on a channel" events instead of the "Play a music on a channel". Keep in mind "Play a sound" means "Play a sound file" not "Play a sound effect"

I'm glad you found another solution that works for you, but keep in mind it isn't needed to avoid this issue with audio files not starting with the game before it is interacted with.
