### ISSUE TITLE
Changing animation sprite and then immediately selecting a sprite Point : wrong animation took in count

### ISSUE THREAD

**Issue by KinkGD** [4ian/GDevelop#879]
## Describe the bug
When changing animation number (or by name) "at the beginning of the scene", then selecting a sprite point (PointX();PointY()) always return the custom point form animation #0 

![image](https://user-images.githubusercontent.com/8144048/51212437-c82fdc00-1918-11e9-9934-f7f0922b2234.png)
![image](https://user-images.githubusercontent.com/8144048/51212472-dd0c6f80-1918-11e9-89ff-914197521b63.png)

## To Reproduce
Open the attached project that illustrate the issue, and "Edit Points" of the object "Player" to understand : 
[SpritePointsAtBeginningOfScene.zip](https://github.com/4ian/GDevelop/files/2761633/SpritePointsAtBeginningOfScene.zip)

## Other details
Windows 10 x64, GD5.b62 (and previous!)

**Comment by 4ian** [comment]
Sprites are updated only at the end of events. This is made to avoid making heavy computations to change the animation each time you change the animation, if for some reason you're having multiple actions changing the animation.

I'll edit your title because it's not related to beginning of the scene. It's related to using points just after trying to change an animation but without waiting for the end of the events of this frame. It's a bit surprising indeed.

**Comment by KinkGD** [comment]
ok! That's what i understood but that was a bit hard to explain  for me :p 

I already use a work around to select the Point at frame+1 (after a trigger one or scene beginning), but it's bit annoying, because i'm changing a lot of sprite animation at the beginning of the scene.
