### ISSUE TITLE
Online build allows splash-screen removal without subscription 

### ISSUE THREAD

**Issue by zatsme** [4ian/GDevelop#885]
If you edit the game.json and do this:-

 "loadingScreen": {
      "showGDevelopSplash": false
    },

then there appears to be no check when the file arrives at the build server!

😨

**Comment by Wend1go** [comment]
Well after all it is just human readable Json + HTML5/JavaScript. Nothing gets compiled into machine code.
You can even substitute the GD splash with another image after using the build service, _if you know how_.
;-)

**Comment by zatsme** [comment]
I know how, but most people don't and will get a subscription as its cheap and easier than mucking about with the code.  But this is too easy to do.

**Comment by 4ian** [comment]
> I guess the point of the build service is just making it less cumbersome to publish a game. You can achieve everything the build service is doing yourself on your local computer. It just takes time to set everything up.

Yes exactly.

For now I haven't added any hard protection because I have other things to do and I'm confident people won't abuse the system. GDevelop is open-source, subscriptions are to support its development. If people want to cheat, they can do it but that means that I'll maybe at some point add a hard check in the build service for this - or more complicated checks in the app to avoid abusing the system.
In the meantime, I put my confidence in the users :)
