### ISSUE TITLE
gdevelop newIde doesn't restore opened editors from previous sessions

### ISSUE THREAD

**Issue by blurymind** [4ian/GDevelop#893]
## Describe the bug
Super annoying bug, the newIde closes all tabs after saving a project that has more than one scene

## To Reproduce
1. Open the platformer example
2. Create a second layout and open it
3. Save the project
4. Close the project
5. Reopen the project - all of the editors tabs you had previously opened are now closed. 

You have to reopen them all again every time you open your project :(

**Comment by 4ian** [comment]
Huh, it's not a bug right? It's clearly a new feature request? Then this goes to the roadmap please :)
I'm trying hard to keep things organized ;)

**Comment by 4ian** [comment]
I'm strict on this because if we start labelling "bugs" what is just requests for improvements, we are giving everything the same priority, we can't distinguish between the real urgent bugs and the wish lists, and we end up working on the wrong things. There are tons of things to do on GDevelop, if we classify them improperly it's dangerous for the project as a whole => people will try to keep flagging their requests as "bugs", which is demotivating and give a bad feeling about GDevelop.

**Comment by blurymind** [comment]
Sorry I misidentified it as a bug, as it was unexpected behavior. When you open a demo scene, gdevelop loads it normally - layout and event sheet tabs automatically open, but whenever you add another layout and save, gdevelop no longer loads any of the tabs and makes you do it manually.

I can look into this if nobody is tackling it, once sorting out the other things :) 
It's a serious issue imo, as it adds a few extra laborious steps to every time you open a project. It would be great if the UI session state is remembered

**Comment by 4ian** [comment]
Opening the first scene is just a mere convenience that is done because I observed a lot of people trying GDevelop for the first time, and even if the project manager was opening automatically, there were having a hard time locating the scene and opening it.

It's because the first time you're trying GDevelop, you want to "see things" as soon as possible. You don't have the concept of different scenes in mind. So most examples are composed of a single scene, that is opening automatically.

A soon as you add another scene to your game, it means that you have been able to open the project manager, and that you are familiar with it, as you've been able to add a scene and probably open it.
Then, as soon as a game has more than one scene, I revert to the classic behavior: open the scene manager and wait for the user to do something. It's also not a good idea to open everything because for very large game this could make GDevelop take too much memory (even crash for super large games).

So for now there is not even a notion of "UI session state" remembered. I don't think there is a card for it on the roadmap => You can create it, with label "IDE" :)

Note that while no scene is opened by default, the search field is focused, so you can directly start typing the name of the scene you want to open and click on it - so for large games it's very fast. The best thing would be to map "Enter" to open the first result when doing a search (like it's done for conditions and actions).
