### ISSUE TITLE
(Question) New parameter type "StringListField" for JSExtensions

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#905]
I would like to add an additional type of parameter to be used in JsExtensions: "StringListField".
The goal is to make it possible to add a JavaScript array of strings in the JsExtension.js file as an additional property of the JSExtension class where one can specify the values that are presented to the user when opening the conditions/actions editor in the IDE as a combo box similar to the keyboard keys or mouse button list but in a "dynamic" way.
(This would be a prerequisite for an upcoming Tweening extension. In the discussion on [Trello](https://trello.com/c/FjxDsXpc/213-add-tweening-animations), we came to the conclusion to limit the tweening to certain properties only)

After looking through the code, I think that I could create the list for the StringListField similar to the [KeyField ](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/ParameterFields/KeyField.js)  but I'd need to somehow feed the array which gets defined in JsExtension.js to the StringListField component. I guess the [ParameterRenderingService ](https://github.com/4ian/GDevelop/blob/c00e98639a8cae8e911490bc81b9399976b420ff/newIDE/app/src/EventsSheet/ParameterRenderingService.js) also needs to be edited.

So my questions are basically:
- How can I extend the PlatformExtension to accept such an array as an additional parameter?
- How should I pass it over to the StringListField?
- What do I need to do in order to pass the array over to the function implementation inside the extensiontools.js and other functions as a parameter?

**Comment by zatsme** [comment]
Does this tie in with the conversation we had in https://github.com/4ian/GDevelop/issues/747 where we came to the conclusion that lists would be good to add to GD5?  As in lists of objects, joint I'd, variables, anything really?

**Comment by Wend1go** [comment]
No those lists are something different.
What I have in mind is a static list of items that the developer of an extension defines inside the JsExtension.js and that won't change at runtime.

So that in the TweeningExtension we could define items like:
- X
- Y
- SizeX
- SizeY
- Opacity

As the only valid properties that can be chosen.

**Comment by 4ian** [comment]
Sorry for not answering before, was busy all the week-end :)

> What do I need to do in order to pass the array over to the function implementation inside the extensiontools.js and other functions as a parameter?

At the end (in generated code), this parameter would probably be a string. So that the tweening extension functions would receive directly the name of the property to tween, and will compare it in a list/dictionary of supported tween properties.
A slightly more optimized solution would be to pass an integer (using "constants" in JS to represent them. `gdjs.Tweening.PROPERTY_X = 0; gdjs.Tweening.PROPERTY_Y = 1`, etc), but the rest of my comment is fine for both.

> How can I extend the PlatformExtension to accept such an array as an additional parameter?

Parameter "metadata" are handled by a (C++) class named ParameterMetadata: https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Extensions/Metadata/InstructionMetadata.h#L36

At the end (in generated code), this parameter would probably be a string, so we would add it here: https://github.com/4ian/GDevelop/blob/master/Core/GDCore/Extensions/Metadata/InstructionMetadata.h#L167

We're lucky because I think all that is needed to support a new parameter type in GDevelop Core (GDevelop.js), and we already have something for passing list. You could use it like this:
`.addParameter("string-within-list", t("Property to tween"), "[\"X\", \"Y\", \"Width\", \"Height\", \"Opacity\"]", false)`

(I filled the "supplementary information" parameter with a JSON array, because I think it's the most portable way of storing data here).

Finally, in GDevelop 5, we would add a new field, similar to [KeyField](https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/ParameterFields/KeyField.js) as you mentioned. Except that the content of the list would be generated from the array which is parsed from the parameter metadata:

```
const { parameterMetadata } = this.props;
let choices = [];
try {
  choices = JSON.parse(parameterMetadata.getExtraInfo());
} catch(exception) {
  console.error("The parameter seems misconfigured, as an array of choices could not be extracted - verify that your properly wrote a list of choices in JSON format. Full exception is:", exception);
}

// Iterate over `choices` to display the list.
```

**Comment by 4ian** [comment]
Closing as added
