### ISSUE TITLE
created most of my game in 4.0 but gd5 does not support both basic "path" and "controller" features, when can this be fixed?

### ISSUE THREAD

**Issue by jbkinz** [4ian/GDevelop#910]
BEFORE opening a new feature request, please make sure that you:
 * Discussed about it on the discord or the forum,
 * There is not already a suggestion about it in the issues or in the roadmap: https://trello.com/b/qf0lM7k8/gdevelop-roadmap
 * Consider commenting on the roadmap if something is important for you

AFTER opening the feature request, the issue will be closed by a maintainer (@4ian or someone else) and a card will be added in the roadmap if it's relevant and does not exist yet :)

## Description
Is your feature request **related to a problem**? Please describe.

## Solution suggested
**Describe the solution**
A clear and concise description of what could be done.

Explain if you can help implementing the solution.

**Comment by 4ian** [comment]
Please follow the template before opening issue, otherwise this will become a huge mess and will impact our ability to work on the project directly ;)

As for your question, you have to do without as they are not available for now. Actually, you have an example showing how to support a controller. Path extension was not asked a lot by the community so for now it's low priority.
