### ISSUE TITLE
(Question) Tween extension

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#921]
I need a little advise for my tween extension.
I'm currently saving the tween instances in a two dimensional array:
```
gdjs.TweenRuntimeBehavior._tweenList[owner][identifier] = new gdjs.TweenRuntimeBehavior.ObjectPositionTweenInstance(bla,...)
```
`owner` is the gameObject instance that holds the tween (passed over as a parameter with `objectPtr` type) and `identifier` is a string with the name of the tween animation, so that I can later refer to each tween instance.
This works perfectly when I only have one instance in the scene, but after adding a second instance of the same sprite object the JS interpreter is not able to differentiate the two instances from each other.

Before adding a new tween, I check if it already exists:
```
gdjs.TweenRuntimeBehavior._tweenExists = (owner, identifier) => {
  if (owner in gdjs.TweenRuntimeBehavior._tweenList) {
    if (identifier in gdjs.TweenRuntimeBehavior._tweenList[owner]) {
      return true
    }
  }
  return false;
};
```
When I have one sprite object instance with a playing tween animation in the scene and add an additional  instance of the same sprite object the tween instance gets replaced by a new one and the whole thing blows up. Adding a breakpoint and hovering the mouse over the `_tweenList` I can see that it already holds a sprite object instance with the object id = 2 (which is correct). The new instance to check against holds an object id = 3. So they are definitely not the same instance. But the function returns true non the less.
I have the impression that it only compares the object type and not the individual instance stored in the array.
Is there an other way to check for the existence of an instance inside the array? 
Or what would be the best way to accomplish this?

**Comment by Lizard-13** [comment]
I think the tween should be a behavior, so each object instance has its own tween object, check the first 4ian comment in the card: https://trello.com/c/FjxDsXpc/213-add-tweening-animations#comment-5c1509304062c945963129bc

**Comment by Wend1go** [comment]
Here is what I have so far #922

**Comment by 4ian** [comment]
I'll close the question as we have the PR to discuss and that you switch to behavior methods anyway :)

As far your original question, this is because when you did: `gdjs.TweenRuntimeBehavior._tweenList[owner]`, javascript is implictly transforming your object to a string (by calling the default `toString` method) - and this string is the same (it's basically the constructor/"class" name) for all instances. Instead, you would have wanted to store some kind of unique id for each object... but it would have been an anti-pattern, using behaviors and behavior action/condition is the way to go. It's idiomatic JS and much faster than storing things with some kind of id.
