### ISSUE TITLE
Buttons of the text window out of sight

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#959]
## Describe the bug
If a text object has a lot of text (e.g. structured JSON text), when trying to edit it, the buttons Apply and Cancel aren't visible until GD has been resized.

## To Reproduce
Create a text object with +20 lines.
Right-click on the text object and choose Edit object.
OR
Create a text object, and paste +20 lines in it.

## Other details
Windows 10
As soon as I resize GD, the buttons show up. So there seems to be a check in place, but not applied until the window is resized.

**Comment by 4ian** [comment]
I've limited the height of the text area, so that this is this part that will be scrolling if the text is too long, and not the whole editor content. This is what was creating the glitch.

![image](https://user-images.githubusercontent.com/1280130/53995516-26b15380-412d-11e9-9cf2-ec3b31f30999.png)

Fix will be in the next version, thanks for reporting this!
