### ISSUE TITLE
Renaming an object don't rename it in For Each events

### ISSUE THREAD

**Issue by xiscoj** [4ian/GDevelop#970]
gdevelop 5 beta 64.
Changed the name of an object and not.all the references changed in the scene code.
Exactly the ones inside
For each object nameofobject
weren't changed

**Comment by Wend1go** [comment]
I noticed the same with the objects passed to a JavaScript event.

**Comment by 4ian** [comment]
Right, this is because expression in Repeat event, and the object in For Each or a JS event are not recognized as such (they are just strings). To fix this, internally they should expose this as "event adhoc parameters" with a proper type. 
And the refactoring classes should also run the refactoring on these parameters (in addition to condition/action parameters)

**Comment by Wend1go** [comment]
A proper header for the 3 event types would be nice. These "text in text variables" looks really out of place and aren't very intuitive to use.

**Comment by 4ian** [comment]
Any improvement there is welcome :) The core of the issue still is more in the events (ForEachEvent.cpp, RepeatEvent.cpp and BaseEvent.h). The BaseEvent should have a method that can be called to expose the event parameters. So that refactoring can pick them.

**Comment by 4ian** [comment]
This was fixed in 4eb8ddfba6554cb909b1295beea182cec4ed24cc (For Each, Repeat and JavaScript Code Event) are properly updated when an object is renamed. Will be in next version of GDevelop.
