### ISSUE TITLE
Crash during select other path folder 

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#973]
## Describe the bug
When you wish change the creation folder of a project the button doesn't work anymore.
Only on b65, i've tested b64.

In developer tools i've this : **"Paused before potential out-of-memory crash"** 

(Thanks to users on Discord for spotted this)

## To Reproduce
- Create a new project
- Change path folder
- Don't work ( Sometimes freeze)

[Video](https://cdn.discordapp.com/attachments/377571085643677696/555432667655438346/Desktop_2019.03.13_-_18.48.48.01.mp4)

## Other details
Beta 65, win10

**Comment by blurymind** [comment]
interesting, this is a pretty bad one

**Comment by 4ian** [comment]
Ok, this is because `<Trans></Trans>` is passed to electron api which is expecting a string (freeze is because the `<Trans>` object is a React element, and when trying to serialize it there seems to be an infinite loop).

Proper solution would be to use i18n._(t`thing to translate`). And also to update flow types to avoid such errors.

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GDevelop/commit/dde8d086936da7b9cf5948e06af0ab2054f4401f
