### ISSUE TITLE
allow zero on animation speed = paused animation

### ISSUE THREAD

**Issue by raMASTER** [4ian/GDevelop#992]
for static animations when frames are changed manually i.e. like an health bar that changes sprite only when player gets hit

![S](https://user-images.githubusercontent.com/21316995/55220606-8b793e80-51ff-11e9-960e-47969f113bed.png)

**Comment by 4ian** [comment]
I think it's not a good idea because this was actually crashing the game engine that would not understand a time of 0 between each frame. 
0 would mean an infinite speed, because there is literally *no time* between frames. So the animation would run at "infinity" frame per second.

There are actions to pause animation, better use them. If you really want to pause animation, then in this case it would be better to have a pause button in the toolbar.

**Comment by 4ian** [comment]
(For enhancements, prefer the forum/roadmap though)

**Comment by blurymind** [comment]
@4ian I think that the problem is that people often mistake the value with
frames per second - which is what most game engines tend to use. Logically
when setting the fps to a lower value- the animation slows down and
setting  it to zero stops it
