### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [4ian/GDevelop#994]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [b2Triangle](https://github.com/4ian/GDevelop/blob/97aeafc4c37f97f9784846c77b6d71f8c765b476/Extensions/PhysicsBehavior/Box2D/Contributions/Utilities/ConvexDecomposition/b2Triangle.cpp#L40)
- [RuntimeScenePhysicsDatas](https://github.com/4ian/GDevelop/blob/97aeafc4c37f97f9784846c77b6d71f8c765b476/Extensions/PhysicsBehavior/RuntimeScenePhysicsDatas.cpp#L14)

**Comment by 4ian** [comment]
So yes and no 😄

* b2Triangle is part of Box2D, so I think any improvement there should go directly to Box2D. Unlikely though that they would like to use smart pointers everywhere.
* For RuntimeScenePhysicsDatas, yes if it has a compelling reason/advantage.
Note that both of these are now used in the C++ version of PhysicsBehavior, which is only used by games running with GDCpp, which is not used anymore by GDevelop 5.

So this is very low priority for now :) 
* Improving GDevelop Core (GDCore folder) C++ codebase with safest alternative like smart pointers is more interesting (as much as possible, that's what I do :)).
*Note that `IDE` folder (old GDevelop 4 editor) will be deleted as some point. 
* GDCpp and extensions in C++ are kept there because they might be re-introduced in GD5, so feel free to do suggest improvements even though it's lower priority than the rest as explained.

**Comment by 4ian** [comment]
Closing as useless then
